### ISSUE TITLE
Option to prevent autoplaying videos

### ISSUE THREAD

**Issue by FLHerne** [qutebrowser/qutebrowser#1643]
(feature request)
Most other browsers (Firefox, Opera, Chrome) have the option to prevent HTML5 video from being played until the user directly interacts with it, or in some variants until the relevant tab is focused.

This is very useful when opening YouTube or other videos in background tabs, otherwise they start playing immediately and force a tab change to pause them.

An equivalent feature would be useful in Qutebrowser.

**Comment by The-Compiler** [comment]
I'm not sure if this is doable without relevant API additions from QtWebEngine - maybe via JS somehow

**Comment by The-Compiler** [comment]
See [QTBUG-60799](https://bugreports.qt.io/browse/QTBUG-60799) and https://github.com/annulen/webkit/issues/357 - also #2626 will allow to block video data entirely.

**Comment by lahwaacz** [comment]
I think that QtWebEngine does not auto-play any `<audio>` or `<video>` elements by itself. On pages like YouTube where they start playing immediately it's due to javascript. This also makes it harder to auto-stop them from qutebrowser by javascript, because the injected code would have to run after the page actually started the video.

I'm wondering, though, how Chromium does the thing that when e.g. a YouTube page is opened in a background tab, the page is loaded as indicated by the favicon spinner, but the video does not play until the tab is focused. It's not a click-to-play nor auto-stop, but does do the job at preventing multiple sources playing simultaneously.

**Comment by pkillnine** [comment]
@lahwaacz maybe chromium exposes to javascript whether the page has been focused, and then Youtube starts the video whent he page is focused?

**Comment by lahwaacz** [comment]
@pkillnine I think that's unlikely, because it happens for _every_ site which auto-plays videos, not only YouTube, so it would be a huge coincidence that all javascript players actually use that extra information exposed by Chromium.

**Comment by The-Compiler** [comment]
FWIW `<video>` does have an `autoplay` attribute, see e.g. [this demo](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_autoplay).

WebKit also recently [started blocking](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/) autoplay for those.

Even Youtube seems to use a `<video>` tag, even if it's with some custom JavaScript aroun dit.

**Comment by The-Compiler** [comment]
Relevant change for Qt 5.11 in QtWebEngine: https://codereview.qt-project.org/#/c/209240/

Looking at that, it might be possible to set it via the commandline already.

**Comment by The-Compiler** [comment]
Quick update: The related change now [landed](https://github.com/qt/qtwebengine/commit/18ea13a7f5e083538910646c52a96a5e4642d1f2) in Qt 5.11.

**Comment by slump64** [comment]
So is there any work on this happening rn?

**Comment by The-Compiler** [comment]
@slump64 Not that I know of. Qt 5.11 also isn't out yet.

**Comment by asmbits** [comment]
this setting stopped working for me recently, videos on youtube are playing automatically with content.autoplay = false

**Comment by gadefox** [comment]
FYI `content.autoplay = false` has no effect on youtube videos..

**Comment by domWalters** [comment]
> FYI `content.autoplay = false` has no effect on youtube videos..

I just tried adding `c.content.autoplay = False` to my config and it did stop youtube autoplay on browser start / tab refresh for me.

It also appears to still allow the youtube autoplay to work, so when a video finished it will play the next one without user input.

---

Version:
```
qutebrowser v3.5.1
Git commit: 
Backend: QtWebEngine 6.9.1
  based on Chromium 130.0.6723.192
  with security patches up to 136.0.7103.114 (plus any distribution patches)
  (source: api)
Qt: 6.9.1

CPython: 3.12.11
PyQt: 6.9.0

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)
```

**Comment by prosoitos** [comment]
```python
content.autoplay = false
```

works for me for the videos on some sites, but not others.

Examples where this is not working:

- Some videos with simple autoplay tags:

https://docs.marimo.io/guides/interactivity/

This one has a fairly straightforward `<video autoplay muted loop>` tag, but the videos are not blocked.
 
- Some videos for which I have no idea what is going on:
 
https://www.nytimes.com/

**Comment by Chiitoo** [comment]
As far as I understand, in general, disabling auto-play in Chromium, and thus in Qt WebEngine as well at this point in time, means muted videos are free to play.

If I remember right, there is even a whitelist, though I don't think that is being used at all in Qt WebEngine, and some other funny "algorithms" that Chromium developers use to decide who are allowed to auto-play regardless what the setting says.

With that in mind, of course sites will abuse this fact and always go for muted, at least if they can check that the browser has auto-play "disabled".

I've been using a local patc^Whack to make Qt WebEngine /really/ stop auto-play, but it's nowhere near presentable for anyone else to use.

Having written that, I don't think qutebrowser can really do anything about it, without maybe some kind of an extension/script, but in any case, I suppose a Qt WebEngine feature request would be more helpful in general, if accepted to be implemented (been meaning to file one such request since 2017 maybe... ooops).

Chromium extension support is being worked on [1], but I'm not sure one like that would be helpful here.

1. https://bugreports.qt.io/browse/QTBUG-61676

**Comment by prosoitos** [comment]
Ah! That explains so much... this was very useful to at least understand what is going on. Thank you!

(Indeed, the videos that autoplay are always muted. I had never realized this).

**Comment by Chiitoo** [comment]
Forgot to mention something that might be of some interest, and for context and all, I believe this is where most, if not all of the checks happen, and where I've been tweaking things:

https://code.qt.io/cgit/qt/qtwebengine-chromium.git/tree/chromium/third_party/blink/renderer/core/html/media/autoplay_policy.cc?h=134-based
