### ISSUE TITLE
Start using coala?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1740]
[coala](http://coala-analyzer.org/) seems to be a nice frontend for various linters - we could integrate the existing linters and probably add some more.

There's also [GitMate](http://gitmate.io/) which does line-comments on PRs (see e.g. the outdated comments in https://github.com/coala-analyzer/coala/pull/2435).

**Comment by rcorre** [comment]
Your link for [GitMate](http://gitmate.io/) is wrong :wink:

**Comment by The-Compiler** [comment]
~~is~~ was :wink:

**Comment by sils1297** [comment]
Hey, I'm the author of GitMate (and the one who did the main talk about coala). GitMate will by default do much more than just run coala, it'll attempt to automate your whole workflow by a bit. This saves us tons of time. However, it might be that it doesn't do it in the right workflow for you, e.g. it only does commit based review (every single commit will be checked individually from GitMate, not the whole PR, it'll also do a bit of a bug prediction and apply some labels to your PRs) at the moment. You might want to turn off some of the stuff it does.

We are aware that this is not what some people want and are working on a new version, in the meantime - feel free to use it and tell us whatever you want to have changed. Your opinion truly matters and it's likely that we will implement e.g. a feature or improve something just because you need it. Just ping me :)

**Comment by The-Compiler** [comment]
Awesome! I was already wondering if I can turn some of those features off :wink:

No ideas so far (and it might be a few weeks until I actually get to this), except maybe something similar https://github.com/facebook/mention-bot does if it doesn't do that already :wink:

**Comment by sils1297** [comment]
Hey,

we tried mention-bot for coala and were a bit disappointed, wasn't particularly good at it. Actually we did have th same idea for gitmate and then found it. We'll be definitely considering it - though we're working on a complete rewrite right now switching some technologies and we'll try to be much more focused on the code review part and then add other features as optional thingies for the user as the review part is what they actually want.

**Comment by The-Compiler** [comment]
I thought about some other things I would find useful for such a bot:

- After a PR was merged, mentioning issues which are mentioned somewhere (PR thread, commit messages) but still open (as some people only mention issue numbers but without "closes #xyz" or similar).
- When the bot is running on my own server, have an easy way to configure something like this after a PR is merged:
  - Run a script
  - If there are any changes, commit and push to the PR traget branch

Usecase: generated documentation for qutebrowser commands/settings in the repo, generated [author list](https://github.com/The-Compiler/qutebrowser#authors) based on git commits
- A way to easily add something to the changelog with a comment, as this is often a source of PR conflicts, and then to merge if the checkers are green. I.e. something like:

> @qutebot add to fixes in changelog: Fix crash when running on a toaster
> @qutebot merge if checks pass

At this point I'm wondering how generic those features are, and if I should write my own bot :laughing:

**Comment by sils1297** [comment]
Hey,

I'll look into that. Gitmate has and will always have a modular architecture internally. Makes it easy to add stuff like you described. for the new version, the big difference will be that we wanna make one feature after each other and disable the more advanced stuff by default in the next version.

If you want I can give you access to the current source code and work with you if you need any features in the currently deployed version. It'll be way easier for you to develop stuff because the basic stuff is already dealt with.

The catch: you'll have to give me the rights on the code, ATM it's proprietary but we plan to open source at least the core of the new version definitely under AGPL.

GitMate will always stay free for open source, if at some point the business model is failing, we will open source everything so the project survives.

If you use gitmate on large scale I'm going to need a donation as I'm posting for servers right now personally, which is not problem on a normal OS project.

**Comment by sils1297** [comment]
For the script run on merge we use rultor.com at coala, which sucks a bit but at least I don't have to maintain it

**Comment by The-Compiler** [comment]
Coala seems to be [pretty much dead](https://github.com/coala/coala/graphs/contributors) nowadays (last release is from May 2017).

A more modern/maintained alternative would probably be [pre-commit](https://pre-commit.com/) and [pre-commit CI](https://pre-commit.ci/), though admittedly I don't really like how it duplicates a lot of things we already have nice solutions for (e.g. `tox` and `requirements.txt`). Might be something to explore at some point, but I'm closing this for now.
