### ISSUE TITLE
Use sqlite internally for completion

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1765]
I noticed Qt has a [QSqlTableModel](http://doc.qt.io/qt-5/qsqltablemodel.html) as well as [QSqlQueryModel](http://doc.qt.io/qt-5/qsqlquerymodel.html).

Since the current way how completions are done is rather complex, and we're often struggling with performance issues - here is a crazy idea: What about writing completions into a sqlite database on start (and updating that database whenever needed), and using a `QSqlQueryModel` to display the completion, probably with no `QSortFilterProxyModel` at all?

That might be a lot faster. It might also make some things easier - and I guess we can still have completion functions generating them dynamically for easier and shorter completions.

It might also be slower and more complex. I really have no idea...

cc @rcorre @lahwaacz

**Comment by lamarpavel** [comment]
Really unsure about this. Relational databases are not necessarily ideal for real-time-feedback but rather optimized for concurrent, load-heavy access. At least that is my limited experience, I am really not an expert on the topic. Sending a new query for every key-stroke to update the completion is entirely sequential and delay-sensitive. Has anyone here had experience with Qts implementation and can give some insight?

**Comment by rcorre** [comment]
My first instinct is that this is overkill, but I too have little experience with DBs. I think the most important step here is to identify whether we have a performance problem. If so, are we slow because it takes a long time to generate completion candidates or a long time to filter/sort them?

I'd separate completion into two categories:

1. `UrlCompletionModel`, which deals with a lot of data and may have performance
   problems for both generating and filtering the list.

2. Every other type of completion, which can probably be generated on the fly.

If performance were no concern, eliminating the caching in `completion.models.instances` remove a lot of complexity and signal/slot wiring that is used to keep the cached instances up to date.

I haven't heard about performance issues outside of the proposed filtering behavior in #1654 (which would be very nice if we can do it performantly).

Maybe we ought to focus on getting some performance testing in place and measure before we cut?

> the current way how completions are done is rather complex

Its rare you hear someone suggest a database as a means to make something _less_
complex :wink:

**Comment by The-Compiler** [comment]
I think we do have a performance problem, or at least our hands are pretty much bound when it comes to functionality improvements for the completion matching (like in #1654).

It would also be nice to be able to complete the full history, or at least more than a few 100 items, without slowing down to a crawl. I think Qt's SQL models can do that by dynamically fetching more data from the database if needed.

**Comment by blyxxyz** [comment]
>Relational databases are not necessarily ideal for real-time-feedback but rather optimized for concurrent, load-heavy access.

sqlite claims it's different:

https://www.sqlite.org/whentouse.html
>SQLite is not directly comparable to client/server SQL database engines such as MySQL, Oracle, PostgreSQL, or SQL Server since SQLite is trying to solve a different problem.

>For programs that have a lot of data that must be sifted and sorted in diverse ways, it is often easier and quicker to load the data into an in-memory SQLite database and use queries with joins and ORDER BY clauses to extract the data in the form and order needed rather than to try to code the same operations manually. Using an SQL database internally in this way also gives the program greater flexibility since new columns and indices can be added without having to recode every query.

It's used in Firefox, so using it in qutebrowser is not a crazy idea.

**Comment by lahwaacz** [comment]
> Its rare you hear someone suggest a database as a means to make something less
complex

The idea is to offload the complexities to the DB backend and have a client doing advanced stuff via simple calls to a standardized interface :wink:

When it comes to optimizing Python code, in my experience most difference can be done by the following:

1. Avoiding unnecessary work.
2. Rewriting the performance critical part into C++, i.e. avoiding Python code (I have some experience with [this](https://bbs.archlinux.org/viewtopic.php?pid=1643715#p1643715)).

In practice, we could do something about [unnecessary resize events](https://github.com/The-Compiler/qutebrowser/pull/1584#issuecomment-229711986) and maybe lower the per-keypress work by adding some [delay](https://github.com/The-Compiler/qutebrowser/issues/1100) or something. Also caching even [more instances](https://github.com/The-Compiler/qutebrowser/pull/1654#discussion_r71065394) might help a lot.

As for 2, using `QSqlTableModel` actually goes in that direction, assuming that it can be made to work reasonably without calling back into Python code like custom `QSortFilterProxyModel`. The thing is that the `filterAcceptsRow` method is called for every row in the completion, so even if it's a method that always says `False`, it's going to be thousands of calls for a big history, so that's not going to work in "real" time if it's Python code, but might if it's C++.

So all in all I think this might work, but if it will, the question is how much fancy stuff could be done on top without hindering performance again. From this point of view it might actually be the same as the current solution.

**Comment by The-Compiler** [comment]
@lahwaacz Your link to the Arch BBS gives me a "Bad request". I thought about adding some C++ to the mix, but that'd make packaging/deployment quite a bit harder...

**Comment by lahwaacz** [comment]
(I'm sorry, the thread probably requires the reader to be logged in... I could repost it here but it's not that much relevant.)

Instead of adding custom C++ code, using as much Qt code as possible gives basically the same result. It's only important to realize when PyQt runs C++ and when it calls back to Python, which could be in the middle of processing something big, which would give the biggest slowdown possible.

**Comment by rcorre** [comment]
Things get messy if we want to keep using a tree view. I'm thinking I may need one table/query for each category with a proxy that redirects nested indexes to the appropriate table/row.

For example, given an index with parent row `p` and child row `c`, I'd map `p` to one of "quickmarks", "bookmarks", or "history" and look up row `c` in that table.

Well, I'm diving in. See you on the other side :grin:

**Comment by rcorre** [comment]
Implemented in https://github.com/qutebrowser/qutebrowser/pull/2295
