### ISSUE TITLE
IPC: Set urgency flag

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#185]
There should be an urgent-flag set when IPC opens a new tab in a window which isn't visible currently.

**Comment by rien333** [comment]
I suppose so, but the current behavior sets the urgency flag incorrectly: say I have a window open on desktop 1, and open up a new window via an IPC socket on desktop 2, then the urgency flag for the window on desktop 1 is set.

**Comment by toofar** [comment]
As far as I can tell raising windows (and alerting) is only done from https://github.com/qutebrowser/qutebrowser/blob/3e816f5/qutebrowser/mainwindow/mainwindow.py#L46 which, when called from IPC, is only called for args that begin with `:`, so commands (https://github.com/qutebrowser/qutebrowser/blob/3e816f5/qutebrowser/app.py#L284). So I am assuming by "open up a new window via an IPC socket" you mean you are passing `:open -w foo` to it.

The logic about whether to raise in `get_window()` is a little strange. Since `force_tab` is always passed when called via IPC then it will raise a window if `new_instance_open_target` is set to anything other than `window`. If it is set to `window` it will use `tab-silent` instead. Since `force_tab` is passed anyway I don't see why it would even be looking at that config setting, it seems like hybrid coupling. As to what window is raised that is decided by `new_instance_open_target_window`.

So anyway, there seems to be to ways to not get the current window to be raised.
* if you are passing a command you need to have `new_instance_open_target` set to `window`
* if you just want to open a URL you can do `qutebrowser --target window "foo bar"` where `--target` takes as an argument any of the values that `new_instance_open_target` can be and the positional argument will be handled by the fuzzy URL matching like `:open` does.

**Comment by rien333** [comment]
@toofar  thanks for the tips! I had been struggling with quickly opening qutebrowser windows for quite some time, but I got a good config now.
