### ISSUE TITLE
Wishlist: some way to display output/status of spawned commands

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2148]
maybe a tab or something, just a simple way to view a command like it's been executed in a terminal.

**Comment by The-Compiler** [comment]
In case there's an error, `:messages` already shows you the output. Do you think the output should still be visible (it's in `:open qute:log` FWIW) when a command succeeded?

I guess the error message could show `:messages` though.

**Comment by sfgasdfsafggfgg** [comment]
@The-Compiler I think I opened this issue because of an attempt to `:spawn mpv {url}` and it failed without showing an error message (i checked `pgrep mpv` and nothing came up).

I tested it in the terminal instead, and it exited with exit code 2 - is Qutebrowser only configured to show an error message when a command exits with exit code 1? Or is this just a problem on my end?

As for your question, I was thinking of having it show output in a tab with a flag, such as `:spawn --output-to-tab`. The main use that came up for me is if I quickly want to debug a command that exits and fails (in this case, mpv), but I thought it would be a simple addition that wouldn't be difficult to implement and could be useful for other cases, such as for example a quick and dirty script that downloads a zip file and outputs a list of it's contents, or something.

I think it's better not to have it do this by default though.

**Comment by The-Compiler** [comment]
I see - a flag like that sounds like a nice idea, and should be relatively easy.

FWIW it'll show an error with any non-0 exit status, see e.g. `:spawn bash -c 'exit 2'`

**Comment by gebulmer** [comment]
I've started work on this. It appears to work, however tests need to be modified with it. 

PR: #3374

**Comment by The-Compiler** [comment]
That PR was merged now! 🎉
