### ISSUE TITLE
Qutebrowser doesn't seem to work for Terminus (TTF) font

### ISSUE THREAD

**Issue by JonathanReeve** [qutebrowser/qutebrowser#2256]
I have a font called "Terminus (TTF)". When I run something like `:set fonts _monospace Terminus (TTF)`, or `:set fonts _monospace "Terminus (TTF)"`, `:set fonts _monospace "Terminus \(TTF\)"`, or similar command, Qutebrowser complains "Invalid value ... must be valid font." I know I have the right name, since `fc-list` shows `/usr/share/fonts/TTF/TerminusTTF.ttf: Terminus (TTF):style=Medium`. 
 
Am I just not escaping it correctly? Or can Qutebrowser not handle font names that contain parentheses?

**Comment by ml-** [comment]
Can reproduce.
Installed this: https://aur.archlinux.org/packages/terminus-font-ttf/
Couldn't set this font "Terminus (TTF)" in qutebrowser.

I'm not sure if @The-Compiler can actually do something about it since the font-matching is in another castle.

### Workaround - Drop-in fontconfig config file (ArchLinux dirs, adjust for your distro)
**/etc/fonts/conf.d/99-terminus.conf**
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<match target="pattern">
		<test qual="any" name="family">
			<string>Terminus</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>Terminus (TTF)</string>
		</edit>
	</match>
</fontconfig>
```

`(sudo) fc-cache [--force]`

Now you can set the font "Terminus" in qutebrowser. Don't forget to restart the browser after you adjusted the fontconfig file.

**Comment by The-Compiler** [comment]
The font validation is actually [done by qutebrowser](https://github.com/The-Compiler/qutebrowser/blob/v0.9.1/qutebrowser/config/configtypes.py#L732-L746) - I didn't think about parentheses in font names, I guess I should just change this to `.*`.

FWIW I use the Terminus pcf font with `xos4 Terminus`.
