### ISSUE TITLE
New private browsing

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2327]
I have some plans for a new way how to handle private browsing, which will also make it much easier to add support for that with QtWebEngine. In a nutshell:

- private browsing is now per-window
- `general -> private-browsing` will not affect existing windows anymore, only new windows (and is mostly kept for people who want to have `private-browsing` always on). We need some way to make this clear though.
- The statusbar changes color (to gray or so) in private browsing mode (like dwb)
- `:open` gains a new `--private` switch which opens a new window which is in private browsing mode.
- qutebrowser does something similar to `--temp-basedir` for all files when private browsing is turned on. This is both as an additional security measure, and to enable private browsing with QtWebKit-NG where it's not implemented yet.

**Comment by EliteTK** [comment]
Yes.

Very yes!

So if I understand correctly, you can't have mixed private/non-private tabs on one window, only a separate window with all tabs private or non-private?

Only thing missing here would be a default bind to open a private browsing window (potentially even using a different new-tab page / homepage). But that's easily done.

**Comment by The-Compiler** [comment]
> So if I understand correctly, you can't have mixed private/non-private tabs on one window, only a separate window with all tabs private or non-private?

Hmm, I think that'd be possible to do as well, with a tab indicator instead. I need to think some more about it. Do you think that'd be better?

**Comment by karlch** [comment]
Just throwing in ideas :smile:

I think it would be perfect if the `--private` switch were simply another optional argument for `:open` which can be added to `-i`, `-b`, `-t` and `-w`. So `:open --private` would make the current tab private, `:open -t --private` would open a new private tab, `:open -w --private` a new private window and so forth.

For me, toggling the `private-browsing` setting should affect all URLs opened after the setting. Meaning after setting `private-browsing` to `true` and calling `:open URL` this URL should be opened in private mode. 

Concerning indicators, I really like the idea of changing the statusbar color. Indicating private tabs with a `tabs.indicator.private` setting sounds great as well.

Not sure how much complexity this would add though.

**Comment by The-Compiler** [comment]
Changing the status of an existing tab (i.e. the `private-browsing` setting and `:open --private` without `-t`/`-b`/`-w`) won't work.

**Comment by karlch** [comment]
Okay, I guess `:open --private` would then have to default to either `-t` or `-w`. Personally I would prefer `-t` but I don't think it makes much of a difference.

Could changing the setting still apply to all newly opened tabs/windows instead?

**Comment by The-Compiler** [comment]
> Could changing the setting still apply to all newly opened tabs/windows instead?

Yes. The only remaining question is whether private/non-private will be something which is per-tab or per-window. I think having it per-tab should be possible, but I'll have to look at the related code in detail first.

**Comment by karlch** [comment]
And as soon as it is a per-tab setting it automatically also works for new windows?

**Comment by The-Compiler** [comment]
Yes, because a new window is just a new tab in another window :wink:

**Comment by karlch** [comment]
That's what I thought, thanks for the clarification and sorry for bothering :smiley:

I am obviously all for the per-tab setting then.

**Comment by lahwaacz** [comment]
I think that with private and non-private tabs mixed in one window things like saving the session will get very awkward - private tabs will have to be skipped to remain really private and so on. People will risk losing some work when they close the window, just because the private tab was not active at the moment.

Also, private tabs can't be re-opened so when you close a private tab `:undo` will not get past it. (This could be solved by skipping with a completion, but that would require some non-trivial work.)

**Comment by EliteTK** [comment]
Well, for all I know no other browser has per-tab private mode.

I don't think it's that good of an idea either personally since it would be easy to accidentally open something non-privately when you're on a private tab.

I think having it as a separate window would actually be both the simplest and safest solution. At least if there was an option to have mixed private tabs then it would be really useful to have a way to forcibly prevent it.

**Comment by NoctuaNivalis** [comment]
Private tabs would be really cool, but require a lot of extra work.

As lahwaacz said, you'd have to get a confirmation on saving a session, and chose between saving them (and opening them privately later) or not saving them.

You'll have to make sure a new tab is always opened in the mode of the current tab, unless specified otherwise (opening a private tab from a public tab with --private, and opening a public tab from a private tab with --public, and perhaps a `:open --switch-privacy`).

If you click a link outside the browser, should it open in a private or none-private tab? The same mode as the last focussed? (Same goes for windows, here, btw.)

**Comment by CIAvash** [comment]
Just for reference, Firefox has a [Private Tab](https://addons.mozilla.org/en-US/firefox/addon/private-tab/) add-on.

**Comment by SirCmpwn** [comment]
+1 for `open -tp`

**Comment by The-Compiler** [comment]
I did some initial work on this [in the new-private-browsing branch](https://github.com/qutebrowser/qutebrowser/compare/new-private-browsing) - then I discovered the settings I'd need to emulate private browsing with QtWebKit-NG are only available globally...

Because of that, I'll wait until private browsing is implemented there (which should happen soon) before continuing work on this.

**Comment by The-Compiler** [comment]
Private browsing is now implemented in QtWebKit-NG: https://github.com/annulen/webkit/commit/e35c9897aed7a33eee74ef61b1641888c11374ef

**Comment by The-Compiler** [comment]
PR at #2615 - review/feedback welcome!

**Comment by BurhanDanger** [comment]
How to open only private/incognito window from command line ?

**Comment by toofar** [comment]
@BurhanDanger `qutebrowser --temp-basedir -s content.private_browsing true` appears to work.

**Comment by The-Compiler** [comment]
@BurhanDanger Also see #4643 - also, please don't comment on random issues which aren't really related with questions - see [getting help](https://github.com/qutebrowser/qutebrowser#getting-help) for better ways to get help.

**Comment by BurhanDanger** [comment]
@The-Compiler , sorry for spamming your mail. To me my question seemed similar to the title of this issue, hence the question. I searched manual and wiki for that but couldn't get how. For something so common it's surprisingly not in wiki/manual and you have ask in IRC.  toofar's method works great and can be used as alias. I'll remember to ask on IRC next time
