### ISSUE TITLE
QTWebEngine: YouTube videos at incorrect aspect ratio

### ISSUE THREAD

**Issue by gnubeest** [qutebrowser/qutebrowser#2425]
Arch Linux, currently at qutebrowser v0.10.0-79-g7c9d004bb but I couldn't tell you at which commit this started happening since I use in-browser video so rarely.

At some point, all YouTube videos seem to have started displaying at a slightly narrower aspect ratio. This affects both videos viewed at youtube.com and embedded YouTube video at other sites. The actual viewport is at the correct aspect ratio, but the video itself is narrowed with a black matte along the right side of the video frame. HTML5 video from other sites doesn't seem to be affected, and YouTube on Chromium displays correctly.

**Comment by The-Compiler** [comment]
On what backend? (see `:open qute:version`)

**Comment by The-Compiler** [comment]
Looks fine for me.

Does it only happen when playing fullscreen? Or non-fullscreen? Both? Can you post an URL to a video with which it happens, and a screenshot? Can you also try if something in qutebrowser introduced this, by e.g. doing `git checkout v0.9.1`?

**Comment by gnubeest** [comment]
I knew this was gonna be unreproducable. :/

1) Happens both full-screen and inline.
2) https://ptpb.pw/H5OF from https://www.youtube.com/watch?v=xSuq-j3xamE -- this is how every single YouTube video is rendered for me in Qute.
3) Totally happening in 0.9.1 (certainly didn't before) with a clean config.
4) Can reproduce in QupZilla, which would seem to narrow it down to backend weirdness (which is at 5.8.0, fully updated Arch, not running [testing]) and I'm obviously a unique snowflake. This is also quite recent and I'm almost certain started happening long after the last Arch update for qtwebengine.

**Comment by The-Compiler** [comment]
Weird! I'd guess something changed on YouTube's side (or in your graphics driver possibly?) which triggers this for you.

Unfortunately I don't see anything qutebrowser can do about this, it doesn't handle drawing the videos at all. You could report the bug to [Qt's bugtracker](https://bugreports.qt.io/), but if nobody there can reproduce it, you're pretty much out of luck...

I guess your best bet would be to wait for Qt 5.9 (~June) which will be based on Chromium 55 or 56 instead of 53 and see how things look there. In the meantime, you could use `mpv` like outlined in the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/FAQ.asciidoc).

Sorry!

**Comment by The-Compiler** [comment]
Not that I'm aware of - but this issue is 6.5 years old, so if you see something similar today (and with Qt 6), it might be a different issue.

**Comment by shlyakpavel** [comment]
@The-Compiler Thank you for your quick response! I reproduced my issue in Chrome and it has something to do with the video file being damaged...
