### ISSUE TITLE
auto-fill authentication requests

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#2489]
When authentication is requested, we could call a configurable shell command which takes a url as input and outputs a username/password. If it is not configured or provides no output, then the usual authentication prompt would show up.

Related: #1792

**Comment by The-Compiler** [comment]
I think it'd make more sense to do this as a plugin, in a way it can also use python libraries (like to access KeePassX databases) and fill login forms in the same plugin - so I'm closing this in favor of #30.

(I plan to write such a plugin for KeePassX once there's a plugin API, and probably for pass/LastPass/... too when it's as trivial as I imagine it to be)

**Comment by rcorre** [comment]
I guess that could work if plugins are on the way. For something like `pass` though, it certainly wouldn't be necessary as calling it from a shell script is dead simple.

**Comment by The-Compiler** [comment]
I don't have an ETA for plugins yet - but once the new config stuff is out of the way, it's the only big-ish task remaining, i.e. the next one on my todo-list once I have some longer block of time. It's also something which can be done more incrementally.

Either way, I'd like to avoid adding more and more stuff to qutebrowser's core, because it won't make maintaining it easier :wink: In the long run, I want to get more and more functionality out in "built-in plugins" using the plugin API (probably under `qutebrowser.modules` or something), and then maybe even "degrade" stuff which has a smaller userbase to plugins which are not installed by default.

**Comment by rcorre** [comment]
> I'd like to avoid adding more and more stuff to qutebrowser's core, because it won't make maintaining it easier

Say no more, I'm sold :grin:
