### ISSUE TITLE
pdfjs can't display PDFs served over https

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2525]
At least with QtWebKit-NG, when e.g. loading https://cmpl.cc/downloads/cms-slides.pdf I get:

![pdfjs](https://cloud.githubusercontent.com/assets/625793/25043266/f60435c0-211e-11e7-9c86-87a62d6300c2.png)

And those JS console messages:

```
[https://cmpl.cc/downloads/cms-slides.pdf:32] [blocked] The page at https://cmpl.cc/downloads/cms-slides.pdf was not allowed to run insecure content from qute://pdfjs/web/viewer.css.
[:0] [blocked] The page at https://cmpl.cc/downloads/cms-slides.pdf was not allowed to run insecure content from qute://pdfjs/web/l10n.js.
[:0] [blocked] The page at https://cmpl.cc/downloads/cms-slides.pdf was not allowed to run insecure content from qute://pdfjs/build/pdf.js.
[:0] [blocked] The page at https://cmpl.cc/downloads/cms-slides.pdf was not allowed to run insecure content from qute://pdfjs/web/viewer.js.'
[https://cmpl.cc/downloads/cms-slides.pdf:358] ReferenceError: Can't find variable: PDFJS
```

This is because `qute://` isn't treated as secure scheme by QtWebKit. I'm guessing #1635 would help, but I still haven't really looked at JS bridge stuff with QtWebEngine...

cc @Kingdread

**Comment by Kingdread** [comment]
Note sure if #1635 would help, as that would only prevent the PDF from being loaded twice. pdf.js would still need to access its own resources, which are all served via `qute://pdfjs/` URLs.

I've played around a bit with [`QWebSecurityOrigin`](http://doc.qt.io/archives/qt-5.5/qwebsecurityorigin.html), but it seems like the whitelist has no effect on SSL vs. non-SSL resources. [Other people](http://stackoverflow.com/questions/34864833/custom-scheme-protocol-access-from-ssl) apparently solved the issue by using a WebKit version which is a bit more lax with the SSL-restriction, but that's of course a non-solution...

Also, it seems like [you can't turn this behaviour off](http://stackoverflow.com/a/32618889), so unless WebKit adds such a flag, the workarounds I can think of are

* Always force `http://` for pdf.js pages, though that would be insecure
* Use a "dummy-host" to serve the files, e.g. `https://pdfjs.qutebrowser`, instead of the `qute://` scheme
* With #1635: Download the file via HTTPS, but switch to HTTP before displaying

**Comment by Kingdread** [comment]
I've found sort of a workaround. The page url is set as non-SSL so it can load the pdfjs assets, but the actual PDF is still requested via SSL. Somehow Javascript cannot access SSL URLs, even if they are on the same domain, so we need to add a whitelist entry.

```diff
diff --git a/qutebrowser/browser/webkit/webpage.py b/qutebrowser/browser/webkit/webpage.py
index 7fc891c4c..1a1342462 100644
--- a/qutebrowser/browser/webkit/webpage.py
+++ b/qutebrowser/browser/webkit/webpage.py
@@ -197,13 +197,17 @@ class BrowserPage(QWebPage):
 
     def _show_pdfjs(self, reply):
         """Show the reply with pdfjs."""
+        from PyQt5.QtWebKit import QWebSecurityOrigin
         try:
             page = pdfjs.generate_pdfjs_page(reply.url())
         except pdfjs.PDFJSNotFound:
             page = jinja.render('no_pdfjs.html',
                                 url=reply.url().toDisplayString())
+        new_url = QUrl(reply.url())
+        new_url.setScheme('http')
+        self.mainFrame().securityOrigin().addAccessWhitelistEntry(reply.url().scheme(), reply.url().host(), QWebSecurityOrigin.DisallowSubdomains)
         self.mainFrame().setContent(page.encode('utf-8'), 'text/html',
-                                    reply.url())
+                                    new_url)
         reply.deleteLater()
 
     def shutdown(self):
```

**Comment by The-Compiler** [comment]
Fixed with the PDF.js rewrite which just landed in master!
