### ISSUE TITLE
Unable to load page Error while opening <url> Request blocked by host blocker.

### ISSUE THREAD

**Issue by idle-zealot** [qutebrowser/qutebrowser#2542]
When trying to access http://www.easycounter.com/report/n-gate.com, the error message

Unable to load page
Error while opening http://www.easycounter.com/report/n-gate.com: 
Request blocked by host blocker.

Is shown rather than the webpage in question. I have yet to find another site with this issue, and other browsers access it fine.

$ qutebrowser --version
qutebrowser v0.10.1
Git commit: 
Backend: QtWebKit

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.10.8-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

**Comment by The-Compiler** [comment]
This is because that host is blocked by the adblock lists, probably because it's usually used for tracking purposes. If you use Chrome with [uMatrix](https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf) (or probably uBlock, though I didn't check), you'll see the same happen.

You can add it to the `content -> host-blocking-whitelist` setting to allow it globally, or (temporarily) disable the host blocker entirely via the `content -> host-blocking-enabled` setting.

Also see #273, which is about adding some kind of "load anyways" button in this case.
