### ISSUE TITLE
New campaign

### ISSUE THREAD

**Issue by cosminadrianpopescu** [qutebrowser/qutebrowser#2568]
I am opening an issue here, maybe it's not the proper place. I am trying to contribute to the new campaign and there is no paypal options. Also, although I have an account on kickstarter, they are still asking for my credit card details. 

Is there a possibility to add paypal?

**Comment by The-Compiler** [comment]
Thank you for the support! Unfortunately, Kickstarter only supports credit cards (via Stripe), and there's nothing I can do about it.

You could simply use my PayPal address (me@the-compiler.org) - however, that won't count towards the Kickstarter tutorial, and since that needs to be reached for the campaign to succeed, I'd prefer donations via Kickstarter until it's reached. Still, it's an option if nothing else works for you, and of course you can also get stickers/shirts that way.

FWIW, at least here I can get prepaid credit cards almost everywhere - maybe that'd be an option for you?

**Comment by NoctuaNivalis** [comment]
Same problem here. Campain's almost succeeded though, so I'll just wait a few more days and use paypal.

**Comment by NoctuaNivalis** [comment]
@cosminadrianpopescu the campaign has succeeded.
