### ISSUE TITLE
Improve documentation - installing on CentOS7

### ISSUE THREAD

**Issue by jmburgos** [qutebrowser/qutebrowser#2618]
Could you add to the documentation instructions on how to install qutebrowser on CentOS7?
Thanks!!

**Comment by The-Compiler** [comment]
Sorry, but it looks like there's no reasonable way to do this on CentOS - it's just too outdated.

qutebrowser requires Python 3.4 (released >3 years ago) and Qt 5.2 (3.5 years ago), CentOS 7 doesn't seem to have Python 3 (9.5 years) or Qt 5 (4.5 years) at all.

It looks like there are ways to get [Python 3](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-centos-7) and [PyQt5](https://github.com/pyqt/python-qt5/wiki/Compiling-for-CentOS-7), but it requires getting things from ~5 different unofficial sources and compiling stuff yourself (and good luck keeping up with updates then...) - that's definitely "you're on your own" territory, and not something I can easily add to qutebrowser's install instructions.

#1912 (binary executables for Linux) might help you - however I'm going to build those on an Ubuntu Trusty (~3 years old) most likely. Since CentOS 7 seems even older, chances are they won't run either.

**Comment by jmburgos** [comment]
Ok, thanks for the explanation.  I will have to move to a more modern distro. :)

**Comment by joe-batt** [comment]
Hi,

I know this Issue is closed, but – at least now – you can install qutebrowser without too much hassle on Centos 7. 
Here is how I did it:

Centos 7 comes with Qt 5.9 these days and I already had it installed for Konsole, so I'm not sure which packages you really need. The packages I have are:
```
qt5-qtbase.x86_64
qt5-qtbase-common.noarch
qt5-qtbase-gui.x86_64
qt5-qtdeclarative.x86_64
qt5-qtsvg.x86_64
qt5-qtx11extras.x86_64
qt5-qtxmlpatterns.x86_64
```

You can probably get away with less, but I was too lazy to check it out.

Next we need Python 3.6. The base repo contains Python 3.4, but that doesn't cut it, but the EPEL gives you 3.6, so install the EPEL-Repo via yum:
`sudo yum install epel-release`

and now Python 3.6:
`sudo yum install python36 python36-devel`

Make sure `/usr/bin/env python3` points to 3.6, and not 3.4 if it's already installed.

Next up is PyQt5. I haven't checked if there are any packages in base/epel for that. If there are, don't use them. From my experience, the prepackaged stuff will give you a bad time, use pip to install it. Luckily the geniuses at Centos (or probably RedHat) dont't provide a package for pip3.6. Since pip will check for updates for itself when installing stuff and you need to keep PyQt5 up to date anyway, I installed it manually:
`wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo python3.6`
 Now finally PyQt, I'm not sure if you need `gcc`, you need it later anyway, so just install it:
```
sudo yum install gcc
sudo pip3.6 install PyQt5
```

Finally it's time to get qutebrower. I decided to use the 1.5.x branch:
```
git clone https://github.com/qutebrowser/qutebrowser.git
cd qutebrowser
git checkout v1.5.x
sudo ./setup.py install
```

That's it, now you can run it via `qutebrowser`!

__Important__
Keep in mind that you should keep the manually installed stuff up to date. I use to do it in a cronjob but you can do it manually as well. The required steps are pretty easy (run as root/via sudo):
```
pip3.6 install --upgrade pip
pip3.6 install --upgrade PyQt5
cd /wherever/the/hell/you/put/qutebrowser
git pull
./setup.py install
```

Cheers and thanks for a great browser

**Comment by ipstone** [comment]
Thanks @joe-batt :+1: I got it working with qutebrowser 1.10.0 following your instruction. Though the latest release version will cause a crash on start.
