### ISSUE TITLE
Mastadon doesn't work with Qutebrowser

### ISSUE THREAD

**Issue by dekksh** [qutebrowser/qutebrowser#2684]
Downloaded the latest deb last night and installed on a 32bit Debian install.

All works OK so far bar Mastadon - checked on 2 servers both have same issues that the webkit version displays the front page but any action away from that page [i.e. login or federated random timeline] results in a blankpage.

Running --backend webengine works but the renderer process intermittently crashes - ran :report and sent it from latest crash.

Any other info plz ask

**Comment by The-Compiler** [comment]
Nothing I can do about it not working with legacy QtWebKit, or about renderer crashes I'm afraid.

Unfortunately, since Debian uses Qt 5.7 instead of the (LTS) 5.6, it now has an unsupported and already buggy QtWebEngine for the next few years (the LTS at least would be supported until 2019 upstream). No idea what the rationale for that was...

An alternative you might want to check out is using an unofficial updated QtWebKit, which has   packages for Debian Unstable (by @paretje) [available here](http://repo.paretje.be/unstable/).
