### ISSUE TITLE
TAKE MY MONEY!!!

### ISSUE THREAD

**Issue by PeteW** [qutebrowser/qutebrowser#2724]
I am a very big fan of this project. I want to see it continue and expand in terms of features. I dont have time to contribute via code. I would like to donate $$ to the key contributors as a form of support. Any recommendations on how some of us non-code contributors can help the project?

**Comment by annulen** [comment]
![shutupand](https://user-images.githubusercontent.com/102544/27232491-4773d698-52c7-11e7-8169-35dc9b2baef8.jpg)

**Comment by The-Compiler** [comment]
@annulen: Dang, I wanted to post that! :wink:

What can I say... thanks! 😆 

See [this section in the README](https://github.com/qutebrowser/qutebrowser#donating) for how to donate. 🎉 

I also did a [crowdfunding](https://www.kickstarter.com/projects/the-compiler/qutebrowser-v10-with-per-domain-settings) this and last year for some full-time work on qutebrowser, and will probably do the same next year. You might want to sign up to the [qutebrowser-announce mailinglist](https://lists.schokokeks.org/mailman/listinfo.cgi/qutebrowser-announce) in order to get notified when stuff like that (or new releases) happens.
