### ISSUE TITLE
Pass line number to external editor

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2725]
As @blueyed mentioned in IRC, it'd be nice if it was possible to pass the line number and maybe column to an external editor, if available.

**Comment by lahwaacz** [comment]
Throwing in an idea: we could use the `selectionStart` attribute of [HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) and [HTMLTextAreaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement), though of course it can [fail](https://stackoverflow.com/questions/21177489/selectionstart-selectionend-on-input-type-number-no-longer-allowed-in-chrome). On the Python side, the linear position of the cursor can be easily transformed into (row, column) coordinates. I found a demo of the javascript part [here](https://stackoverflow.com/a/34466831/4180822).

**Comment by 7lb** [comment]
What's the desired behaviour here?

My guess: passing the line number to the external editor would allow the editor itself to place the cursor in the same position that it had in the browser.

Following guess: if my first guess is correct I suppose a new placeholder for the editor command is needed. `{}` is the current placeholder for the temporary file name, but since each editor may receive a line number argument in a different way we may need a `{row}` (and perhaps `{col}`) placeholder for the line number, correct?

As an example one could set `editor.command` as `'["gvim", "+{row}", "-f", "{}"]'` or `'["sublimetext", "{}:{row}:{col}"]'`.

Did I get something wrong?

**Comment by The-Compiler** [comment]
@7lb Sounds good to me! 👍

**Comment by 7lb** [comment]
Cool, I'll see if I'm able to work on this. I found the python handler for the shortcut, but where should I look for the javascript side of things?

Also, if we add the `{line}` (`{row}` makes less sense in this context now that I think about it) and `{col}` placeholders it would make sense to change `{}` to something else, perhaps `{file}`, `{filename}` or `{fn}`, but that would break current configurations.

I have three proposals on this:
1. forget about renaming, leave `{}` as `{}`
2. rename `{}` to something else (say `{x}`) and silently change the existing placeholder in `editor.command` to `{x}`, deprecating the use of `{}`
3. accept both `{}` and `{x}`

What do you think? :)

**Comment by blueyed** [comment]
Accepting both `{}` and `{x}` makes sense to me, preferring `{x}` (e.g. in help/docs).

As for Vim you can use `-c "call cursor({line}, {column})"` there.

**Comment by 7lb** [comment]
Ok, after spelunking the code a bit I think I understand all the basic pieces to try and implement this.

Also, another issue popped up in my brain. What if some editor somewhere uses 1-based caret position, such that the topmostr leftmost position in a buffer is not (0, 0) but (1, 1)?

Is this something we care about or should we ignore the issue and possibly revisit the code if / when the issue arises?

A simple solution could be having both `{line}` and `{line1}` placeholders for 0- and 1-based indexes.

Anyway, if it's not a problem I'd like to take this issue, and hope to have a WIP pull request ready in about 24 hours.
