### ISSUE TITLE
Switch to ruamel.yaml

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2745]
With #2742 we should also be able to switch from the outdated/abandoned [PyYAML](http://pyyaml.org/) to [ruamel.yaml](https://bitbucket.org/ruamel/yaml)

Note it had a [breaking API change](http://yaml.readthedocs.io/en/latest/api.html) though, and we'll need to implement support for both APIs. This shouldn't be much code though, and is totally worth it seeing the [benefits](http://yaml.readthedocs.io/en/latest/pyyaml.html) we get over PyYAML.

**Comment by The-Compiler** [comment]
@jgkamat made me aware that Gentoo doesn't have ruamel.yaml outside of https://gpo.zugaina.org/dev-python/ruamel-yaml

Then again, Gentoo's package is probably not going to be upgraded to v1.0 anytime soon, and it's installable via pip easily, so I'm not sure if I should care.

**Comment by jgkamat** [comment]
I'm going to have to agree with you on this, esp because of how unresponsive the gentoo maintainers (at least for qutebrowser) are right now. If it's not packaged for gentoo, people are going to be (probably) installing it via pip anyway, so they'll get that dependency. 

I would also expect gentoo to (eventually) get ruamel packaged, since it seems to be the replacement to PyYAML.

Once 1.0 is released, I'd probably be willing to put in some effort to try to get that shipped (but I don't know how feasable that is....)

**Comment by The-Compiler** [comment]
This unfortunately went to [the ~~trash~~ experiments repo](https://github.com/qutebrowser/experiments/compare/ruamel-yaml) because of [big performance issues](https://bitbucket.org/ruamel/yaml/issues/159/bad-performance-compared-to-pyyaml) after switching 😟

**Comment by The-Compiler** [comment]
Looks like PyYAML recently moved under the YAML organization on GitHub and has seen some activity again! https://github.com/yaml/pyyaml
