### ISSUE TITLE
Flatpak for qutebrowser

### ISSUE THREAD

**Issue by sanjayankur31** [qutebrowser/qutebrowser#2751]
Related to #1912 

I've been working on building a flatpak this week. It builds, and installs, but it doesn't run properly. Seems to be something related to the kde runtime. One can follow the discussion here: https://lists.freedesktop.org/archives/flatpak/2017-June/000710.html

Current manifest is here: https://github.com/sanjayankur31/qutebrowser/blob/flatpak/qutebrowser.json

Once it builds, we can look at automating nightly builds, and of course a repo will be needed.

**Comment by b-rodrigues** [comment]
This would be great! I've got a pinebook (arm64) and can't get qutebrowser to compile from source. Maybe it could work with a flatpak?

**Comment by The-Compiler** [comment]
@sanjayankur31 On the mailinglist thread (I'm subscribed now) I saw `QTWEBENGINE_DISABLE_SANDBOX=1` mentioned - doing so is a security issue (it disables Chromium's [sandboxing](https://chromium.googlesource.com/chromium/src/+/master/docs/design/sandbox_faq.md)). Doing that might be okay for Subsurface (if it uses QtWebEngine for trusted input only), but definitely isn't for a browser.

@b-rodrigues I think Flatpaks are architecture specific, and there probably won't be any for ARM64. There's nothing really to be compiled in qutebrowser itself (it's Python, after all), so what exactly are you having trouble with?

**Comment by sanjayankur31** [comment]
@The-Compiler - yeh, I thought so. We're going to have to wait on the KDE folks to fix the runtime and SDK then? I'll try to get in touch with them.

**Comment by b-rodrigues** [comment]
@The-Compiler I'm having trouble with PyQt5. I've install the latest version from source but then when I try to install qutebrowser using tox I get the following error:

```
Could not find a version that satisfies the requirement PyQt5==5.8.2 (from -r /home/pine64/Documents/qutebrowser/misc/requirements/requirements-pyqt.txt (line 3)) (from versions: )     
No matching distribution found for PyQt5==5.8.2 (from -r /home/pine64/Documents/qutebrowser/misc/requirements/requirements-pyqt.txt (line 3))   
```

Maybe the problem is because I installed PyQt5 from source, and the module is called PyQt5_gpl and not PyQt5. Any way I can specify the path to PyQt5?

**Comment by The-Compiler** [comment]
@sanjayankur31 I'm not sure what exactly is the problem there, but it seems to me it's more like something along "QtWebEngine is just non-trivial to make work in such a setup" rather than "the KDE SDK is broken", no?

@b-rodrigues Are you doing `tox -e mkvenv-pypi`? That tries to install PyQt5 as a binary from PyPI, which fails because it's not available for your architecture. Try `tox -e mkvenv` instead, which tries to symlink a globally installed PyQt.

**Comment by b-rodrigues** [comment]
@The-Compiler thanks this worked, but when I launch qutebrowser, it seems that I have an outdated version of QT5 (PyQt5 is ok though). I'll need to build Qt5 from source also, then. Thanks for your help!

**Comment by The-Compiler** [comment]
Closing this for now, as we have #1912 already. Let me know when there's anything new, though!
