### ISSUE TITLE
tab-close [count] doesn't work ([count] isn't a recognised argument)

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2769]

**Comment by jgkamat** [comment]
@pkillnine `count` refers to the prefix value, so pressing:
4, <key_for_tab_close> will close the 4th tab. 

I do feel like the documentation for this could be better though.

Alternatively, `:run-with-count 4 :tab-close`

**Comment by pkillnine** [comment]
ah i see, thanks :)

**Comment by The-Compiler** [comment]
Where did you get `:tab-close [count]` from? The documentation says `Syntax: :tab-close [--prev] [--next] [--opposite] [--force]`.

I'm happy to improve the documentation, I just have no idea how :wink:

**Comment by parchd-1** [comment]
Look slightly further down, count is described without indication that it is a prefix:

> 
> ### count
> The tab index to close

Until seeing this issue I had always assumed the command was designed in the way the title assumed it, and that it was broken in the current build the few times I had tried to use it (which isn't many).

**Comment by The-Compiler** [comment]
Hmm... Would it help if the command help page would clarify the concept of a count at the top? Would anyone read it there? 😆 Or should the section title be `count (prefix)` or something?

**Comment by parchd-1** [comment]
I'm sorry to say I don't think people would read it, unless there was a link back to it from every mention of count :wink: . `count (prefix)` would be ok though. It would at least prevent people from thinking it was an argument to stick at the end.

I do wonder *why* it isn't an argument to stick at the end rather than a prefix, though. It isn't really a count, it is an identifier/location. In vim, for example, a numerical prefix would be a real count (5w is move 5 words (count), not move to the 5th word (id/location)). But if there are plenty of people used to the current way of using it, changing it would also be unproductive I guess.

**Comment by The-Compiler** [comment]
Not necessarily - for example, using a count with `:tabnext` in vim gets you to the tab with that count (just like in qutebrowser). If it was an argument, you also wouldn't be able to do `5T` for example (for `:tab-focus`).

**Comment by parchd-1** [comment]
I don't use tabs in vim, so I wasn't aware of that. Interesting that you mentioned :tab-focus though, because that works with count as an argument too.

:tab-focus 5 will focus tab 5, just like 5T (which I'd never used before, I had always used the command)

**Comment by The-Compiler** [comment]
You are right, this is quite inconsistent. I opened #2789 now.

**Comment by JorgeLdeOz** [comment]
I'm still having the same issue with QuteBrowser 3.5 on Manjaro Linux installed with yay (AUR). The recommendation to set the count to cmd-run-with-count works.
