### ISSUE TITLE
small window after exiting fullscreen mode

### ISSUE THREAD

**Issue by helbling** [qutebrowser/qutebrowser#2778]
Reproduction:
1: make browser window fullscreen by doubleclicking on title bar in KDE
2: go to some youtube video
3: klick on fullscreen button to have the video all over the screen
4: press escape

Behaviour: window is not fullscreen anymore. It has the size it had before step 1
Expected: window should look exactly like after step 1

Bug is not just on youtube but on other pages having some fullcreen functionality as well.

qutebrowser v0.10.1
Git commit: v0.10.0-883-g629038632 (2017-07-03 10:29:28 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.1
Qt: 5.9.0
PyQt: 5.8.2

sip: 4.19.2
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017

Style: Oxygen::Style
Platform: Linux-4.11.6-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False

**Comment by lahwaacz** [comment]
FWIW, both qutebrowser and Chromium in i3 behave the same way.

**Comment by helbling** [comment]
My chromium behaves correctly.

Chromium	59.0.3071.109 (Developer Build) (64-bit)
Revision	9f4b44b898b326679817ee5a327256f8fac6ee75
OS	Linux

**Comment by The-Compiler** [comment]
I see the same issue in Chromium 59.0.3071.115 and Chrome 61.0.3141.7 with herbstluftwm.

qutebrowser can probably do this properly though, by saving the fullscreen state when page fullscreen was requested, and restoring it (instead of just calling `showNormal`) when page fullscreen is left.

**Comment by lahwaacz** [comment]
Which part is responsible for handling the exit-video-fullscreen request? It can't be done globally, because when there is a fullscreen video, I'd expect `<Esc>` to exit only the video fullscreen and restore the normal window fullscreen, but `<F11>` (or any window manager shortcut) to exit even the normal window fullscreen.

**Comment by The-Compiler** [comment]
The flow is roughly like this:

- `QWebEnginePage.fullScreenRequested` (signal)
- `WebEngineTab._on_fullscreen_requested`
- `WebEngineTab.fullscreen_requested` (signal)
- `TabbedBrowser.cur_fullscreen_requested` (signal; if it was in the currently open tab)
- `MainWindow._on_fullscreen_requested`
- `self.showFullScreen()` / `self.showNormal()`

Fullscreen via the WM is handled by Qt only I think.

The `:fullscreen` command also calls `.showNormal()` or `.showFullScreen()`, or invokes a `QWebEnginePage.ExitFullScreen` `WebAction` when called with `--leave`.

So `MainWindow._on_fullscreen_requested` could simply store the state when fullscreen was requested and restore that.

**Comment by lahwaacz** [comment]
> Fullscreen via the WM is handled by Qt only I think.

So if qutebrowser is in fullscreen due to the WM request, how does it know what to restore later on?

**Comment by The-Compiler** [comment]
When the page requests fullscreen, the mainwindow can check `self.isFullScreen()`, save that, and when the page leaves fullscreen, not do anything rather than calling `self.showNormal()`.

**Comment by lahwaacz** [comment]
Well, I still don't think that it's that easy. For example, if a tab is closed while a video is fullscreen, the global per-window state would have to be reset, otherwise the other tabs might get the wrong state later...

**Comment by The-Compiler** [comment]
I think when a fullscreened tab is closed, we should do the equivalent of `:fullscreen --leave` (i.e. restore the fullscreen state) anyways - that's not the case currently, though, but would probably be a simple `self.action.exit_fullscreen()` in `WebEngineTab.shutdown`.

**Comment by lahwaacz** [comment]
But we need to also tell the `MainWindow` to reset its `self._restore_fullscreen` variable or whatever, because it won't get the `fullscreen_requested(False)` signal when the tab is closed.

**Comment by The-Compiler** [comment]
When we do `self.action.exit_fullscreen()` in `shutdown`, it does - it's exactly the same as pressing esc (or doing `:fullscreen --leave`).

**Comment by lahwaacz** [comment]
Finally got it, thanks for the help!

**Comment by forkbong** [comment]
A similar thing happens if the window was initially maximized. Entering and exiting fullscreen, (either by clicking the fullscreen button on youtube or by pressing F11) makes the window unmaximized.

Of course this should not apply to tiling window managers because they don't even support maximized windows AFAIC.

**Comment by The-Compiler** [comment]
@forkbong Hmm - Qt has `.isMaximized()` which we could check here I guess, but it says that it won't always report the correct thing depending on the WM. I don't have an easy way to test this right now.

**Comment by Sophist-UK** [comment]
There appears to be some confusion in this issue (and possibly in Qt itself) between Fullscreen mode (which utilises literally the full screen without a window titlebar) and Maximised mode (where it uses all the screen not reserved by e.g. the windowing subsystem for taskbars, menu button, widgets etc.).

Double-clicking on the titlebar usually (in Windows at least) results in the window being Maximised rather than it going into Fullscreen mode.
