### ISSUE TITLE
New config: Documentation / Migration

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2793]
When qutebrowser is started the first time with the new config code in place, it should open an information page telling the user what's going on.

The page should contain:

- What happened.
- How the new configuration with `config.py` and `autoconfig.yml` works.
- Location of the old config (probably renamed to `qutebrowser-legacy.conf` or so) and the old key config.
- Location of a `config-example.py` or so.
- A diff of the old default config to the config the user had. See [difflib](https://docs.python.org/3/library/difflib.html) and [pygments](http://pygments.org/docs/lexers/#lexers-for-diff-patch-formats).

**Comment by lahwaacz** [comment]
As for `config-example.py`, shipping the file along with the browser would be hard because there is no standard location for such files. Many *nix manuals are full of hard-coded paths that don't match reality of the system where they exist. To make the informative page work as intended, packagers would have to somehow tell qutebrowser which path should be displayed. I think it would be much simpler if the file lived only in the repo and the page contained a link to the file.

**Comment by The-Compiler** [comment]
It'd probably be easiest if qutebrowser generates it when there's a legacy config but no `config.py` yet. There could also be a `qutebrowser --write-example-config` or so.

**Comment by The-Compiler** [comment]
I decided to not have a `config-example.py` at all - hopefully the documentation is enough.
