### ISSUE TITLE
Handling opening of unknown schemes

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2833]
Some discussion in IRC:

- There should probably be a setting for a whitelist of schemes allowed to be opened without prompting (as a per-domain setting)
- Currently there's no prompt at all with QtWebEngine, but at least it only allows opening unknown links after an user gesture.
- Also see [QTBUG-58627](https://bugreports.qt.io/browse/QTBUG-58627)
- Maybe a `QWebEngineUrlRequestJob` can be abused to at least handle `magnet://` links for QtWebEngine?

**Comment by aramiscd** [comment]
In the meantime e.g. following a magnet link leads to an error page (`ERR_UNKNOWN_URL_SCHEME`). From there, users can pass the url to an external application with `:spawn`.  On linux `:spawn xdg-open {url}` should work.  Otherwise, call the application directly, e.g. `:spawn transmission-gtk {url}`.

If this is the wrong place for that type of comment, please let me know.

**Comment by Ambrevar** [comment]
As a workaround, I currently use the following bindings for the Transmission daemon:

```
config.bind(',t', 'hint links spawn transmission-remote -a {hint-url}')
config.bind(',T', 'hint -r links spawn transmission-remote -a {hint-url}')
```

This way I can keyboard-select the magnet links, it's usually fast enough.

**Comment by The-Compiler** [comment]
As pointed out in IRC, on https://www.archlinux.org/download/ following the link via `:follow-selected` works, while `:hint` does not.

**Comment by khaalidrafi** [comment]
Looks like now it by default uses `/usr/bin/xdg-open` for mailto links? I shadowed it with `handlr open` in my system with a script in  `~/.local/bin/xdg-open`. But, that doesn;t work. Can I set qutebrowser to use `handlr open`?
