### ISSUE TITLE
auto-insert-mode shouldn't apply to tabs opened in the background

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2858]
When `auto-insert-mode` is on, doing `:open -b ddg.gg` shouldn't enter insert mode.

**Comment by Penaz91** [comment]
Might not be just a modeman issue, since you can type inside the background tab too.

Steps to reproduce
1: `open -b ddg.gg`
2: Type (blindly) any search (I used banana) and press enter
3: Put the background tab in foreground, the search will be made.

This makes me think that background tabs are not really in background.

**Comment by Penaz91** [comment]
I might have a patch for this, I'm trying to prettify it a bit, even if it's just 2 lines of code xD
