### ISSUE TITLE
[Arch Linux] Open qutebrowser with WebEngine by default

### ISSUE THREAD

**Issue by ikocevski** [qutebrowser/qutebrowser#2926]
Hi, I'm using Arch Linux and the official package via `pacman` has a hard dependency on Qt-WebKit. This means I'll have to install both WebKit and WebEngine to use the latter. Then, I'd have to type in the whole command with the argument (I can't recall the exact line ATM) to open qutebrowser with WebEngine. It takes too much time to open a browser like this.

Remove the hard dependency on Qt-WebKit from the Arch repository and let us choose the rendering engine on install (I've seen _gradle_ doing this). This way we can just type in qutebrowser in a terminal and it will run with the one we prefer. Or if that's not possible at least implement the option to choose the default somehow (preferably via the config file).

Also, while we're at this, why not just switch the default straight to WebEngine? Y'know, without the Google code?

**Comment by The-Compiler** [comment]
You can put a wrapper script in e.g. `/usr/local/bin` which looks something like this:

```bash
#!/bin/bash
exec /usr/bin/qutebrowser --backend webengine "$@"
```

For the rest, see #2335 and #2589.

**Comment by ahsis** [comment]
+ distributions generally decided how they package the software not the developer but since there hasn't been a qutebrowser release which regards webengine as stable, arch developers default to qt5-webkit which isn't that bad nowadays actually thanks to annulen.
+ distro's will probably make you choose between webengine and webkit when you install qutebrowser and once the new config is online if you have both installed for whatever reason you can choose which one you want by default
+ the most simple solution for your problem is qutebrowser-qtwebengine from AUR
