### ISSUE TITLE
Creating a template config.py

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2980]
Like mentioned in IRC, having a template `config.py` would help a lot with writing a custom one.

It could look roughly like this:

```
# Some explanations and a link to the docs

## Settings
# Description for content.javascript.enabled (probably just the short version)
# c.content.javascript.enabled = True   # default value
# ...

## Bindings
# config.bind('j', 'scroll down', mode='normal')
```

It'd probably be created automatically when there's no `config.py` around (as it only contains comments), 

I'm not sure though how easy it is to write a properly working file (i.e. one which would be valid if all settings were uncommented).

Also, there could be some kind of `:config-write-py` or so command, writing either the default, or the settings in `autoconfig.yml` currently - see #2794.

Also see #2793.

**Comment by jasonwryan** [comment]
Rather than creating a template that would have to work if someone uncommented everything (or worse, randomly uncommented some lines but not others), would a simpler approach be to just include a qutebrowser.conf man page? I'd be happy to draft one if you wanted to go down that path...

**Comment by jgkamat** [comment]
@jasonwryan, there is already documentation on `autoconfig.yml` and `config.py` here: https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc. I do think it could be fleshed out into greater detail though.

The benefit of having a basic template is that most people (sadly) don't read manuals, and just try to brute force solutions to save time. While a template config.py shouldn't be comprehensive (that's what documenation is for), it should have the most basic functionality, so that people don't need to read lots of manuals to start off (and give them a solid foundation). I don't think it would be too hard to create very basic config blocks that could be independently uncommented (and it's on the user not to do something 'bad' in the `config.py` file, since it is `config.py`, not `autoconfig.yml`).

**Comment by jasonwryan** [comment]
@jgkamat Yes, I'm aware of the asciidocs. Personally, I'm more likely to look for help in a man page. In any event, I agree more examples would be helpful, wherever they are located.

**Comment by The-Compiler** [comment]
I'd rather not duplicate the same information in a man page, sorry.

**Comment by lahwaacz** [comment]
I really think that creating a dummy `config.py` automatically is a bad idea. What if the API used in the comments changes one day? You would either have to do a complicated migration or users end up with a wrong and confusing example. I think that the decision to split the configuration system into separate automatically- and user-managed parts was great, it would be nice to keep it that way without partial bridges to close the gap.

@jgkamat People who want to use `config.py` to customize anything will have to read (parts of) the documentation sooner or later anyway, so if they can't find the basic template _in the documentation_ to get started, they wouldn't get far even if they had it prepared in `config.py`. And if they don't want to customize and use `config.py` just because "it is cool", they should not use it in the first place...

**Comment by jgkamat** [comment]
Hmm, I would really hate for the api to change at all (its going to be painful either way if it does, since people would have to rewrite their configs regardless).

I think that even a template such as:

```
# Welcome to your config.py configuration file, for advanced users
# Please go to <URL> for full documentation about using this feature

# Binding documentation is here: <URL>

# Settings documentation is here: <URL>

# etc.
```

Would help a lot, especially for people who are exploring, or people who want to be sure where the config.py is located before trying to modify it.

I find that people (including me) learn by example a lot more quickly than they learn from documentation, so I mainly want easily accessible concrete examples somewhere for people to use. I like the idea of a config template since it's much easier to copy paste examples directly from the template than go to documentation for everything, but I don't think it's that much worse.

**Comment by The-Compiler** [comment]
@lahwaacz you do have a valid point here. What do you think about creating a config-example.py instead which qutebrowser can update at will (but will not create if a config.py exists)?

**Comment by lahwaacz** [comment]
> I would really hate for the api to change at all

Obviously, but if there is no template to be maintained, you could create deprecation warnings for the old calls and remove it completely after a year or so. But this standard deprecation strategy does not really work with the commented examples, you would still have to do the migration at some point.

> I think that even a template such as [...] would help a lot

That's a user preference from just one side. I'm a person who does not like dummy files to be ever created in his `$HOME` tree, the proper place for such "example documentation configs" is `/usr/share/doc/` (not even `/etc/` if it was a system tool) &mdash; at least in Arch Linux, on your system it might be different &mdash; and users should copy the file to the appropriate location when they want to use it. See also [this aged post of mine](https://lists.archlinux.org/pipermail/arch-general/2014-May/036386.html). I think that's also why @The-Compiler decided to not create the `config-example.py` in https://github.com/qutebrowser/qutebrowser/issues/2793#issuecomment-329957303.

> I find that people (including me) learn by example a lot more quickly than they learn from documentation

The two things don't exclude each other, you can have a comprehensible [Quickstart](http://docs.python-requests.org/en/master/user/quickstart/) with many examples and a comprehensive [API reference](http://docs.python-requests.org/en/master/api/). True, for a library the idea of a _template_ does not make sense at all, but I'm sure you get the point.

**Comment by lahwaacz** [comment]
@The-Compiler It seems that we were writing at the same time; I would not like the `config-example.py` to exist in my `$HOME` at all so finding out a suitable location would be hard. See also https://github.com/qutebrowser/qutebrowser/issues/2793#issuecomment-313406179.

**Comment by The-Compiler** [comment]
FWIW the main reason I didn't do this in #2793 is that I wanted to get the `new-config` branch in and wasn't sure whether it was needed.

What's the problem with having a `~/.config/qutebrowser/config-example.py` as long as no `config.py` exists though? I mean, I know the proper location would be something like `/usr/share/doc/qutebrowser`, but that just makes everyone's life harder here (packagers need to install it, I need to duplicate stuff in the repo, and it doesn't apply to macOS/Windows).

FWIW the alternative I see is just having a `:config-write-py` or so and documenting that it exists.

**Comment by lahwaacz** [comment]
It's completely useless if somebody wants to stick with `autoconfig.yml` and not use `config.py` at all. I don't like useless files lying around, ideally `~/.config/qutebrowser/` would not even exist after fresh-starting qutebrowser. That's currently not the case because of bookmarks and quickmarks (which IMO don't belong under `~/.config/` but that's different story), but I don't see a reason to add another omnipresent file when not necessary.

**Comment by The-Compiler** [comment]
There's a [`:config-write-py` command](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/commands.asciidoc#config-write-py) which can write such a template file. I decided to not write it automatically for the reasons @lahwaacz mentioned.

**Comment by ersi-dnd** [comment]
When config.py is created, then what will happen to autoconfig.yml? Which one is prioritised by Qutebrowser?

**Comment by The-Compiler** [comment]
@ersi-dnd autoconfig.yml isn't loaded when a config.py exists - see the [relevant documentation](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#loading-autoconfigyml).
