### ISSUE TITLE
error  while spawning editor! The process failed to start. after upgrade

### ISSUE THREAD

**Issue by McKean** [qutebrowser/qutebrowser#3038]
I've just upgraded to 0.11.0 and get this error now. The relevant line in my config is set like this:
`editor = /usr/bin/urxvt -name floating -e /usr/bin/nvim "{}"`

this used to work perfectly fine.

Thank for the help.

**Comment by jgkamat** [comment]
Can you try:

`:set editor.command '["urxvt", "-name", "floating", "-e", "vim", "{}"]'`

which works for me. You probably want to change `vim` to `nvim` though (I changed it so it would work on my computer).

**Comment by The-Compiler** [comment]
@jgkamat note that @McKean upgraded to v0.11.0, not the git master :wink:

@McKean What did you use before the upgrade? Can you reproduce this and then do `:report` so I can take a look at the debug logs?

**Comment by McKean** [comment]
Upgrade history:
```[2017-06-03 16:10] [PACMAN] Running 'pacman --color auto -U /tmp/yaourt-tmp-mckean/PKGDEST.EEF/qutebrowser-git-0.10.1.r739.gc0705e735-1-any.pkg.tar.xz'
[2017-06-03 16:10] [ALPM] installed qutebrowser-git (0.10.1.r739.gc0705e735-1)
[2017-06-21 13:48] [PACMAN] Running 'pacman --color auto -U /tmp/yaourt-tmp-mckean/PKGDEST.wa5/qutebrowser-git-0.10.1.r851.gcb5cd1a91-1-any.pkg.tar.xz'
[2017-06-21 13:48] [ALPM] upgraded qutebrowser-git (0.10.1.r739.gc0705e735-1 -> 0.10.1.r851.gcb5cd1a91-1)
[2017-08-20 17:26] [PACMAN] Running 'pacman --color auto -U /tmp/yaourt-tmp-mckean/PKGDEST.og8/qutebrowser-git-0.11.0.r393.g173688c74-1-any.pkg.tar.xz'
[2017-08-20 17:26] [ALPM] upgraded qutebrowser-git (0.10.1.r851.gcb5cd1a91-1 -> 0.11.0.r393.g173688c74-1)
[2017-09-24 15:42] [PACMAN] Running 'pacman --color auto -U /tmp/yaourt-tmp-mckean/PKGDEST.bJs/qutebrowser-git-0.11.0.r969.gfb9fca247-1-any.pkg.tar.xz'
[2017-09-24 15:42] [ALPM] upgraded qutebrowser-git (0.11.0.r393.g173688c74-1 -> 0.11.0.r969.gfb9fca247-1)
```
Reported.

However after doing all this I did what you suggested @jgkamat and it worked like a charm. @The-Compiler does the config file not have any effect anymore? Is there a file we can store these configurations?

Thanks a lot for the quick help.

**Comment by The-Compiler** [comment]
Ah! Versions for Git packages typically look like `<last tag>.r<commits since then>.g<commit id>`. So you upgraded from something 393 commits away from v0.11.0 to something 969 commits away from v0.11.0, and what @jgkamat says is accurate :wink:

The config system changed recently, and you can write a `config.py` file if you prefer storing configuration in a hand-written file. A tab should've opened telling you about the change on the first start, but you can go to `qute://help/configuring.html` to show it again.

Finally, I'd recommend subscribing to the [qutebrowser-announce](https://lists.schokokeks.org/mailman/listinfo.cgi/qutebrowser-announce) mailinglist if you're using the git version - it's quite low-traffic (1-3 mails per month usually), but will tell you about important changes.

**Comment by The-Compiler** [comment]
I just noticed in your crash report that you're starting with `--backend webengine --enable-webengine-inspector` - two comments about that:

- There's now a `backend` setting, set to `webengine` by default, so you probably don't need `--backend webengine` anymore.
- `--enable-webengine-inspector` might allow other websites to access the inspector via [a trick](http://bouk.co/blog/hacking-developers/), so I wouldn't recommend leaving it turned on permanently.

**Comment by McKean** [comment]
many thanks!
