### ISSUE TITLE
Possibility to disable insert mode(Emacs like browsing)

### ISSUE THREAD

**Issue by schvabodka-man** [qutebrowser/qutebrowser#3143]
Hello, I really like this piece of software but there is one issue. For Emacs users modal editing can be very clunky. I know that qutebrowser was created as vim like browser, but it would be really awesome if there would be some switch in config to disable insert mode and allow to type text in normal mode. It would be useful for non vim users

**Comment by The-Compiler** [comment]
This is something I've thought about before, and I'm open to it as long as it's relatively simple to implement. Probably #319 would have to happen before it, though.

**Comment by pkillnine** [comment]
Couldn't you implement this yourself by deleting all the default binds via config.py, setting `c.input.forward_unbound_keys = 'all'` and binding everything you want to the modifier keys?

**Comment by The-Compiler** [comment]
Hmm, interesting idea - that might actually work.

**Comment by blyxxyz** [comment]
This is almost doable just by changing settings and binding keys. It just needs a way to disable insert mode and support for special keys in keychains.
A binding like `<ctrl+x><ctrl+f>` is impossible because special keys are handled completely separately from keychains. Special keybindings are keys in one dict, keychains are keys in another. As far as I can tell, that particular binding gets interpreted as the `ctrl+x><ctrl+f` special key, which doesn't exist. On the other hand, `<ctrl+c>c` gets interpreted as that exact chain of normal keys.
It's probably better to change the key parser so it handles special keys and normal keys the same way, using tuples of strings instead of strings or something.

**Comment by The-Compiler** [comment]
@blyxxyz Why would you need to disable insert mode - wouldn't `c.input.forward_unbound_keys = 'all'` as suggested by @pkillnine above work? As for the bindings, see #319.

**Comment by blyxxyz** [comment]
Because selecting an editable element (through hints or through clicking) always enables insert mode, which in Emacs-style editing just disables command keybindings for no benefit.
Would a complete Emacs-style example config.py be something to bundle with qutebrowser?

**Comment by The-Compiler** [comment]
> Because selecting an editable element (through hints or through clicking) always enables insert mode, which in Emacs-style editing just disables command keybindings for no benefit.

Fair point. We already have `input.insert_mode.auto_leave` and `auto_load`, I'm not opposed to adding a `auto_click` or so.

> Would a complete Emacs-style example config.py be something to bundle with qutebrowser?

I guess it'd be fine to put it in the repo in a `misc/example_configs` or so and link it from the [config docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).
