### ISSUE TITLE
Support for webextensions

### ISSUE THREAD

**Issue by schvabodka-man** [qutebrowser/qutebrowser#3186]
Hello? Are there currently any plans to include support for webextensions? They're pretty universal and now every mainstream browser use them. Qutebrowser is running on webkit, so implementing webext's in it won't be that hard.

**Comment by The-Compiler** [comment]
See #30.

> Qutebrowser is running on webkit, so implementing webext's in it won't be that hard.

This isn't true. QtWebKit/QtWebEngine don't have anything which would help with this.

**Comment by edrex** [comment]
Just a user report: IMO web extensions are now an integral part of the web platform and without them qutebrowser is again missing a key browser feature. I moved to FF 6mo ago to get webextension support. In my case, I am using a custom extension to sync activity data to Perkeep.

Python plugins are not equivalent or related, as this is about supporting the large population of existing extensions rather than providing some extension mechanism.

Upstream: https://bugreports.qt.io/browse/QTBUG-61676

**Comment by The-Compiler** [comment]
@edrex Sure, I don't think anyone disagrees. There's just little qutebrowser can do without QtWebEngine supporting this, and support for it in QtWebEngine is likely to be a quite big task - FWIW Brave tried the same with their [Muon](https://github.com/brave/muon) fork of Electron, and while they [got something to work](https://brave.com/loading-chrome-extensions-in-brave/) they ended up [with a rewrite using Chromium's UI](https://brave.com/development-plans-for-upcoming-release/) instead:

> We’ll have full extension API support. Over time, we will extend the extension API for Brave to express things such as specific shield settings. More on our extension plans in a future blog post, but for now, the good news is that Brave will be able to support many extensions that our users tell us they need in order to switch.

**Comment by smnthermes** [comment]
Why not just rebase qutebrowser on Firefox or Chromium?

**Comment by The-Compiler** [comment]
@smnthermes There are various Firefox/Chromium addons which do something similar than qutebrowser, see the README for a list.

**Comment by smnthermes** [comment]
So the reasoning against rebasing is that it would be hard to maintain qutebrowser?

**Comment by edrex** [comment]
@smnthermes  this is kind of a nonsensical question. qutebrowser is not a browser extension, it's a pyqt codebase using QtWebEngine. There's no way to port it to work within chromium or ff. There are extensions that do something similar, but they suffer from the limitations of the extension APIs. You are free to use one of those (Vimium is a good place to start, and works on both).

**Comment by smnthermes** [comment]
From another issue:
> Firefox had the issue of having a plugin API which tightly integrates with its internals, and had to drop it because it made further Firefox development harder, and bigger changes impossible

There isn't evidence for this at all, extensions can't modify the rendering engine. Mozilla's intent is to turn Firefox into a Chrome copycat, even in seemingly inofensive things such as [dumbing down the address bar](https://www.ghacks.net/2020/02/28/firefox-75-address-bar-results/) (read the comments by Iron Heart).

Also, considering that qutebrowser has a small team, it may be better to let extensions inject code into qutebrowser rather than writing APIs for them.
