### ISSUE TITLE
fullscreen to window option

### ISSUE THREAD

**Issue by plexigras** [qutebrowser/qutebrowser#3213]
i would like to see an option that allows me to instead of going into wm side fullscreen mode maximize it only inside the window or maybe even just the tab.

ps.: i don't know much python but i think this might be what is doing the maximizing

https://github.com/qutebrowser/qutebrowser/blob/984dd1ba8c5ae7b9bd940cc6cf241ab3218f1f61/qutebrowser/browser/webengine/webenginetab.py#L720-L730

**Comment by Enzime** [comment]
Whoever implements this should allow three options for the setting `always`, `never`, `prompt`.

**Comment by The-Compiler** [comment]
That seems like a slightly different thing, no? If you prevent a website from entering fullscreen, it should probably not be allowed to be in-window fullscreen either?

**Comment by Enzime** [comment]
From my perspective, window fullscreen is okay because the page already had nearly that amount of screen real estate already, but you're preventing it taking over your whole monitor in the case where your window isn't the same size as your monitor.

**Comment by The-Compiler** [comment]
Fair - though I'm not convinced having a "permission" for fullscreen makes sense, as AFAIK QtWebEngine only allows it as response to an user gesture (e.g. clicking a button) anyways.

**Comment by Ape** [comment]
One use case for this is playing YouTube videos so that you only have a browser window (not using the whole screen), but inside that window there is only the video content. This way no room is wasted for the web page layout (comment section and what not).

I can already do this by using my window manager to prevent the fullscreen so that the application still thinks it's fullscreen even when it really is a window.

**Comment by The-Compiler** [comment]
Done in #3285, thanks @quxs!
