### ISSUE TITLE
External editor keys and command hard to find

### ISSUE THREAD

**Issue by dschrempf** [qutebrowser/qutebrowser#3235]
Hello,

I am using qutebrowser v1.0.2.

The keyboard shortcut `CTRL-E` to open an insert field in the external editor was very hard to find for me. Is it possible to include it to the quickstart, or the keybinding cheatsheet?

Additionally, the command `open-editor` is not shown in the help and also not auto completed.

Thank you very much,
Dominik

**Comment by The-Compiler** [comment]
It is already in the [cheatsheet](https://qutebrowser.org/img/cheatsheet-big.png) (at the bottom right under "modifier commands -> in insert mode") and in the help (`:help :open-editor`).

I'd rather not include it on the quickstart page as that's intended to show the basics only.

The command was hidden from the completion because it couldn't be used in normal mode in an earlier release, however that has changed - so I did unhide it now in bb208f4e7736312aa8bfc1763f166b84f2259169.

**Comment by dschrempf** [comment]
Oh, I didn't see the CTRL-E in the cheat sheet. Thanks a lot!

**Comment by grahamperrin** [comment]
I don't know the origin of <https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/img/cheatsheet-big.png>, but I assume that it's more recent.

**Comment by The-Compiler** [comment]
@grahamperrin This issue is from 2017, the cheatsheet is from 2014, and linked from a variety of places (for starters, the quickstart page opening on the first start of qutebrowser). So, not sure what your point is there...

**Comment by grahamperrin** [comment]
Sorry, I'm not familiar with the quickstart page. 

Please, which of the two linked sheets is the more recent?

**Comment by The-Compiler** [comment]
Oh, weird, they are supposed to be the same. I opened #7004 to track this. The one in the git repo is indeed more recent.
