### ISSUE TITLE
Sessions saved in private mode are empty

### ISSUE THREAD

**Issue by aayla-secura** [qutebrowser/qutebrowser#3248]
Not sure if it's a bug or the intended behaviour but when in private mode, `session-save` saves an empty session file (or should I say, containing `windows: []`. It makes sense that when a user explicitly requests a session to be saved, this should be respected even in private mode when history is not being stored.

**Comment by The-Compiler** [comment]
What Qt version, backend and qutebrowser version?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by aayla-secura** [comment]
Sorry, my bad. I tested with both backends, here's some more info from `qutebrowser --version`

```
qutebrowser v1.0.2
Git commit: 
Backend: new QtWebKit (WebKit 602.1)

CPython: 3.5.4
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017
```

**Comment by The-Compiler** [comment]
I thought this was a bug fixed recently(-ish), but that was actually about `:restart` (which uses session files internally).

This is actually intended - you'll need to pass the `--with-private`/`-p` switch to `:session-save` for it to include private windows. The reason they aren't included by default is because people usually use private mode only for individual windows (via `:open -p`), and you'd usually not want those to be included.

**Comment by aayla-secura** [comment]
Oooh, I see, that makes sense! That option `--with-private` must have been a fairly recent addition, I don't remember seeing it when I first read the commands help section. Thanks!
