### ISSUE TITLE
Re-enter insert/passthrough mode after temporarily leaving it

### ISSUE THREAD

**Issue by pevu** [qutebrowser/qutebrowser#3324]
Qutebrowser shouldn't change modes unless the user wants to. As an example of when this occurs, when you're in `passthrough` mode, saving an image by *right click* > *save* will return you to `normal` mode instead of `passthrough`.

Maybe it's possible to have each command, that potentially changes the active mode, restore the previous mode before exit. Either by not storing the state anywhere and passing it as arguments (like in functional programming):

	def my_command(qb_state, ...): # qb_state: current state of qutebrowser, incl. current mode
		... # do something
		return qb_state

Or like this:

	def my_command(qb_state, ...):
		prev_mode = qb_state.mode
		... # do something
		qb_state.mode = prev_mode
		return

Either way, since only one command is executed at a time, the call stack would do all the work. 

Commands, that change tabs, would leave the state alone, allowing each tab to have its own state.

**Comment by The-Compiler** [comment]
It's not as easy as that, unfortunately - when a command e.g. displays a prompt, the command handler function is left, as control needs to return to Qt's mainloop, and everything after that is asynchronous.

Like briefly mentioned in IRC, qutebrowser used to have a stack of modes, introduced in 3d292fbc27ad1c60152279a8198e2502451d5bd5 and removed in 03ac8874ff3036069c72e96f6268235a34b26ea2 because it caused a lot of funny issues (see the issues/commits linked in that commit). Maybe it'd work to have more granular case-by-case saving/restoring of modes - i.e. save the mode before a prompt was shown (at least for insert/passthrough mode, others are probably more troublesome) and restore that once it's left.

**Comment by Plonq** [comment]
IMO this is most important for passthrough mode. An example is a webapp that has its own keybindings. I want to leave that webapp in passthrough mode all the time, but if a part of it regularly triggers javascript confirm dialogs, you constantly have to re-enter passthrough mode.

To me passthrough mode is special, because it's like a "normal browser" mode and I'd like it to be permanent until turned off (for my use case anyway).
