### ISSUE TITLE
Pinned tabs partly or completely hides tab number

### ISSUE THREAD

**Issue by bitraid** [qutebrowser/qutebrowser#3342]
This only happens with v1.0.4 on Windows, and is more obvious when using a large font size for tabs. You can see this clearly if you set `fonts.tabs` to something like 24px (I have tried it with Consolas and Terminus) and pin a tab with a favicon. The tab size shrinks too much and also hides the number.

**Comment by jgkamat** [comment]
My first guess is that this was fixed in #3250. 

Do these screenshots look like the problem you're having to you? 

v1.0.4
![2017-11-29-121144_116x62_scrot](https://user-images.githubusercontent.com/4349709/33388679-9b85b8dc-d4fe-11e7-9251-065274b10d5e.png)

master:
![2017-11-29-121102_416x149_scrot](https://user-images.githubusercontent.com/4349709/33388690-a0d80ac4-d4fe-11e7-9c01-fb103830207d.png)

In addition, master also scales the size of the icon up in the vertical direction as well, even when no pinned tabs are present. I know building on windows is a bit hard, but could you try to see if this problem is present on the latest master as well?

**Comment by The-Compiler** [comment]
FWIW here's a build of the latest master: https://qutebrowser.org/tmp/3342

**Comment by bitraid** [comment]
The link for the latest builds gives me all zero files. The problem i'm having is what is shown in the screenshots though.

**Comment by jgkamat** [comment]
@bitraid, the link seems to work for me. Maybe you would have better luck with a direct download link?

https://qutebrowser.org/tmp/3342/qutebrowser-1.0.4-windows-standalone-amd64.zip

**Comment by bitraid** [comment]
The files download ok and the size seems correct, but they don't have any content (all bytes are zero). Can you open the file? I've tried different machines, browsers (even tor), but i get the same result...

**Comment by jgkamat** [comment]
Ah, I just assumed the file was good after seeing the size (or that you were having trouble starting the download), I have the same problem too when I try to unzip (the file is all 0 bytes). Sorry for doubting you! :)

 @The-Compiler could you double check the files were uploaded properly?

**Comment by The-Compiler** [comment]
Yeah, looks like I messed something up. I'll build a new release when I get a minute.

**Comment by The-Compiler** [comment]
I just uploaded a new "release" - can you test with that please? I blame VirtualBox for corrupting the previous one :wink:

**Comment by bitraid** [comment]
Yes, this build works ok.

**Comment by jgkamat** [comment]
Thanks! I think this issue can be closed then, since it's fixed on master already. It should make it into the next major release. If this is bugging you a lot, you can continue to run the build from master :)

**Comment by bitraid** [comment]
@jgkamat thanks for the quick response and @The-Compiler thanks for the new build.
