### ISSUE TITLE
hackernoon article shows black box over text

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3343]
https://hackernoon.com/the-decline-of-stack-overflow-7cb69faa575d shows some weird black box over the text, but things look good in other browsers (even QupZilla).

When reloading in the middle of the text, things seem fine.

**Comment by helbling** [comment]
Seems to be caused by `<canvas class="canvas-renderer" ...>` which contains the Title and title image and has `position:fixed`.
If you set that to display:none, the text will appear again. Also disabling its `background:#fff` works as well.

I'm wondering if it's just a rendering bug which might have been fixed in a newer chromium version.

**Comment by The-Compiler** [comment]
I can also reproduce it with Qt 5.10 - also, that doesn't explain why it works fine with QupZilla :wink:

**Comment by The-Compiler** [comment]
I can't seem to reproduce this anymore (maybe the site changed?).
