### ISSUE TITLE
Downloads bar shown over fullscreen videos

### ISSUE THREAD

**Issue by yantar92** [qutebrowser/qutebrowser#3426]
Is downloads bar supposed to be shown in full screen mode?

qutebrowser v1.0.4
Git commit: d4cadcc62 (2017-12-07 08:17:15 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)

**Comment by jgkamat** [comment]
I think this is intended behavior I think you might like the `downloads.remove_finished` setting though.

**Comment by yantar92** [comment]
Sorry, I was not very clear.
What I mean is that it is shown when full screen video is being played. Showing downloads bar in full screen mode is ok in general case.

**Comment by jgkamat** [comment]
Ah, I can reproduce that, and I don't think that's intended.

**Comment by Brynildsen** [comment]
May I suggest giving it a function to either show or hide.. Like you can do with tabs and statusbar, xx, xb, xt. In some cases if you only have a single download it can be nice to still keep an eye on it's progress when watching video fullscreen while waiting for it to finish. But in cases where you have 15 downloads running it is pita because it takes up so much screen space..
