### ISSUE TITLE
Which complier should I use?

### ISSUE THREAD

**Issue by Okyougotme** [qutebrowser/qutebrowser#3442]
![screen shot 2017-12-27 at 12 04 35 am](https://user-images.githubusercontent.com/34583010/34371319-1cb3d564-ea9a-11e7-9a63-aa24bd889cf8.jpg)

Which complier should I use? Can I use GCC in Terminal to compile, Atom with run code in Atom package or do I need to download Xcode? Also I already have developer tools installed in Terminal. I’m new to the browser reason for all the questions. 

I get this error when attempting to compile using Atom:  uninitialized constant Formula (NameError)
How can I resolve this issue. Thanks in advance.

![screen shot 2017-12-27 at 12 30 20 am](https://user-images.githubusercontent.com/34583010/34371674-35a4297c-ea9d-11e7-8e9c-5d23b7558ef7.jpg)

Should I change the name from the source file: usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb:3

![screen shot 2017-12-27 at 1 01 01 am](https://user-images.githubusercontent.com/34583010/34372271-83a34096-eaa1-11e7-85b7-44387d64cce8.jpg)

**Comment by The-Compiler** [comment]
This all has nothing to do with qutebrowser, and I can't help you with those questions. I suggest you find the right channel to get support for Homebrew.

**Comment by Okyougotme** [comment]
I can tell from the beginning you didn't want to help me, for the mere fact you're Closing all my tickets. What is the big deal about you pointing me in the right direction. I'm just trying to to be able to use your browser as my default. I don't think I'm asking for a lot. Have a blessed day

**Comment by The-Compiler** [comment]
> I can tell from the beginning you didn't want to help me

I'd appreciate it if you didn't jump to (wrong) conclusions. It's not even that I don't want to help you, I *can't*, because I have no idea about the things you're asking about, because they're not related to qutebrowser at all.

> for the mere fact you're Closing all my tickets.

Because this is a tracker for qutebrowser issues.

> What is the big deal about you pointing me in the right direction

Which is exactly what I did.

**Comment by jgkamat** [comment]
@Okyougotme, I looked around, and I think a good starting point is [one of the community homebrew options](https://github.com/Homebrew/brew#community), such as #machomebrew on freenode.

**Comment by Okyougotme** [comment]
I will check it out

**Comment by Okyougotme** [comment]
I open the issue with home brew team however, they requested I seek help here.

![screen shot 2018-01-02 at 4 17 17 am](https://user-images.githubusercontent.com/34583010/34479289-df6937ce-ef73-11e7-9439-1fc9aaab44ce.jpg)

**Comment by The-Compiler** [comment]
Do you have a link?

**Comment by mschilli87** [comment]
cross-reference: https://github.com/Homebrew/brew/issues/3623

---
@Okyougotme: Please consider that you already emailed around 600 people
(repeatedly) and nobody is trying to treat you any worse than anyone else.
You will need some patience and you will be expected to read the
information availabe.

You complain people close an (invalid?) issue because you didn't know of
the issue checklist?  I just tried to open an issue at
https://github.com/Homebrew/brew/issues/new and the checklist was already
there.  You had to delete it without bothering to even read it to open your
issue there in the first place. There is a good reason this information is
there: To prevent people to open invalid issues without bothering hundreds
of people.

I suggest you read @jgkamat's last message (that you agreed to, without
actually clicking the link therein and reading, it seems) and contact the
homebrew community on freenode (*not* by opening an issue ignoring the
template clearly asking you not to do so).

If people start ignoring/banning you (which so far nobody did), it is
because you don't convey respect to people offering you help, free of
charge, in their free time.
