### ISSUE TITLE
Incremental search + Enter jumps to the next match

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3511]
When I write `/search term` and press `Enter` to finish the prompt, qutebrowser jumps to the _second_ occurrence while the first occurrence is highlighted even before pressing `Enter`.

```
$ qutebrowser --version
[0121/170550.774588:WARNING:stack_trace_posix.cc(648)] Failed to open file: /tmp/.glhjvleX (deleted)
  Error: No such file or directory
[0121/170550.774652:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/lahwaacz/#7081286 (deleted)
  Error: No such file or directory
qutebrowser v1.1.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.9.2

sip: 4.19.6
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.14.13-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/lahwaacz/.cache/qutebrowser
config: /home/lahwaacz/.config/qutebrowser
data: /home/lahwaacz/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

**Comment by The-Compiler** [comment]
I've seen this as well but can't reliably reproduce it.

cc @jupart

**Comment by jgkamat** [comment]
Hmm, on my machine I can reproduce this every time. I'm still on qt5.7.1 though...

**Comment by jupart** [comment]
I'll check this out soon.

**Comment by jupart** [comment]
I've been looking at this off and on, comparing to Vim search functionality. We could eat an Enter key press after incremental search, but it seems kind of hacky to me. I noticed that in Neovim (maybe Vim too), while typing the search term with incremental search set, 

1. it searches to the first matched term and highlights it as you type. After you press the Enter key, 
2. it searches for all matching words in the buffer (all the open buffers actually I think) and highlights them in a different color. 

I'd like to make incremental search in qutebrowser work this way, as I think it's a good design.

My idea was to add a `search_once` browser command that accomplishes 1. that incremental search can use. Then on an Enter key press, we `search` as usual.

**Comment by brianbuccola** [comment]
I've noticed this issue as well, and just wanted to make two quick comments.

1. This is specific to `<enter>`. If you hit `<esc>` instead, the search highlight remains, and the currently focused search is the first match. So, as a workaround, you can (train yourself to) hit `<esc>` (or `<ctrl-[>`) instead of `<enter>`.
2. One motivation (in case anyone needed one) for staying on the first match, instead of jumping to the second, is so that, if the first match is a link, then you can just hit `<enter>` a second time to follow the link. Obviously, hitting `<enter>` twice in quick succesion is way more comfortable than hitting `<esc>` then `<enter>` (and I myself have this bound to muscle memory from previous versions of qutebrowser and others).

**Comment by jgkamat** [comment]
Indeed, the second issue you mentioned is really bugging me, so I want to try to fix this before the next release, unless someone beats me to it.
