### ISSUE TITLE
Playing IMDb videos on Arch Linux with webengine

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#3512]
I just moved to a new machine running Arch Linux and now imdb.com videos won't play anymore on the latest Qutebrowser with the webengine backend.

It used to work fine on my previous setup which was more or less the same, so I'm not sure what went wrong.
Am I missing a specific package?
Any tip on debugging is more than welcome :)

**Comment by jgkamat** [comment]
I think that the most possible cause for this is not having non-free codecs enabled in webengine. 

(see https://github.com/qutebrowser/qutebrowser/issues/2944 :P)

I think someone with more experience with arch should answer this as well, but I would suggest trying to install https://aur.archlinux.org/packages/qt5-webengine-widevine/? I heard that it might have broken recently though, but I don't rememeber the details.

**Comment by The-Compiler** [comment]
Related logs:

```
[9541:9560:0121/204008.763263:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: demuxer error: 13"}
[9541:9560:0121/204008.763861:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: demuxer error: 13"}
[9541:9541:0121/204008.763961:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_COULD_NOT_PARSE
```

Looks like [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=731766), which is not fixed so far. I guess you could rebuild QtWebEngine to use its own ffmpeg instead of the system-wide one, if you feel like that's wirth the effort :wink:

Closing this now, as there's nothing qutebrowser can do here.

**Comment by gadefox** [comment]
I'm using Qt 5.15.2, ffmpeg 4.4 w/ the latest qutebrowser and I'm getting the same error:
[4907:14:0718/161726.079241:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[4907:1:0718/161726.080138:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}

Any idea? Do I need to install any codecs? Thanks.

**Comment by The-Compiler** [comment]
@gadefox Can you show your full `:version` output?

**Comment by gadefox** [comment]
https://paste.the-compiler.org/view/2e2e536e

ffmpeg version 4.4-1,   libavutil      56. 70.100 / 56. 70.100,   libavcodec     58.134.100 / 58.134.100,  libavformat    58. 76.100 / 58. 76.100,  libavdevice    58. 13.100 / 58. 13.100,  libavfilter     7.110.100 /  7.110.100,  libavresample   4.  0.  0 /  4.  0.  0,  libswscale      5.  9.100 /  5.  9.100,  libswresample   3.  9.100 /  3.  9.100,  libpostproc    55.  9.100 / 55.  9.100

**Comment by The-Compiler** [comment]
@gadefox looking at:

```
Qt library executable path: /opt/qt515/libexec, data path: /opt/qt515
```

you seem to run qutebrowser against a custom Qt build. I'm guessing that QtWebEngine isn't [built with proprietary codec support](https://doc.qt.io/qt-5/qtwebengine-features.html#audio-and-video-codecs).

**Comment by gadefox** [comment]
Well, I'm not sure, because I'm using prebuilt package. I will check.. Anyway, is this the Qt issue, what do you think?

ERROR:rtc_peer_connection_handler.cc(2531)] Failed to create native session description. Type: "offer" SDP: "v=0\r\no=- 4202735153657883392 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/TLS/RTP/SAVPF 109\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:d1ai\r\na=ice-pwd:9ZThfFqtDdGmWb3vRQKZqBSL\r\na=ice-options:trickle\r\na=fingerprint:sha-256 64:9E:4D:9F:45:70:06:11:5B:CA:D5:76:5A:02:21:AC:49:A2:7F:75:C6:1B:AA:8F:12:97:F3:3E:36:F7:7B:D0\r\na=setup:actpass\r\na=mid:0\r\na=sendrecv\r\na=msid: \r\na=rtcp-mux\r\na=rtpmap:109 google-data/90000\r\na=ssrc:216686932 cname:H+d6uNHiYQRWZA+b\r\na=ssrc:216686932 msid:- \r\na=ssrc:216686932 mslabel:-\r\na=ssrc:216686932 label:\r\n"
[12589:1:0719/190157.084658:ERROR:rtc_peer_connection_handler.cc(1366)] "Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute.

**Comment by The-Compiler** [comment]
That sounds more like a WebRTC issue you're posting there. Seems unrelated to the IMDB video thing.
