### ISSUE TITLE
Add a nice __repr__ to configtypes

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3646]
Objects in the `config/configtypes.py` module should have a nice `__repr__` function defined (which prints sub-types, attributes, etc.) to ease debugging.

**Comment by IcePinguin** [comment]
@The-Compiler  can I work on this

**Comment by The-Compiler** [comment]
@IcePinguin Sure, please go ahead! The idea is that showing a config type in the debugger (or logs) shows options which are passed via `__init__` - you can use `utils.get_repr` to simplify this, see other places where a `__repr__` is defined. If you need more information, please let me know!

**Comment by AlternateData** [comment]
Hello. Seeing as nobody has done a Pull Request on this yet,  I too would like to try myself on this. 
Yet I have several questions:

-  Using `utils.get_repr` Should the representation be in constructor form ? (  `'Foo(one=1, two=2)'` instead of  `'<Foo one=1 two=2>`  ?) 
-  If a variable is set to a (default) value by the super constructor do I need to include it into the representation of the subclass ? 
- Should private members of a class also be displayed ?
