### ISSUE TITLE
Detect bookmark as identical if only the trailing slash differs

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#3664]
Suppose I have

```
http://example.org Example page
```

in my bookmarks.  Now if I visit the page `http://example.org/` and press `M`, Qutebrowser will save an additional bookmark.
I think this should be avoided as it clutters the bookmark file.

**Comment by The-Compiler** [comment]
To be honest I'm not sure whether this is a good idea. Those two URLs [can, in theory](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html) contain different content (and I'm almost sure that's found in the wild :laughing:).

What do other browsers do? Do they allow to have the same URL with and without trailing slash as bookmarks?

cc @jgkamat

**Comment by jgkamat** [comment]
I took a look at firefox and chromium, and they both seem to treat these two files differently. I'm going off of the "bookmark star" they have in the top right to detect if they think it's the page is already bookmarked, rather than bookmark creation (as ffx and chrome allow duplicate bookmarks). 

Because of this, I'd support closing #3668 and perhaps asking people to make a userscript which checks for slash/slashless duplicates as they like, since it does seem a bit nonstandard (and hacky) to check for the two versions :P

**Comment by The-Compiler** [comment]
Closing this then - thanks for the suggestion @Ambrevar, but I think it's better to avoid "magic" here :wink:
