### ISSUE TITLE
Quickly repeated following of hints to background tabs fails with QtWebEngine

### ISSUE THREAD

**Issue by arza-zara** [qutebrowser/qutebrowser#3670]
To reproduce:
1. In qutebrowser run `:set tabs.background true`
1. In terminal run `sleep 5 ; xdotool type FaFa`
1. Switch to qutebrowser window and wait -> only one tab will be opened

This concerns only QtWebEngine.

Latest git (02c313eafd3e4dd818acf7b94ebee2911c5c5bb0) / QtWebEngine 5.10.1 (Chromium 61.0.3163.140)

**Comment by jgkamat** [comment]
I think you can get around this by using 'rapid mode', since I think that will calculate the hints only once (so you will only need to wait for the hints to come up one time, after that, it should be much faster).

Can you see if your automation will work in rapid mode?

`:hints--rapid links tab-bg`

**Comment by arza-zara** [comment]
Correct.

**Comment by The-Compiler** [comment]
Well, "don't do that". You're probably trying to follow hints (a fraction of a section) before they are shown, which just won't work. :wink:
