### ISSUE TITLE
Documentation - Ubuntu 16.04 LTS and Tox

### ISSUE THREAD

**Issue by AlvaroLuken** [qutebrowser/qutebrowser#3799]
![image](https://user-images.githubusercontent.com/25407127/38218345-70ec0f24-369f-11e8-8e58-17d2a7036fb1.png)

I am new to submitting issues and am looking at how to make Qute smoother for newbies (to installing on command line) like me. 

When installing Qute Browser for Ubuntu 16.04, the user is redirected to the install.asciidoc file:

I think the launch command should be in its own gray box or just not hidden under the tab 'Creating a wrapper script' - for newbies like me who are not yet too versed with Tox (yet run Ubuntu 16.04), it is not apparent that creating a wrapper script is equivalent or the path to launching - I spent a good amount of time looking for the launch command until I finally found it hidden into the short sentence. 

It should either be in its apparent tab or in a gray box so that scrolling through to find relevant commands is easier. So it should be: To launch browser etc etc...

.venv/bin/python3 -m qutebrowser

I'd be happy to do this myself too!

**Comment by jgkamat** [comment]
This sounds like a good idea to me, it woudl also help to space that section out a bit more. If you're comfortable, feel free to submit a PR with this change to get a contribution, otherwise, I can handle it :)

All you want to to is change:

Running tox does not install a system-wide qutebrowser script. You can launch qutebrowser by doing `.venv/bin/python3 -m qutebrowser`.

to:

Running tox does not install a system-wide qutebrowser script. You can launch qutebrowser by running:
```
 .venv/bin/python3 -m qutebrowser.
```

correct?

**Comment by AlvaroLuken** [comment]
Yup, got it on the nose ^ 

I agree that section should be spaced out better ; I will handle PR though (for the minor change)!
