### ISSUE TITLE
Theme files

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#381]
``` irc
10:10 <asdfqwerhkjdsafa> are there themes?
10:11 <The-Compiler> asdfqwerhkjdsafa: no - you can customize fonts/colors, but there aren't theme files or anything
10:11 <asdfqwerhkjdsafa> thank you
10:11 <asdfqwerhkjdsafa> *feature request*
10:13 <The-Compiler> I thought about config file "merging" which would also mean themes
10:14 <The-Compiler> but then a "theme" can overwrite any setting which might not be a good idea
10:14 <oed> couldn't those settings just be saved in two different files?
10:16 <The-Compiler> oed: you meah the [colors] and [fonts] setting would be in a separate configfile, like the keys are currently? Hmm.
10:17 <The-Compiler> that'd work, but probably .qutetheme files (or whatever) which can only contain these sections, which get then merged into the mail config would be simpler
```

**Comment by vyp** [comment]
+1, not to try and increase priority or anything, just to show support.

**Comment by vyp** [comment]
Also being able to define arbitrary colour palette variables such as `red`, `blue` etc, and being able to use them as normal via `${red}` would be nice.

**Comment by vyp** [comment]
Actually I think **if** that is done, instead of arbitrary variable names, you should only allow `colorN` where `N` is a number. Because:

1. Allowing other arbitrary variable names means there's potential for future conflicts; where you may want to specify a new variable, but someone may already be using that variable name in their config.

2. It makes sense to just use `colorN` anyway (sort of like with `.Xresources` files), because that signifies that there doesn't *have* to be a 'red-like' colour, etc etc.

The reason I think this could be useful is just that it allows to (at least partially) copy paste Xresources themes (or other similar things) if all one wants to do is change the colour *palette*, whilst keeping all the other colour options. This is of course already possible, but imo it's slightly uglier because the variable interpolation has to use widget/ui names such as `${completion.category.border.top}`, instead of just say `${color0}`.

**Comment by vyp** [comment]
Is it possible to set the colours for the search results (that is, searching in a web page via pressing `/`)? Because, if not, maybe it should also be an option for theming. (if possible)

**Comment by The-Compiler** [comment]
@vyp Unfortunately it's not.

**Comment by t1mxg0d** [comment]
One simple request would be able to redefine the colors such as red, green, yellow, etc as well as background/foreground. Or maybe similar to Termite where it uses color{0-15} similar to .Xresources.

These might be easier to accomplish when the config is in YAML/TOML.

Being a designer/front-end dev I'd glady translate a few themes from vim for the project. I;ve already spent quite a bit of time making my Qutebrowser pretty. :)

**Comment by Elronnd** [comment]
@vyp surely you would still be able to specify arbitrary 24-bit colours!

**Comment by The-Compiler** [comment]
Now that there's a `config.py` and ` :config-source` command, I think this is covered.
