### ISSUE TITLE
how can i yank current webpage url to wget to save image

### ISSUE THREAD

**Issue by peet1234** [qutebrowser/qutebrowser#3902]

**Comment by mschilli87** [comment]
<kbd>Y</kbd><kbd>Y</kbd> should be equivalent to <kbd>G</kbd><kbd>O</kbd>[highlight URL]<kbd>Ctrl</kbd>+<kbd>C</kbd> (or <kbd>Ctrl</kbd>+<kbd>L</kbd><kbd>Ctrl</kbd>+<kbd>C</kbd> in many other browsers), *i.e.* copy current URL to clipboard, while <kbd>Y</kbd><kbd>Shift</kbd>+<kbd>Y</kbd> would copy the current URL to the primary selection. How you paste the URL to you terminal to run `wget` depends on your system (<kbd>Shift</kbd>+<kbd>Insert</kbd> usually pastes the primary selection).

If you don't care about `wget`, you can also just type <kbd>G</kbd><kbd>D</kbd> to download the current URL directly from qutebrowser.

**Comment by peet1234** [comment]
i'm set :bind wg yank pretty-url -s spawn wget -nd -P /home/xx/tmp/ -A jpeg,jpg,bmp,png {ulr:pretty} 
but not work please  help

**Comment by jgkamat** [comment]
There's a couple things that are off with that command:

1. yank won't work directly with spawn, since yank copies to the clipboard and dosen't run any commands. You might want to look at `:help :yank`. However, we don't need to do this if we are actively visiting the image.
2. You misspelled `{url}` in `{url:pretty}`

When visiting an image, such as http://qutebrowser.org/doc/img/main.png, `spawn wget -nd -P /tmp -A jpeg,jpg,bmp,png {url:pretty}` works fine for me. 

If you want hints, you may want to look at `:help :hint` for more documentation on that.

**Comment by peet1234** [comment]
thank, that was work!!!!
