### ISSUE TITLE
Remember the devtools settings

### ISSUE THREAD

**Issue by BlackCapCoder** [qutebrowser/qutebrowser#3971]
Version 1.3.1

The developer tools window have its own settings accessible from the top right corner. These settings are not stored between sessions, which is annoying.

**Comment by jgkamat** [comment]
It's possible that this could be fixed by the new qt5.11 inspector. If it isn't this should proably be reported to qtwebengine, as that's where the inspector is coming from (we have little control over how it works)

**Comment by Synray** [comment]
[QTBUG-50766](https://bugreports.qt.io/browse/QTBUG-50766) reports having fixed the insecure inspector.

**Comment by jgkamat** [comment]
This isn't exactly about the inspector being insecure, this issue in particular is about remembering settings in the inspector. Im a bit too lazy to figure out if 5.11 fixed it (since pyqt5.11 isnt out yet), but it might have (I would personally think it has)

On June 5, 2018 7:42:18 PM EDT, Synray <notifications@github.com> wrote:
>[QTBUG-50766](https://bugreports.qt.io/browse/QTBUG-50766) reports
>having fixed the insecure inspector.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
I just tested with the Qt 5.11 simplebrowser example (which uses the new inspector API), and they're remembered there. So I'd expect this to be fixed once the new inspector API is used in qutebrowser (#3010).

**Comment by Jumblemuddle** [comment]
Is the devtools window also zoomable with Qt 5.11? Using it on a HDPI screen is almost impossible at the moment.

**Comment by BlackCapCoder** [comment]
@Jumblemuddle The devtools does scale correctly with the following flags

    QT_SCALE_FACTOR="1.8" qutebrowser --backend webengine --enable-webengine-inspector

**Comment by Jumblemuddle** [comment]
@BlackCapCoder Oh, nice! It's going to be a bit of a pain to figure out my font sizes again, but I'm glad there's a way to do this at the moment.
