### ISSUE TITLE
view_in_mpv script issue with youtube playlists

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#3977]
Hello, 
When using the ``view_in_mpv`` script on a youtube video which is part of a playlist, the downloaded video is the first from the playlist instead of the currently viewed video.

version: qutebrowser v1.3.1

**Comment by jgkamat** [comment]
You should be able to add --no-playlist to the launch options of mpv to force it to launch a single video. Not sure if we should add this to the default or not.

On June 4, 2018 12:49:52 PM EDT, Alexandre Provencio <notifications@github.com> wrote:
>Hello, 
>When using the ``view_in_mpv`` script on a youtube video which is part
>of a playlist, the downloaded video is the first from the playlist
>instead of the currently viewed video.
>
>version: qutebrowser v1.3.1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aleprovencio** [comment]
Indeed @jgkamat,
I've seen that the script has this ``--ytdl-raw-options=yes-playlist``, however I can't override it just by addind the ``--no-playlist`` to ``youtube-dl/config`` file. If this is a fact, IMHO the script should allow the default to be set on ``youtube-dl/config`` plus it just feels buggy because it blanks out the current viewing video but downloads another one.

Where exactly do you mean ``ytdl-args``?

**Comment by jgkamat** [comment]
> I've seen that the script has this --ytdl-raw-options=yes-playlist, however
> I can't override it just by addind the --no-playlist to youtube-dl/config
> file. If this is a fact, IMHO the script

Sorry about being unavailable to actually test this before, I was rather busy.

By just removing the '--ytdl-raw-options=yes-playlist=' argument, playlists
work as intended (for me).

For example, this command seems to be "broken":

mpv --force-window --no-terminal --keep-open=yes --ytdl --ytdl-raw-options=yes-playlist= 'https://www.youtube.com/watch?v=UqTUFLYz3Sk&t=0s&index=5&list=PL4BC045240D2FB11B'

But this command is fine:

mpv --force-window --no-terminal --keep-open=yes --ytdl 'https://www.youtube.com/watch?v=UqTUFLYz3Sk&t=0s&index=5&list=PL4BC045240D2FB11B'

See https://github.com/qutebrowser/qutebrowser/pull/3057 for why that was
added (from looking at the blame). It seems like a matter of preference to me,
so I think there should probably be a documentation line above that setting
explaining it (so people can disable it easily if they wish).

The argument will probably override any config files you have set, so that's
why that's not taking any effect.

Also see this issue for more information (it seems like mpv is passing
no-playlist by default):

https://github.com/mpv-player/mpv/issues/2592

Alexandre Provencio writes:

**Comment by The-Compiler** [comment]
I wasn't aware adding `--yes-playlist` plays the first video even when invoking it on a later video in a playlist - I agree it's better to remove the `--yes-playlist` argument in that case, which I just did.

cc @t-wissmann @jnphilipp
