### ISSUE TITLE
bookmark-del not showing msg info about deletion

### ISSUE THREAD

**Issue by freed00m** [qutebrowser/qutebrowser#3997]
Qutebrowser 1.3.1

When I bookmark, the msg is shown "Bookedmarked ...", however, when deleting, no message appears.

I was looking into the source code and it doesn't make any sense to me why it would not work.
The bookmark is however deleted. When attempting to bookmark-del again, I get msg about "not found url" wich is correct.

I can't seems to figure a way to debug as the qutebrowser.py dettaches itself and I can't seems to find how to prevent it from this happening.

**Comment by The-Compiler** [comment]
The reason for the message is that it's bound to `M` by default, so with that keybinding, there's no other feedback.

With `:bookmark-del` you typically execute it via the commandline, which means you already do get visual feedback - thus I don't think a message is necessary there.

> I can't seems to figure a way to debug as the qutebrowser.py dettaches itself and I can't seems to find how to prevent it from this happening.

You probably have a running instance open already - you might want to start with `--temp-basedir`.

**Comment by The-Compiler** [comment]
Are you aware of `:bookmark-add --toggle`? That adds a bookmark or removes an existing one, and shows messages for both. That might be better suited for a keybinding I guess, as you only need a single key.

And don't worry! I'm always open about discussing things - if you have a good reason to bind to `:bookmark-del` instead of `:bookmark-add --toggle`, feel free to open a PR which adds a message, no hard feelings either way :smile:

**Comment by freed00m** [comment]
I wasn't aware, however I want one key to only add and another to only remove, many accidents I would have using toggle.

I endup with this setup

```
config.bind('M', 'bookmark-del ;; message-info "Bookmark deleted {url}"')
config.bind('m', 'bookmark-add')
``` 

That's why it feels silly. :D but I am oke with it now.
