### ISSUE TITLE
Open tabs directly after current tab

### ISSUE THREAD

**Issue by noctuid** [qutebrowser/qutebrowser#4007]
Currently I have both `tabs.new_position.unrelated` and `tabs.new_position.related` set to `next`. With this configuration, new tabs open after the last tab opened from the current tab, but I'd like to have all tabs open directly after the current tab. Is there currently some way to achieve this, or could this be added as an option?

**Comment by jgkamat** [comment]
I don't think there's a way to do this currently.

The fix for this is pretty easy, I think (just comment this line):

https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/mainwindow/tabbedbrowser.py#L537

However, I'm not sure what an ideal interface for this would be. We could add
a new setting (maybe something about stacking related tabs), or we could make
new options for tabs.new_position.related.

Fox Kiester writes:

**Comment by noctuid** [comment]
I think the description for `next` is misleading since it doesn't always open tabs after the current. I think a new option for `tabs.new_position.related` for the current behavior would make sense, but it would break backwards compatibility. I think adding a new setting that determines how `next` behaves and then mentioning it in `tabs.new_position.related` probably makes the most sense.
