### ISSUE TITLE
Restart required to pick up rotated TLS cert

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#4020]
Given:

 1. You have attempted to load a page and gotten a "certificate expired" error.
 2. A new, valid certificate is subsequently installed.

Expected result: Reloading the page should succeed using the new cert.

Observed result: Reloading the page still results in a "certificate expired" error. Restarting qutebrowser allows the page to load successfully.

Background: I currently manually rotate the cert for my personal site every 3 months (Let's Encrypt) (need to automate it :) ). I usually notice the expired cert in qutebrowser, so I have seen this issue a few times.

**Comment by The-Compiler** [comment]
How does Chromium handle that case?

**Comment by edrex** [comment]
Not sure. Attempting to create a reproducable test case to check...

**Comment by The-Compiler** [comment]
FWIW there's nothing qutebrowser can do here either way - but either this can be reported to Qt, or it's just how Chromium does things. But yeah, not exactly easy to test...

**Comment by edrex** [comment]
Ok, I tested with Chromium, Firefox, Qutebrowser, and Falkon.

Methodology:

Test 1: 

 1. Load page in freshly opened browser using valid cert.
 2. Replace with invalid (wrong domain) cert and restart webserver (haproxy)
 3. Reload page in browser, note result.

Test 2: 

 1. Load page in freshly opened browser using invalid (wrong domain) cert.
 2. Replace with valid cert and restart webserver.
 3. Reload page in browser, note result.

Chromium, Falkon, and Firefox all pick up the cert change in both tests, while Qutebrowser continues using the initial cert on subsequent reloads.

**Comment by The-Compiler** [comment]
Oh, apologies, there's indeed something qutebrowser does differently here! I think you're actually running into #3918 here, i.e. going back (`H`) instead of reloading should work.

However, the custom error page is a workaround for [a Qt bug](https://bugreports.qt.io/browse/QTBUG-56207) which seems to be fixed in the meantime - in other words, I should be able to remove that hack so you get Chromium's error pages, and then qutebrowser should act just like Falkon (at least on Qt >= 5.9).

**Comment by edrex** [comment]
Omigosh that is what's happening. I thought I eliminated that as a possibility by typing in the URL but evidently not. Closing.
