### ISSUE TITLE
How can I allow blocked popups on the fly?

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4109]
In Chromium, if a popup is blocked, I get informed by a message in the omnibar and I have access to the option to allow it.

If I visit the same page with qutebrowser, I get no notification, which is puzzling (it feels like there is a problem with the site since clicking on a link has no effect). Even once I understand that the problem is a blocked popup (thanks to a visit to that site on Chromium), I do not know how to allow it in qutebrowser.

Thanks for letting me know how to properly handle blocked popups.

**Comment by prosoitos** [comment]
[On the same website](https://sims.sfu.ca/psp/csprd/EMPLOYEE/HRMS/h/?cmd=logout), I have a different but somewhat similar problem: when I need to see pdf that have been generated by the system, nothing happens (on other browsers, they open in a new tab).

qutebrowser does not allow in this case to have the pdf opened from `temp` nor does it offer to download it. Just, nothing happens.

This website is definitely not friendly on qutebrowser. Unfortunately, I need to use it regularly.

**Comment by The-Compiler** [comment]
See #2375 - unfortunately, QtWebEngine doesn't expose a way to do this...

What you can likely do however is changing the `content.javascript.can_open_tabs_automatically` setting to allow popups - it supports URL patterns, so something like `:set -u sims.sfu.ca content.javascript.can_open_tabs_automatically true` should work I think. I can't test since it requires a login.

**Comment by prosoitos** [comment]
Oh, sorry for not spotting #2375...

I will explore your suggestions. Thank you @The-Compiler.
