### ISSUE TITLE
Add a --config-py option to specify a path to an alternate config.py

### ISSUE THREAD

**Issue by jbwiv** [qutebrowser/qutebrowser#4132]
Currently, config.py is always expected to be found in <basedir>/config/config.py. However, there are many cases where it would be useful to specify the path to the config.py on the command line. For example, you may wish to use a custom config.py with ---temp-basedir, where the basedir isn't known ahead of time.

Please consider adding this functionality. It will be very useful.

Thanks.

**Comment by The-Compiler** [comment]
Also see #2115/671ce67be5bb2df6a13b408c19d8c79c76eaade4 which removed a similar `--confdir` setting - but I'm fine with just having a `--config-py` because it'd indeed be useful, and it's much more clear how it should behave (as `config.py` is read-only).

**Comment by cauimsouza** [comment]
Could I start working on this?

**Comment by The-Compiler** [comment]
@cauimsouza Sure, go ahead! :+1:

**Comment by xaverdh** [comment]
If I can help with that, give me a shout.

**Comment by xaverdh** [comment]
I gave it a shot in #4286
One test fails, probably because the code wich fakes the argument list has to be informed of the new argument. I don't quite understand how that works though; any pointers are greatly appreciated.

Another thing to consider is how this should interact with config-write-py feature.
Currently it doesn't at all, in the sense that the configuration will be written to <basedir>/config.py regardless of the new flag.  I think this is the right thing to do, but this is probably debatable. Either way the (non)interaction should be documented I guess?
