### ISSUE TITLE
text entered into editor not inserted

### ISSUE THREAD

**Issue by ExpandingMan** [qutebrowser/qutebrowser#4134]
Hello all, I feel like this is probably due to something really silly that I am doing or failing to do, so I was loathe to open an issue, but I can't figure it out for the life of me so here it goes.

When using `open-editor` (`Ctrl-E` when in insert mode by default) my editor opens successfully, I can enter text, and save to the buffer, but then nothing happens: nothing is inserted into the field either when I save or when I exit the editor.

My editor command is
```python
c.editor.command = ["gnome-terminal", "-x", "nvim", "-f", "{}"]
```
(again, nvim seems to open just fine)

Any idea what is going wrong?

**Comment by The-Compiler** [comment]
No worries! You're not the first one to have this issue, and it's a bit subtle :wink:

In order to find out when to stop listening to file changes, qutebrowser waits until the process it spawned exits. However, `gnome-terminal` probably forks to the background immediately (i.e. if you run the above in another terminal, you'll get your prompt back immediately, not after vim is closed).

Looking at [this bug](https://bugzilla.gnome.org/show_bug.cgi?id=707899), apparently there's a `--disable-factory` version which was broken since a long time, and a rather new `--wait` option - can you try adding those (before the `-x`)? If neither of both helps, you'll need to use another terminal for that.

**Comment by JoshMcguigan** [comment]
Thanks for sharing this. Just wanted to mention this is working for me using `vim` with the following config:

`c.editor.command = ["gnome-terminal", "--wait", "--", "vim", "+call cursor({line}, {column})", "--", "{file}"]`
