### ISSUE TITLE
Using VPN give me different content

### ISSUE THREAD

**Issue by brorbw** [qutebrowser/qutebrowser#4139]
Im using VPN to access my universities network to get access to articles. But im unable to get it to work in qutebrowser, and quite frankly im baffled. This makes no sense.
Using chrome, accessing ACM i can download articles just fine. Using qutebrowser, i cant.

Here is an image of the same site, visited at the same time through the same VPN. Notice the field with `Full Text:`.
[https://imgur.com/a/VNgFAeI](https://imgur.com/a/VNgFAeI)

Im not entirely sure if this is an issue with qutebrowser or ACM, but its annoying as hell. Is qutebrowser getting flagged as a bot or something? This is far beyond my expertise.
```
qutebrowser v1.4.1
Git commit: 75d153d6d (2018-07-11 17:16:50 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)
```

**Comment by The-Compiler** [comment]
I have no clue what's going on either, but I doubt this is related to qutebrowser. Also note the page says "State Library in Aarhus" at the top of the page in Chrome, but not in qutebrowser.

Some stuff you could try:

- Make sure you have the same IP to the outside via https://ifconfig.co/ (though that should be the case)
- Try playing with the `content.headers.user_agent` setting
- Try with `--temp-basedir`
- Try with another QtWebEngine based browser such as [KDE Falkon](https://www.falkon.org/)

**Comment by brorbw** [comment]
The have the same external IP, which is the only thing access to ACM should be based on.

Im working on a mac and KDE is no supported (iirc).

**Comment by brorbw** [comment]
The user_agent field is empty by default. Is this purposefully?

**Comment by The-Compiler** [comment]
Can you try with [QupZilla](https://qupzilla.com/download#mac) then? It's the predecessor of Falkon, so it might be a bit outdated, but still useful to test.

An empty user agent just sends the backend's default. You can check e.g. http://httpbin.org/headers to get the actual value.

**Comment by brorbw** [comment]
Now it works, and i think i've figured out why. 

Im not sure about the caching in qutebrowser, but it could be that the session doesn't change even though the connection has changed?


If I turn my VPN on, and open the browser and then the page. It works, if i turn off the VPN, and refreshes - it shows the exact same page.
If I open the browser and then the page, and then turn on the VPN, it does not show the state library in aarhus in the top.

**Comment by brorbw** [comment]
FYI turning the VPN on and off in google works perfectly.

**Comment by The-Compiler** [comment]
Depends on what the website does exactly. Cookies are entirely handled by QtWebEngine (which is based on Chromium) though, so there isn't much qutebrowser can do here. No idea what the culprit is precisely...

**Comment by brorbw** [comment]
I would reopen this issue

**Comment by The-Compiler** [comment]
Like I said, there's nothing qutebrowser can do here - it does not handle cookies or sessions at all. Not sure what's happening exactly (could be existing cookies if you don't get the same behavior with `--temp-basedir`, could be the older Chromium QtWebEngine relies on, could be something the website does differently).

**Comment by brorbw** [comment]
At first i thought that it worked with `--temp-basedir` but it works just as bad.

**Comment by jgkamat** [comment]
Bror Winther writes:

> using a --temp-basedir, worked - this however to not a usefull solution.
> I have something in my setup that is breaking this. Any suggestions on how to debug?

> Now it works, and i think i've figured out why.
>
> Im not sure about the caching in qutebrowser, but it could be that the session doesn't change even though the connection has changed?
>
> If I turn my VPN on, and open the browser and then the page. It works, if i turn off the VPN, and refreshes - it shows the exact same page.
> If I open the browser and then the page, and then turn on the VPN, it does not show the state library in aarhus in the top.

> FYI turning the VPN on and off in google works perfectly.

> At first i thought that it worked with --temp-basedir but it works just as bad.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Going back and forth on these things makes it really hard to debug anything
(especially since we cannot visit the site ourselves).

I would recommend you ask your uni how exactly they control access. If it is
by external IP, using the VPN should suffice, but you shouldn't get access
after turning the VPN off (as 'google' seems to do for you?)

If it is by cookies, you should check content.cookies.accept. If it is by
cookies, then the VPN shouldn't matter.

Most likely they are doing some really weird thing for authentication on their
side, since it seems to be flipping on and off for you at random. It probably
only works in chrome as that's the only place where they're testing it (and
probably even changing some settings in chrome would show the same behavior as
qb).

As The-Compiler says, qb does not control your external IP, cookies, or local
storage (it just passes the settings to qtwebengine). It's very hard for us to
do anything to fix this unless you make a minimal reliable reproduction we can
test on ourselves, from our point of view, there's nothing we can do until we
can debug the problem ourselves.

Looking at the layout of the site, there seems to be a 'sign in' link at the
top right. Are you sure you're not supposed to use that to login? Maybe you
signed in a long time ago in chrome, and that's why it's working over there.
There even is a 'Sign in via your Institution' link on the page.
