### ISSUE TITLE
Can't play video in fullscreen in adobe flash player.

### ISSUE THREAD

**Issue by supremew** [qutebrowser/qutebrowser#4175]
example:
1. I can't play the video in fullscreen in adobe flash player, "http://movie.le.com/izt/2018jmzb/index.html"
2. can't play video in the "http:youku.com", the reason is likely it can't get the right video url address.

[1.txt](https://github.com/qutebrowser/qutebrowser/files/2335229/1.txt)

**Comment by The-Compiler** [comment]
> I can't play the video in fullscreen in adobe flash player

QtWebEngine does [not support Flash fullscreen](https://bugreports.qt.io/browse/QTBUG-51306), and since [Flash is going away soon](https://www.chromium.org/flash-roadmap) this probably won't change.

> can't play video in the "http:youku.com", the reason is likely it can't get the right video url address.

I see the same behavior (redirecting to a 404 page) in Chromium, so it's probably the page's fault.
