### ISSUE TITLE
Use URL patterns for content.host_blocking.whitelist

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4179]
For historical reasons, the `content.host_blocking.whitelist` setting uses [fnmatch](https://docs.python.org/3/library/fnmatch.html) (see `is_whitelisted_host` in `browser/adblock.py`).

Now that we have [URL patterns](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/utils/urlmatch.py), it should use those instead.

**Comment by The-Compiler** [comment]
@sumit9696 Nobody has worked on this yet, and it should be a good newcomer issue - so please do, and feel free to ask if you need help!

**Comment by sumit9696** [comment]
Ok.. Thanks...

**Comment by toofar** [comment]
This should probably build on top of https://github.com/qutebrowser/qutebrowser/pull/4181/commits/7fb222464000de15dac945b40712615fd546d9c3 so that custom validation of the patterns doesn't need to be done.
The `config.val.content.host_blocking.whitelist` 
The whitelist check is here https://github.com/qutebrowser/qutebrowser/blob/25c189d8d469b123a9284847e48f4cbfc5a2fa0b/qutebrowser/browser/adblock.py#L71 and apart from the validiation that'll have to be changed to be something like `urlmatch.UrlPattern(pattern).matches(url)`, and the caller noods to be modified to pass in the whole url instead of just the host.
That way people can block whole domains and whitelist individual pages.

**Comment by hseg** [comment]
This patch breaks patterns using `?` -- `urlmatch.UrlPattern` considers that to be the start of a query string.
I'm using such patterns as `'w?.web.whatsapp.com'` -- I prefer to avoid overbroad whitelists if possible.

**Comment by The-Compiler** [comment]
That's unfortunate, but not something I consider important enough to have two different pattern syntaxes - sorry.

**Comment by hseg** [comment]
OK, but then the documentation for `host_blocking.whitelist` should be updated to match.

**Comment by hseg** [comment]
> OK, but then the documentation for `host_blocking.whitelist` should be updated to match.

... As it has been -- my `config.py` just ossified the old docs. Sorry for the noise.
