### ISSUE TITLE
Support URL patterns in custom adblock lists

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4188]
Until we get around to #29, we could at least support adding URL patterns to `~/.config/qutebrowser/blocked-hosts` for some more custom blocking flexibility. Probably shouldn't accept pattern for normal (downloaded) adblock lists though as it's not a common format.

**Comment by Entebate** [comment]
I made a quick and dirty modification to `adblock.py`. My original intent was to block lower subdomains, so that an entry `c.d` in the host block file would also block `b.c.d`, `a.b.c.d`, etc. This is a key feature to block trackers. For example, `googleusercontent.com` is in my blocking list, but the tracker shows up as, `lh3.`, `lh4.` and `lh5.googleusercontent.com` (as Firefox tracker blocking detects) and Qutebrowser will not block them. The same if the tracker is preceded by `www.` and if the blocked entry on the file lacks the `www.`.

Since this feature was not implemented yet, I decided to give it a try.

However, my solution will block `bc.d` also for an entry `c.d`. That _usually_ should not be a problem, but might happen to block a legitimate non-tracking domain. I found no problem in ~1 week of testing, and although the modified code is probably redundant and not much efficient (as you may see), I couldn't detect any performance issue. So I decided to share my new `adblockmodified.py` (you can compare it with the original `adblockoriginal.py`), which basically consists just of the extra function that performs the match, in the attached zip file.

[adblock.zip](https://github.com/qutebrowser/qutebrowser/files/4690005/adblock.zip)

**Comment by amacfie** [comment]
Closable due to https://github.com/qutebrowser/qutebrowser/pull/5317?

**Comment by The-Compiler** [comment]
Yeah, I guess this isn't needed anymore - thanks!
