### ISSUE TITLE
Qt 5.12: Uncaught TypeError: Cannot read property 'namespaceURI' of null

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4244]
```
[876:876:0923/225225.713466:INFO:CONSOLE(65)] "Uncaught TypeError: Cannot read property 'namespaceURI' of null", source: userscript:_qute_stylesheet_creation (65)
```

~~Probably~~ also happens in the tests: https://github.com/qutebrowser/qutebrowser/issues/4025#issuecomment-400629755, ~~but can't check that thanks to #4243.~~

But also when just running qutebrowser with `--temp-basedir`.

**Comment by shayneoneill** [comment]
Fun fact. Theres not a single instance on google anywhere of a git issue with "Cannot read property x of null" where theres an answer :/

**Comment by toofar** [comment]
In this case the error is from javascript and isn't Qt specific. I'm pretty sure it is from [this line](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/javascript/stylesheet.js#L56) because `document.documentElement` is `null` due to the script getting injected into the page before the DOM is initialized. The script is written that way because it used to be injected after the DOM was initialised, in the Qt 5.12 release webengine started etheir injecting scripts that wanted to run at document-start earlier or started initialising the DOM later (or maybe it was chromium or some complicated interrelation that changed).
