### ISSUE TITLE
Add setting to allow navigation in pinned tabs

### ISSUE THREAD

**Issue by giann** [qutebrowser/qutebrowser#4400]
I should be able to open any url in a pinned tab as long as it's on the same domain.

**Comment by mschilli87** [comment]
I actually prefer the current behaviour.

**Comment by giann** [comment]
Or maybe introduce a different type of pin: pin url vs pin a tab.
In one you are explicitly saying "i want this tab to stay on this url", in the other you just want to pin a tab regardless of its current url.

**Comment by jgkamat** [comment]
Benoit Giannangeli writes:

> Or maybe introduce a different type of pin: pin url vs pin a tab.
> In one you are explicitly saying "i want this tab to stay on this url", in the other you just want to pin a tab regardless of its current url.

Would a global "pinned.tab.frozen" setting defaulting to true work for you? I
think that would be the simplest way to implement this. Having two commands
would be a lot of work for (I'm assuming) not a lot of people's benefit, and
can lead to confusion.

Ie: you want pinned tabs for their shrinking alone right?

**Comment by giann** [comment]
Yes a flag like that would be great.

**Comment by jgkamat** [comment]
The code for this is in browser/commands.py:openurl, and I think it should be
fairly trivial (maybe even with a third setting for allowing only same domain,
but simpler is better). If no one takes it, I'll do it at some point.

>                 curtab = self._cntwidget(count)
>                 if curtab is None:
>                     if count is None:
>                         # We want to open a URL in the current tab, but none
>                         # exists yet.
>                         self._tabbed_browser.tabopen(cur_url)
>                     else:
>                         # Explicit count with a tab that doesn't exist.
>                         return
>                 elif curtab.data.pinned:
>                     message.info("Tab is pinned!")
>                 else:
>                     curtab.openurl(cur_url)

**Comment by beelzebielsk** [comment]
I'd be interested in taking this on. I haven't contributed to qutebrowser before, but I'm interested in doing so.

**Comment by jgkamat** [comment]
Adam Ibrahim writes:

> I'd be interested in taking this on. I haven't contributed to qutebrowser before, but I'm interested in doing so.

This is definitely a good starter task (especially without a third per-url
flag).

The code to block navigation on :open in pinned tabs is here, and should be
pretty trivial to modify once you have a config value:

https://github.com/qutebrowser/qutebrowser/blob/060489f1bc5b5a6529bd8e78d80449a4b06dd568/qutebrowser/browser/commands.py#L320

Here's an example of a setting, you should be able to add another one by using
the same formula. If you want to tackle a same-domain setting, you'll need to
make it a string instead of a bool though.

https://github.com/qutebrowser/qutebrowser/blob/060489f1bc5b5a6529bd8e78d80449a4b06dd568/qutebrowser/config/configdata.yml#L1766

Lastly, there are a couple other places where navigation is blocked due to
pinned status. Maybe we can take this opportunity to make some sort of
'navigation_blocked' method so if we want to keep adding new features we only
need to change one place.

https://github.com/qutebrowser/qutebrowser/blob/cbb6ae860c156f061beb4fa597db895983eab440/qutebrowser/components/misccommands.py#L122

Feel free to ask on freenode if you have any questions :)
