### ISSUE TITLE
[macOS] Support Mojave Dark Mode

### ISSUE THREAD

**Issue by koekeishiya** [qutebrowser/qutebrowser#4430]
With #4067 out of reach, I was wondering if it would be possible to support the new Dark Mode (titlebar) introduced in macOS Mojave?

**Comment by The-Compiler** [comment]
From what I gather from [this blog post](https://blog.qt.io/blog/2018/11/08/qt-macos-10-14-mojave/) and [this documentation](http://doc-snapshots.qt.io/qt5-5.12/macos.html) (and also [this Apple article](https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app)), whether dark mode is on by default depends on the XCode version being used. Since qutebrowser currently still supports El Capitan (and will still support Sierra for a while, even when dropping that soon), that's out of the question.

However, apparently it's possible to add this to `Info.plist`:

```xml
<key>NSRequiresAquaSystemAppearance</key>
<string>False</string>
```

Can you please try that (by browsing the `.app` and editing its `Info.plist`) and report back how qutebrowser behaves?

**Comment by koekeishiya** [comment]
That worked! Thanks for the quick reply as always.

**Comment by The-Compiler** [comment]
And qutebrowser still behaves nicely, including UI like the completion or the `:report` dialog? If so, I'll include that key by default.

**Comment by koekeishiya** [comment]
Ah right, so the text in the `:report` dialog is now invisible, as the window is darkish, but the text-field and text-color are both white.

Other parts of the UI seems to work fine though (but that might just be because I've set custom colors for most of the UI). Either way, I can live with that and report back if I notice other anomalities.
This was rather simple to enable/disable as well, so you could probably hold off adding it by default for now.

**Comment by The-Compiler** [comment]
I guess let's wait until Qt 5.12 gets released and see how things look there. Thanks for being my guinea pig :laughing:

**Comment by The-Compiler** [comment]
@koekeishiya Can you please try qutebrowser v1.6.0 (released today) without any modification to `Info.plist`?

**Comment by koekeishiya** [comment]
Without modification to the .plist file, v1.6.0 still uses the default "light" appearance.

**Comment by koekeishiya** [comment]
Tested this in v1.6.3. Same result as in v1.6.0.

**Comment by The-Compiler** [comment]
Related PyInstaller issues:

https://github.com/pyinstaller/pyinstaller/issues/4627
https://github.com/pyinstaller/pyinstaller/issues/4627

**Comment by The-Compiler** [comment]
Looks like everything is working properly with recent-ish Qt and PyInstaller versions, so I'm now (finally) setting that by default.
