### ISSUE TITLE
Pages overscroll on OS X

### ISSUE THREAD

**Issue by Equidamoid** [qutebrowser/qutebrowser#4500]
**Version info (see `:version`)**:
yesterday's master (4b0d1b394)
pyqt 5.11.3

**Description**
Pages overscroll (think of "pull down to refresh" thing in mobile apps) a lot on osx.

**How to reproduce**
 - Run qutebrowser on OS X
 - Open any page
 - Scroll to the top
 - Continue scrolling
 
Expected: nothing happens
Actual: the page files down, sometimes all the way to the bottom of the screen and slooowly comes back.

**Notes**
Happens also for scrolling down and even left-right
I have a feeling that this is a qtwebengine featurebug, but can't find anything in the docs.

**Comment by jgkamat** [comment]
Since mac os is responsible for adding those to applications, wouldnt this be a bug in mac os? I dont think individual application developers are adding overscroll just for mac os.

On December 30, 2018 2:50:31 AM PST, Equidamoid <notifications@github.com> wrote:
>**Version info (see `:version`)**:
>yesterday's master (4b0d1b394)
>pyqt 5.11.3
>
>**Description**
>Pages overscroll (think of "pull down to refresh" thing in mobile apps)
>a lot on osx.
>
>**How to reproduce**
> - Run qutebrowser on OS X
> - Open any page
> - Scroll to the top
> - Continue scrolling
> 
>Expected: nothing happens
>Actual: the page files down, sometimes all the way to the bottom of the
>screen and slooowly comes back.
>
>**Notes**
>Happens also for scrolling down and even left-right
>I have a feeling that this is a qtwebengine featurebug, but can't find
>anything in the docs.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Equidamoid** [comment]
@jgkamat, 
> mac os is responsible for adding those to applications

I doubt it. OS can't know enough of inner workings of particular application to do such complex distorion of a window. I'd say it's the job of UI framework. 
Out of curiosity I checked some applications for scrolling behavior:
 - "Apple things", using Cocoa (or how is it called now?..): overscroll is present, recovers much quicker than in qutebrowser
 - Some other apps, mostly crossplatform (darktable, pycharm, firefox 52, HOMM3 in wine ;), no overscroll at all
 - Qt Designer (as a separate bullet since it uses the same Qt version as qutebrowser) - no overscroll

Again, I think it's a weird behaviour of qt webengine. I'll try to reproduce it with a small demo app...
The question the is if it is possible to disable it in qutebrowser.

**Comment by mentalisttraceur** [comment]
@The-Compiler I recommend keeping this open until there's some way to make the overscroll go away. I still see this on MacOS and it's particularly unpleasant when everything is in dark mode because the fill color for the overscroll is _white_.

For that matter, is there at least a way to change that overscroll fill color?

**Comment by The-Compiler** [comment]
There's no point in having an issue open for something that isn't actionable from qutebrowser's side. I have no idea where exactly the animation is coming from in QtWebEngine/Chromium, but if there's seemingly no way to disable it, I doubt there's a way to change its color.

**Comment by mentalisttraceur** [comment]
@The-Compiler You can trivially change its color with user CSS, but there are problems, so I think there's a good chance there's way to do it better from within Qutebrowser code.

For example, when I add this to my `content.user_stylesheets` file:

```css
html
{
    background: #000000;
}
```

the overscroll void is solid black instead of solid white - it's just that this is not a workable solution because

1. it usually also blackens the page itself, not just the overscroll void, and
2. it interacts badly with `colors.webpage.darkmode.enabled`, because some other elements end up inheriting the background color.

Also, on pages which do things fully right, like GitHub, the overscroll void is the same color as the background.

My primary guess right now is that the algorithm behind `colors.webpage.darkmode.enabled` is not coloring the HTML background (perhaps it's only coloring the `<body>` and below in the HTML). Is that something Qutebrowser has any say in?

**Comment by The-Compiler** [comment]
> so I think there's a good chance there's way to do it better from within Qutebrowser code.

Ok, you tell me where then. The only way I'm aware of how qutebrowser can influence a page's background color is already exposed as a setting (`colors.webpage.bg`).

> Is that something Qutebrowser has any say in?

No, the dark mode is entirely coming from the underlying Chromium.

**Comment by mentalisttraceur** [comment]
> > so I think there's a good chance there's way to do it better from within Qutebrowser code.
>
> Ok, you tell me where then. The only way I'm aware of how qutebrowser can influence a page's background color is already exposed as a setting (`colors.webpage.bg`).

@The-Compiler I haven't been able to find a way either, but I'm not nearly as familiar with the Qt APIs as you.

I was just saying that

1. CSS in the file specified by `content.user_stylesheets` is a way to change its color, since you said "I doubt there's a way to change its color", and

2. since you seemingly didn't mention user stylesheets being a way to do it, and since you seem like a good maintainer who wants to be helpful to your users, I was forced to think that you didn't know user stylesheets could color the overscroll void, which suggested that your own search for a solution was not exhaustive... and since user stylesheets was one of the first things I tried, to me that suggested a good chance that something else might've been missed as well (_at the time_ - your latest reply obviously brings down the odds of that, since now I can see that even if you didn't know about the user stylesheet way to change its color before, right after it being mentioned you're still seemingly confident that there's no good way to do it from within Qutebrowser, and very much I trust your familiarity with the relevant APIs).

**Comment by mentalisttraceur** [comment]
For anyone experiencing the same problem and looking for a "good enough" solution, the best I got so far is to add this to my user CSS:

```
html
{
    background: #333333;
}
```

`#333333` is dark enough to not flash-bang my eyes when I inevitably accidentally trigger the overscroll, and I haven't yet seen it cause the weird color-inversion issues I was seeing when trying to use `#000000`.

**Comment by mentalisttraceur** [comment]
I've just confirmed that this overscroll white void issue also happens in Google Chrome itself (version 91.0.4472.164 to be exact).

Maybe this was already known? But I didn't note it explicitly mentioned in this issue discussion so far.

So now I'm assuming this is a problem all the way down in the Chrome/Chromium web engine itself, not even in Qt like was suggested above. If so, then you're right - the proper thing for Qutebrowser to do about this is to just do nothing and wait until it is solved in Chrome/Chromium, and I take back my recommendation to keep this issue open.

**Comment by anordhoff** [comment]
Adding the following css to my `content.user_stylesheets` disabled the rubber band effect on Catalina:

```
body {
    overscroll-behavior-x: none;
    overscroll-behavior-y: none;
}
```

https://stackoverflow.com/a/47686467

**Comment by mentalisttraceur** [comment]
@anordhoff Interesting, and I'm glad to hear that. I am pretty sure I tried overscroll-behavior before it didn't work for me, but maybe I just did it on a website where it didn't work, or maybe it took a newer version of WebEngine.
