### ISSUE TITLE
using imports on user_stylesheets file

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#4527]
Hello,
I'm sorry if this is a bit off, I'm trying to set `content.user_stylesheets` with a file that imports `pywal`'s colors, like:

```
@import url('file:///home/aleprovencio/.cache/wal/colors.css');

body {
  background-color: var(--color0) !important;
  color: var(--color12) !important;
}
```

However, the file does not seem to read the variables defined on `pywal`'s generated file.

What's wrong with this, please help?

**Comment by toofar** [comment]
Are you getting `Not allowed to load local resource: file:///home/aleprovencio/.cache/wal/colors.css` in the web inspector console? So did i when I tested it. Hosting it on an HTTP URL and pointing the import statement to that works just fine though.

**Comment by aleprovencio** [comment]
Yes @toofar, I get that message too..
Did your intend to import a pywal file as well?

**Comment by toofar** [comment]
Yes I just copied your example. That message is expected because the stylesheets are injected in a non-privileged way so they look like stuff the page is doing and you don't want webpages loading up your local files, usually.
I'm going to close this issue now because we are not going to support importing from `file://` URLs, using an `http://` or `https://` URL works fine. So you can host it somewhere or just remove the import and copy the color definitions into the same file.

**Comment by The-Compiler** [comment]
Hmm, I suppose qutebrowser could read such import statements and replace them by the files contents before applying the stylesheet? If we only support a subset of `@import` (only file URLs, no media declaration) that shouldn't be too hard hopefully?
