### ISSUE TITLE
after_load_hook is very expensive

### ISSUE THREAD

**Issue by Mstrodl** [qutebrowser/qutebrowser#4535]
**Version info (see `:version`)**:
v1.5.2

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes

**Description**
Changing the page URL using `window.location` or the history API blocks for some reason. It makes pages which change the URL frequently perform badly.

**How to reproduce**

```js
setInterval(()=>location.hash=Math.random(), 100)
```

**Comment by toofar** [comment]
I'm not convinced it is blocking, as opposed to lots of work being triggered as a result of the URL changing. In particular writing out to the autosave file each time. I tried it with with your example aund couldn't even scroll the page, I replaced `save_autosave()` with a stub and then it was just janky, instead of essentially frozen. Doing less expensive work on URL changes should be something we keep in mind but this might be made a non-issue by #4087. Could you try reproducing with a basedir in a ramdisk?

**Comment by Mstrodl** [comment]
@toofar Well, the page is unable to do any other work while waiting on the location to be set so it seems blocking to me. Something like a file upload even suffers while location is being updated.

**Comment by Mstrodl** [comment]
@toofar Using `/tmp` as a basedir seems to make it a lot less noticeable
