### ISSUE TITLE
rl-unix-filename-rubout halts at spaces

### ISSUE THREAD

**Issue by JadElClemens** [qutebrowser/qutebrowser#4561]
As far as I can tell there's no legitimate use for the space character as a filesystem delimiter, so having rl-unix-filename-rubout ignore spaces would be ideal imo.

I currently have rl-unix-filename-rubout bound to C-h in prompt mode to emulate helm/ivy file selection behavior, but if a folder has spaces in its name I have to press it multiple times to actually erase to the previous forward slash. Perhaps this behavior is expected (I have limited experience working with readline) but it would be nice to at least have a flag to ignore spaces/whitespace characters.

**Comment by jgkamat** [comment]
JadElClemens writes:

> I currently have rl-unix-filename-rubout bound to C-h in prompt mode to emulate helm/ivy file selection behavior, but if a folder has spaces in its name I have to press it multiple times to actually erase to the previous forward slash. Perhaps this behavior is expected (I have limited experience working with readline) but it would be nice to have a flag to ignore spaces/whitespace characters.

Currently rl-unix-filename-rubout does stop at spaces. I think a flag to
provide this behavior would be useful though.

I have been thinking on how to get an ivy-like experience in qutebrowser. I
think it would require an operator that deletes one char until it gets to a
slash, and then deletes backwards until the next slash.

Also, we need to think what should be done in commands, ie: ':open a b c'. I
would think that in that case, spaces should matter, while in paths, it
shouldn't.

Simply ignoring spaces as boundaries should be fairly easy though, see this PR
for locations:

https://github.com/qutebrowser/qutebrowser/pull/1715/files

**Comment by The-Compiler** [comment]
I ended up adding two new commands in ab65c542a0551abf105eeb58803cd08bd040753b:

- `:rl-rubout <chars>`, which can be used as `:rl-rubout " "` to replace `:rl-unix-word-rubout` (now deprecated) and `:rl-rubout " /"` to get the old `:rl-unix-filename-rubout` behavior (ditto)
- `:rl-filename-rubout` which is a "better" way of going up a file path: It doesn't consider spaces as a separator, and it uses the OS-specific path separator (i.e. `\` on Windows)

While writing tests for those, I noticed a bug causing e.g. `path_with_no_slashes` to be changed to `p` rather than deleted entirely. That is now fixed in 1af602b258b97aaba69d2585ed499d95e2303ac2. It took me a while to understand the code (I added some ascii drawings hopefully helping for next time), so I'd appreciate if @edi9999 (originally implementing it in 9e1c7e011707b63a878caa9be589da7c5a6908ec) and/or @rcorre (changing it in 9e1c7e011707b63a878caa9be589da7c5a6908ec) could take a quick look to double-check I didn't miss anything.

**Comment by rcorre** [comment]
> @edi9999 (originally implementing it in https://github.com/qutebrowser/qutebrowser/commit/9e1c7e011707b63a878caa9be589da7c5a6908ec) and/or @rcorre (changing it in https://github.com/qutebrowser/qutebrowser/commit/9e1c7e011707b63a878caa9be589da7c5a6908ec) could take a quick look to double-check I didn't miss anything.

I think you posted the same commit both times :)

**Comment by The-Compiler** [comment]
@rcorre Whoops! I meant a086095954b973b86398a4013344ba3afa760038, fixed!
