### ISSUE TITLE
window._qutebrowser unavailable with JS disabled on qutebrowser.org

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4633]
With `./.tox/py37-pyqt512/bin/python3 -m qutebrowser --temp-basedir  --debug -s content.javascript.enabled false qutebrowser.org`:

```
13:08:51 DEBUG    commands   command:run:534 command called: hint
[...]
13:08:51 DEBUG    js         shared:javascript_log_message:146 [http://qutebrowser.org/:2] Uncaught TypeError: Cannot read property 'find_css' of undefined
13:08:51 DEBUG    message    message:_log_stack:41 Stack for error message:
  [...]
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginetab.py", line 610, in _js_cb_multiple
    error_cb(webelem.Error("Unknown error while getting "
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/hints.py", line 744, in <lambda>
    error_cb=lambda err: message.error(str(err)),
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/message.py", line 53, in error
    stack = ''.join(traceback.format_stack())
13:08:51 ERROR    message    message:error:58 Unknown error while getting elements
```

Works on 5.11.

**Comment by toofar** [comment]
There are two things going on here.

1. Shadowing of global variables by DOM elements.

I wasn't are this was a thing previously but if you have an element in a page like `<h2 id="_qutebrowser">qutebrowser</h2>` then `window._qutebrowser` will return the `HTMLElement`. In the global wrapper for internal injected scripts there is a `if (!("_qutebrowser" in window))` check which will be true in that case. We could change the qutebrowser.org source but then other people could still do it (the scripts run in a different JS world than the page JS so we don't have to worry about shadowing from that front). `typeof someHTMLElement` still returns `"object"` which is not helpful. [Apperently](https://stackoverflow.com/a/7894320) the proper way to check an objects type is `Object.prototype.toString.call(t)`. So this patch will fix it:
```javascript
diff --git i/qutebrowser/javascript/global_wrapper.js w/qutebrowser/javascript/global_wrapper.js
index a302bd5d1516..7ce96ce49b47 100644
--- i/qutebrowser/javascript/global_wrapper.js
+++ w/qutebrowser/javascript/global_wrapper.js
@@ -1,6 +1,10 @@
 (function() {
     "use strict";
-    if (!("_qutebrowser" in window)) {
+    if (
+      !("_qutebrowser" in window) ||
+      Object.prototype.toString.call(window._qutebrowser) !== '[object Object]')
+    {
         window._qutebrowser = {"initialized": {}};
     }
 
```

2. `QWebEngineScript.DocumentCreation` not running if JS is disabled

That above behaviour didn't change with 5.12, it was being avoided because we were injecting the scripts at both DocumentCreation and DocumentReady (as a workaround for [QTBUG-66011](https://bugreports.qt.io/browse/QTBUG-66011)). With 5.12 the DocumentCreation script is no longer running when JS is disabled, with JS enabled that script was creating the proper `window._qutebrowser` object before the DOM had been parsed (or something like that).
The [docs](https://doc.qt.io/qt-5/qwebenginesettings.html#WebAttribute-enum) say that the javascript enabled setting **Enables the running of JavaScript programs in the MainWorld.** This should not block scripts from running in non-main JS worlds. I expect it changed as a side effect of the fix for QTBUG-66011 which changed DocumentCreation scripts to run after `DidClearWindowObject` fires. Presumably that overriden method only gets called when it relates to the main world for some reason.

**Comment by The-Compiler** [comment]
Thanks for the great analysis, @toofar! I applied that fix.

**Comment by The-Compiler** [comment]
Qt fix: https://codereview.qt-project.org/#/c/258039/
