### ISSUE TITLE
Poor performance when more than one instance on Wayland

### ISSUE THREAD

**Issue by gabm** [qutebrowser/qutebrowser#4692]
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/d59c7e2f

**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

I am using qutebrowser with `tabs_are_windows` on Sway Wayland, so I dont use the tabs from qutebrowser but instead switch Sway into tabbing mode. When one of the windows that is currently not shown is busy (for example loading a page) then the currently visible window becomes practically unusable for me :/ it is very laggy and its almost impossible to enter any commands. This behavior started around 2 months ago. I am running arch linux, so I cannot isolate anymore, which update caused the behavior..

I was searching the web for information but didnt find any - I am almost sure its not qutebrowsers fault, but rather some kind of sway/wayland vs. qt5 thing. Unfortunately I am not really sure what to do anymore, its driving me crazy ... Maybe you have some ideas on how to approach this kind of situation?

**How to reproduce**

-

**Comment by The-Compiler** [comment]
Most likely [QTBUG-69077](https://bugreports.qt.io/browse/QTBUG-69077)

**Comment by gabm** [comment]
oh yes, thank you - looks very much like it.. lets hope they come up with a fix... thanks :+1:

**Comment by The-Compiler** [comment]
There was a [fix](https://codereview.qt-project.org/#/c/245665/) for this, but it was [reverted](https://codereview.qt-project.org/#/c/249346/) because it caused a [different issue](https://bugreports.qt.io/browse/QTBUG-72578). There's now a [second fix](https://codereview.qt-project.org/#/c/251380/) in the works.

If you want a workaround, I guess you could try applying the WIP fix and rebuilding the QtWayland package, or run qutebrowser under XWayland FWIW.

**Comment by The-Compiler** [comment]
FWIW looks like the fix now got [merged](https://codereview.qt-project.org/#/c/251380/) for Qt 5.12.4.

**Comment by gabm** [comment]
thats very good news, thank you!
