### ISSUE TITLE
Consider better data structures for bindings

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4721]
e.g. a trie - from #4652 by @user202729:

> @The-Compiler Regarding the problem you mentioned: I implemented trie data structure for keybindings (https://paste.the-compiler.org/view/c15f385c), however the implementation is incomplete:
> 
> * Partial key sequence suggestion or config bind/unbind (`on_config_changed`) still traverse the whole dict.
> * `update` method is not implemented (although this one is easy to implement, just loop over all items)

**Comment by jgkamat** [comment]
Note that this approach will have some extra cost when adding bindings (eg:
when hinting, the hint mode dict is rewritten on the fly). I don't think that
will outweigh the improvements from not iterating over everything though (even
in hint mode).

Another approach I thought of (which is sloppier than a trie but maybe easier)
is to just add every combination leading to a complete key to the binding. Eg:
'abc' would store 'a->partial, ab->partial, abc->complete' in a dict. A trie
is better and cleaner though, in my opinion (wouldn't waste a bunch of space,
although it might be a bit slower).

**Comment by user202729** [comment]
@jgkamat Why would adding bindings have extra cost? If implemented correctly it's only necessary to traverse the trie, which has time complexity == sequence length, which is about as good as it can get.

**Comment by jgkamat** [comment]
user202729 writes:

> @jgkamat Why would adding bindings have extra cost? If implemented correctly it's only necessary to traverse the trie, which has time complexity == sequence length, which is about as good as it can get.

If I understood the old logic correctly, the old logic had an insertion cost
scaling with the only the number of bindings, while a trie will be the key
sequence length * number of bindings (just looking at time complexity alone).
If, for example, there was some logic that inserted extremely long bindings
repeatedly, it will probably get slower.

Of course, the lookup cost will probably be so dramatically better that it
won't matter at all.

**Comment by user202729** [comment]
@jgkamat 

* Actually, I think the old logic is also key sequence length * number of bindings, because hash takes linear time. Try this:

```
>>> class a:
...  def __hash__(self):
...   print('h')
...   return 1
... 
>>> x=a()
>>> hash(x)
h
1
>>> hash(x)
h
1
```

* Ideally, there should be some way for the config system to notify the key parser exactly which one is bound/unbound so that the key parser only have to update that one, in that case both would takes (amortized) time only (key sequence length).

**Comment by user202729** [comment]
@jgkamat Regarding your proposed alternative: it would need to store how many "complete" bindings may result in a "partial" binding, otherwise delete a binding would requires traversing the whole dict. (that is, assume the `config_updated`/`read_config` logic is updated so that it won't just delete and rebuild the whole dict)
