### ISSUE TITLE
'Too late to register scheme "qute"' when restore from fatal crash

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#4804]
**Version info (see `:version`)**:

Latest master.

**Does the bug happen if you start with `--temp-basedir`?**:

Obviously not, because of restart.

**Description**

The following warning messages are printed when restoring from a fatal crash:

```
12:39:20 WARNING: QWebEngineUrlScheme::registerScheme: Too late to register scheme "qute"
12:39:20 WARNING: Please register the custom scheme 'qute' via QWebEngineUrlScheme::registerScheme() before installing the custom scheme handler.
12:39:20 WARNING: Please register the custom scheme 'qute' via QWebEngineUrlScheme::registerScheme() before installing the custom scheme handler.
```

**How to reproduce**

1. `:crash segfault`
2. Reopen qutebrowser in a terminal

**Comment by user202729** [comment]
By the way, I think that the current way to call init functions are error-prone (you have to make sure that they're called in correct order, and each one is only called once)

This should be a better way to do that:

```
#!/bin/python

def call_once(func):
	called = False
	def wrapper():
		nonlocal called
		if called:
			return
		func()
		called = True
	return wrapper


# then wrap all init functions in call_once
@call_once
def init():
	print(1)


# functions/init functions would call the init functions it depends on
# note that there must not be circular dependency (there should not be anyway)
def a():
	init()

def b():
	init()

class C():
	def __init__(self):
		init()

a()
b()
C()
```

There might be a small (O(1) per function call) overhead if the option above is used. If that's significant it's possible to look at performance improvement later.

**Comment by toofar** [comment]
Interestingly pages like qute://version and qute://settings still work in this case.
The issue appears to be with something the crash dialog is doing, either in its information gathering or just because it makes some widgets. I don't see any reason why that call can't move a little later. Also the message says it is initializing the crashlog module but that actually gets done in `run()`.

```diff
diff --git i/qutebrowser/app.py w/qutebrowser/app.py
index 1f6d5c7ae4bc..db24092a2b48 100644
--- i/qutebrowser/app.py
+++ w/qutebrowser/app.py
@@ -459,16 +459,16 @@ def _init_modules(args, crash_handler):
     log.init.debug("Initializing command history...")
     cmdhistory.init()
 
-    log.init.debug("Initializing crashlog...")
-    if not args.no_err_windows:
-        crash_handler.handle_segfault()
-
     log.init.debug("Initializing sessions...")
     sessions.init(q_app)
 
     log.init.debug("Initializing websettings...")
     websettings.init(args)
 
+    log.init.debug("Handling any previous crashlogs...")
+    if not args.no_err_windows:
+        crash_handler.handle_segfault()
+
     log.init.debug("Initializing quickmarks...")
     quickmark_manager = urlmarks.QuickmarkManager(q_app)
     objreg.register('quickmark-manager', quickmark_manager)
```

**Comment by The-Compiler** [comment]
This happens because the crash dialog calls `version._chromium_version()` (indirectly) which creates a QWebEngineProfile.

I'd like to initialize it as early as possible - it doesn't only handle previous segfaults, it also sets up crash logging for segfaults. Moving it after initializing QWebEngineSettings (and thus QtWebEngine) would cause it to miss segfaults happening there.

Ideally, setting up logging of new crashes should be separate from handling a previous logfile, but that'd mean more complex handling of existing crash log files and such. I think I'd just remove the Chromium version from the segfault dialog instead.

As for refactoring the init process - I think getting rid of the objreg (#640) and instead passing the needed objects as arguments would make the dependencies much clearer. I'd like to avoid making the whole thing more complex than needed by calling init functions everywhere (and ignoring the calls).

**Comment by The-Compiler** [comment]
> Ideally, setting up logging of new crashes should be separate from handling a previous logfile, but that'd mean more complex handling of existing crash log files and such. I think I'd just remove the Chromium version from the segfault dialog instead.

Turns out splitting it apart was easier than I thought, so that's what I did.
