### ISSUE TITLE
Tawkto API script doesn't show up in the browser

### ISSUE THREAD

**Issue by cdmjr** [qutebrowser/qutebrowser#4831]
When I opened it in a mainstream browser (firefox), I get to see the widget, but when I open it in qutebrowser, I don't see it.

Here is the site. 

> https://www.tawk.to/

When you go to there using other browser, you will see a chat widget at the bottom left corner, but in qutebrowser, there's nothing.

**Comment by jgkamat** [comment]
cdmjr writes:

> When you go to there using other browser, you will see a chat widget at the 
> bottom left corner, but in qutebrowser, there's nothing.

I don't see any chat widget in the bottom left on any browser. In qutebrowser 
and firefox, I see a chat widget in the bottom right.

**Comment by The-Compiler** [comment]
This is due to `va.tawk.to` being part of the StevenBlack host blocklist. If you block that elsewhere (e.g. by adding `127.0.0.1 va.tawk.to` to `/etc/hosts`), you'll see the same result in all browsers.

I opened an issue requesting it to be unblocked here: https://github.com/FadeMind/hosts.extras/issues/24
