### ISSUE TITLE
a function for making qutebrowse free some ram

### ISSUE THREAD

**Issue by emanrdesu** [qutebrowser/qutebrowser#4856]
I think qutebrowser keeps past pages in ram in order for faster access or something, and that's fine, I just don't like having to restart the browser for it to clear up the past pages.
I notice I have 97% ram usage in my machine, with only 14 tabs opens, but then I simply restart it and it goes to 57% ram usage.

I propose a function that just does this "ram clearing" so I can keybind it and hence not have to restart the browser.

**Comment by jgkamat** [comment]
emanrdesu writes:

> I think qutebrowser keeps past pages in ram in order for faster access or 
> something, and that's fine, I just don't like having to restart the browser 
> for it to clear up the past pages.
> I notice I have 97% ram usage in my machine, with only 14 tabs opens, but 
> then I simply restart it and it goes to 57% ram usage.

Unfortunately, python programs in general tend to grow in size over time due 
to internal fragmentation, even if there is no leak. Unfortunately, the only 
way to fix this in python is to restart the process, or not use python.

There also might be some bugs in PyQt5 or harder to detect leaks, but in the 
few profiles I've done (which are very shallow level), about 15% of the memory 
we use in the python process is 'wasted' in this way on startup (and that will 
grow over time).

http://rushter.com/blog/python-garbage-collector/

**Comment by emanrdesu** [comment]
seems like python is a bad programming language then.
do other dynamic languages have this problem? e.g. (common lisp, ruby)

**Comment by jgkamat** [comment]
emanrdesu writes:

> do other dynamic languages have this problem? e.g. (common lisp, ruby)

I'm not so sure about those two, but I do know Java in particular handles 
memory allocation a lot better (especially if tuned). AFAIK, the problem is 
that python uses memory addresses to specify the 'id' function, and since the 
'id' can't change, the memory address can't change, which means that you can't 
move objects to compact the heap.

I would assume for common lisp it would depend heavily on the implementation, 
but on a long lived (months) application on sbcl I manage which allocates 
>10GB of data daily (with a tiny amount never freed), I have never seen the 
total usage go over 200mb.

**Comment by The-Compiler** [comment]
Huh, GitHub won't let me comment?

**Comment by The-Compiler** [comment]
@jgkamat How is that related to Python? In C you also couldn't just move stuff around on the heap... Also, from what we've seen so far, by far the biggest amount of RAM consumption doesn't seem to be caused by Python allocations, right?

Some related issues: #1476, #67/#4037 (not directly related though), #4616 (maybe the page lifecycle API will allow us to discard closed tabs more cleanly?).

**Comment by jgkamat** [comment]
Florian Bruhin writes:

> @jgkamat How is that related to Python? In C you also couldn't just move 
> stuff around on the heap...

Yah, C/C++ has this same problem. It's common for people to try different heap 
managers or tune their existing one to waste less memory like this. Python is 
weird though, because it suffers from the downsides of static memory 
allocation and downsides of gc (time spent managing memory, pauses) at the 
same time.

> Also, from what we've seen so far, by far the biggest amount of RAM 
> consumption doesn't seem to be caused by Python allocations, right?

We do have some evidence that Python code allocations are a very small part of 
memory usage, but we have little/no evidence that the interpreter itself isn't 
taking a large part of memory (especially on long-lived instances).
