### ISSUE TITLE
Proposal: Element blocking

### ISSUE THREAD

**Issue by IvanDelsinne** [qutebrowser/qutebrowser#4875]
There are lots of ads that simply cannot be blocked based on domain lists:

- base-64-encoded images
- ads served from the same website, on the same subdomain
- popups
- banners

On Firefox, but also most other major browsers, the uBlock origin extension allows to block entire DOM element trees (by kicking the root out of the document), or remove/disable CSS rules.

For CSS rules, custom user scripts can already sort-of manage that, but having a way to, in a way that's similar to uBo, block an entire DOM element, would be really neat.

I guess that this can be triggered past-DOM building (I don't know if there's a hook between the DOM document building and rendering, but that could be even put here to avoid having elements disappearing), loading a list of DOM selectors, and kicking out every found element.

**Comment by The-Compiler** [comment]
See #29 and https://gitlab.com/jgkamat/jhide

**Comment by IvanDelsinne** [comment]
Thanks for the link I couldn't find. Still, integrating it may come with huge performance improvements.

**Comment by The-Compiler** [comment]
qutebrowser can't interact with the DOM except via JavaScript, so there's no difference.

**Comment by jgkamat** [comment]
Ivan Delsinne writes:

> Thanks for the link I couldn't find. Still, integrating it may come with 
> huge performance improvements.

You can implement the same method as uBlock with greasemonkey (hot-loading 
relevant blocking css only when it's needed). Both methods have tradeoffs 
though, as you'll need to scan all new elements (and the dom when you first 
load) using this method, instead of letting the browser handle it. 
Unfortunately I'm pretty lazy, and there are much worse bottlenecks in 
qutebrowser on page loads.

> (by kicking the root out of the document)

uBlock dosen't "kick out" anything. It uses CSS rules as well.

http://www.github.com/uBlock-LLC/uBlock/issues/161
