### ISSUE TITLE
How currently use custom CSS styles?

### ISSUE THREAD

**Issue by banderlog** [qutebrowser/qutebrowser#4945]
Call me stupid, but I am failed to find any info about that in document or `:help` or even on duckduck.go.  Most relevant thing I was able to find is `content.user_stylesheets` options in settings, which should be some list of paths (absolute or relative to config dir). But what files should be in that list, in which form, why css files from userscripts.org does not work? Also there are plenty of Issues with 'CSS' in their title.

Could someone give an example of working css style and brief description of what features are working now compare to stylish (as a de facto standard)

**Comment by The-Compiler** [comment]
Those should be CSS files, simple as that :wink: userscripts.org has Greasemonkey userscripts (which belong in `~/.local/share/qutebrowser/greasemonkey`), not CSS files.

The main thing which doesn't work is setting a stylesheet for a given page instead of globally, see #3636 for that.

An example stylesheet some people (including me) use is https://github.com/alphapapa/solarized-everything-css/
