### ISSUE TITLE
project name feels offensive.  plz rename into glimpsebrowser

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#4989]
`qute` seems like an insult imo.  following the footsteps of https://github.com/glimpse-editor/Glimpse plz rename `qutebrowser` into `glimpsebrowser`.  else u may get forked.

> For now, not a lot! The initial aim is to provide a downstream fork of the GNU Image Manipulation Program that has a **_less problematic_** **_name_** so there are no potential barriers to using the software in businesses and educational institutions.

**Comment by jgkamat** [comment]
I agree, but I find the 'browser' part of the name offensive as well, and this is blocking me from using qutebrowser at my school (due to my schools ban on Mario villans). How about renaming to '␇' instead? The bell character will make it more friendly for educational purposes, and improve typing speed for startup substantially.

On August 27, 2019 4:32:59 PM PDT, Toraboran Caveman <notifications@github.com> wrote:
>`qute` seems like an insult imo.  following the footsteps of
>https://github.com/glimpse-editor/Glimpse plz rename `qutebrowser` into
>`glimpsebrowser`.  else we will fork u.
>
>> For now, not a lot! The initial aim is to provide a downstream fork
>of the GNU Image Manipulation Program that has a **_less problematic_**
>**_name_** so there are no potential barriers to using the software in
>businesses and educational institutions.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mschilli87** [comment]
While I agree that the re-branding attempt of GIMP to Glimpse is not necessary I think it's not funny at all to poke fun of the people that like a piece of FOSS, believe it could do better with a specific change, and try to make that change via a fork. Why the need for hostility? This shines a very bad light on the free/open source software community IMHO. So what if there is a clone of GIMP that's called Glimpse? Who cares if @jgkamat decides to release his qutebrowser fork under its own name as he feels it diverges too much from upstream or he simply disagrees strongly with @The-Compiler about something? I use neovim, neomutt, libreoffice, and libressl. My window manager of choice was renamed from `scrotwm` to `spectrwm` (see https://github.com/conformal/spectrwm/commit/e83f3b790887174fe8b8fd6b3c98172b59ff9305) to be less problematic. While personally I am fine with the GIMP (not a great name but so what), I think people that use the ideas behind FOSS to initiate the change they want to see deserve respect.

Also the [GIMP FAQ](https://www.gimp.org/docs/userfaq.html#i-dont-like-the-name-gimp-will-you-change-it) state:
> #### I don’t like the name GIMP. Will you change it?
> With all due respect, no.
> [...]
> Finally, if you still have strong feelings about the name “GIMP”, you should feel free to [...] maintain your own releases of the software under a different name.

Even encouraging people do to what the Glimpse folks not attempt to do.

**Comment by The-Compiler** [comment]
This isn't the place for random trolling or a discussion about GIMP/Glimpse (though I have to admit @jgkamat made me chuckle).

@Al-Caveman Your last couple of issues/comments here were all quite off-topic. Lots of people are subscribed to this repository because they are interested in qutebrowser development. Take this kind of thing to a blog or Twitter account or something.
