### ISSUE TITLE
Night mode for Readability

### ISSUE THREAD

**Issue by jorgelaranjo** [qutebrowser/qutebrowser#4994]
Is there a quick way to give option to use normal mode or a night mode for readability?
I changed mine to be in night mode as I rather have it that way.

```
1         body {
  2             margin: 40px auto;
  3             max-width: 650px;
  4             line-height: 1.4;
  5             padding: 0 10px;
  6             background-color: black;
  7             opacity: 0.6;
  8             color: white;
  9         }
```

**Comment by The-Compiler** [comment]
Are you talking about the readability userscript? You could probably inject custom additional css using the `content.user_stylesheets` setting.

**Comment by jorgelaranjo** [comment]
> Are you talking about the readability userscript? You could probably inject custom additional css using the `content.user_stylesheets` setting.

Or just change the readability userscript to take into accnt a setting on the config or even better take argument [is it possible]?
If possible to pass argument to userscript then can have two key binds: normal and night mode.
More modes would also be possible.

Happy to code the options on the userscript.

**Comment by rien333** [comment]
@jorgelaranjo I just use a `content.user_stylesheets`  binding to toggle a night mode, like so:
```python
config.bind('<Ctrl-R>', 'config-cycle content.user_stylesheets ~/solarized-everything-css/.../nord-dark-all-sites.css ""')
```

The down side might be that all websites would be in "night mode" when  a style sheet is applied, although toggling is fairly quick. This could possibly be fixed if `content.user_stylesheets` would be translated to a domain specific setting, so that it only works for URLs that point to the readability script output (which most settings of qutebrowser support, but the stylesheet setting currently doesn't IIRC).

> If possible to pass argument to userscript then can have two key binds: normal and night mode.

I think you can do this like so:
```python
c.aliases = {"readability" : "spawn --userscript ~/.config/qutebrowser/userscripts/readability", 
"readability-night" : "spawn --userscript ~/.config/qutebrowser/userscripts/readability night"}
```
(haven't tested this tho)

**Comment by hyiltiz** [comment]
It would've been another killer feature if this option was included (with any non-bright CSS really; which one doesn't matter that much) so users could simply do `:set night-mode True` and `:set night-mode False` instead of first looking up a CSS and digging through `config.py` and then restarting the browser. Also, since new pages still flashes white screen in the WebKit engine by default and requires users' to hack some more, the `:set night-mode True` option could also set up proper options and CSS rules s.t. new pages and refreshes doesn't flash bright white lights.

**Comment by The-Compiler** [comment]
@hyiltiz This issue is about the [readability userscript](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/readability), not qutebrowser in general.

> It would've been another killer feature if this option was included (with any non-bright CSS really; which one doesn't matter that much) so users could simply do `:set night-mode True` and `:set night-mode False` instead of first looking up a CSS and digging through `config.py` and then restarting the browser.

I disagree. If something is solvable according to the users preference with a simple download and `:set` command (no fiddling with `config.py` or restarting needed), I don't see a good reason for qutebrowser to hardcode a particular choice.

> Also, since new pages still flashes white screen in the WebKit engine by default and requires users' to hack some more, the `:set night-mode True` option could also set up proper options and CSS rules s.t. new pages and refreshes doesn't flash bright white lights.

I don't see any flashing with WebKit. Either way, QtWebKit [isn't really maintained](https://github.com/annulen/webkit/releases), so if you're going to use that instead of the default QtWebEngine backend, you're on your own. I'm not going to put any time into QtWebKit-specific things. Are you volunteering?

> This seems to now have been implemented 9 days ago [6cceadd](https://github.com/qutebrowser/qutebrowser/commit/6cceadd9a79a83c5c351d633e486149af1746cbc). Just need to wait for this changes to be released and flow downstream.

...huh? That's about fonts.

**Comment by rien333** [comment]
@hyiltiz Maybe you're talking about `c.colors.webpage.force_dark_color_scheme = True`? It's not a perfect solution to a night mode, but for the couple of websites that have support for it, it's pretty neat. (in the end, it's probably going to be a better idea to push website makers to support, than do custom CSS hackery)

**Comment by rhysday** [comment]
Is this possible to get dark reader script via the greasemonkey working on say, just wikipedia? As it seems to break Google maps

**Comment by rien333** [comment]
You can exclude websites from greasemonkey scripts, if that also works for you. Google has tons of results. Wrong thread tho, this is about an userscript.
