### ISSUE TITLE
Finishing of page loading quits hint mode

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#5052]
<details>
  <summary><strong>Version info</strong></summary>

  qutebrowser v1.8.1
  Git commit: 
  Backend: QtWebEngine (Chromium 65.0.3325.230)

  CPython: 3.7.3
  Qt: 5.11.3
  PyQt: 5.11.3

  sip: 4.19.14
  colorama: 0.3.7
  pypeg2: 2.15
  jinja2: 2.10
  pygments: 2.3.1
  yaml: 3.13
  cssutils: no
  attr: 18.2.0
  PyQt5.QtWebEngineWidgets: yes
  PyQt5.QtWebEngine: yes
  PyQt5.QtWebKitWidgets: no
  pdf.js: no
  sqlite: 3.27.2
  QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

  Style: QFusionStyle
  Platform: Linux-4.19.0-6-amd64-x86_64-with-debian-10.1, 64bit
  Linux distribution: Debian GNU/Linux 10 (buster) (debian)
  Frozen: False
  Imported from /usr/lib/python3/dist-packages/qutebrowser
  Using Python from /usr/bin/python3
  Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

  Paths:
  cache: /tmp/cache/qutebrowser
  config: /home/user/.config/qutebrowser
  data: /home/user/.local/share/qutebrowser
  runtime: /run/user/1000/qutebrowser
  system data: /usr/share/qutebrowser

  Autoconfig loaded: yes
  Config.py: /home/user/.config/qutebrowser/config.py has been loaded
  Uptime: 0:03:12
</details>

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Sometimes, when I open a page and quickly run hints, I can notice that the hinting mode was quit before I managed to type the sequence to follow a hint. First, I experienced that with qutebrowser 1.7, so I stuck with v1.6 for a while, but now I experience the same issue with v1.8, yet it seems to happen more rarely.

**How to reproduce**
Unfortunately, I can't reproduce the issue reliably, it feels like some race condition happens inconsistently (just guessing). Please, let me know if I can run some tests to investigate the issue.

**Comment by The-Compiler** [comment]
That's intended so that if you e.g. click a hint manually, the hints disappear. If you prefer then to stay around no matter what, there's the `hints.leave_on_load` setting.

**Comment by The-Compiler** [comment]
I wrote a bit of a longer answer for this on Reddit - here it is:

The main problem here is [QTBUG-65223](https://bugreports.qt.io/browse/QTBUG-65223) which means that QtWebEngine (since Qt 5.10) emits its `loadStarted` signals whenever a page changes its URL via JavaScript (which can commonly happen while typing on pages like Google Translate). So qutebrowser can do one of these things:

- Leave insert/hint mode when a page load started - but then it'll also leave it e.g. when typing on Google Translate, which was a bug for a long time.
- Leave insert/hint mode when a page load finished (like it does now).
- Don't leave them at all (which you can do via the `input.insert_mode.leave_on_load` and `hints.leave_on_load` settings). This tends to be rather confusing - when you e.g. enter a search term on Google and press enter, you probably wouldn't expect to still be in insert mode.

I wish there was a better solution (or that bug would finally get fixed) - but so far, I haven't been able to think of one.
