### ISSUE TITLE
Wrong font type

### ISSUE THREAD

**Issue by emprovements** [qutebrowser/qutebrowser#5077]
**Version info (see `:version`)**: qutebrowser v1.8.1

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Hi, after mac update to Catalina, some fonts are rendered in serif style instead of mono. I guess it only does that for code frames and similar. I also tried version 1.7 without any luck. Here is the comparison with Safari: https://postimg.cc/gallery/g3rr914u/

**Comment by The-Compiler** [comment]
Looks like [[QTBUG-79120] 'font-family' requests do not work for generic fonts - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-79120).

**Comment by emprovements** [comment]
Definitely this one. So I will wait until they fix it.

**Comment by The-Compiler** [comment]
If you're lucky, something in the Chromium upgrade in Qt 5.13 (hopefully bundled with qutebrowser v1.9.0 finally) or 5.14 (upstream release scheduled for end of November) will already help.

If you're curious, I have https://www.qutebrowser.org/tmp/qutebrowser-1.8.0-qt5.13.1.dmg - note however that due to a Qt bug, keyboard input on pages can be broken there (you can work around it by unfocusing and refocusing your window). Also you might want to first back up the data directory shown in `:version`.

**Comment by emprovements** [comment]
Thanks a lot for help. I think I can live with the different font for now and avoid the other issues :-)
