### ISSUE TITLE
Weird behaviour under OSX

### ISSUE THREAD

**Issue by GhostValk** [qutebrowser/qutebrowser#5103]
I'm seeing something odd in my qb behaviour. When i open ob from the app icon, qb works extremely slow, takes a long time to open, every time i open a new tab it gets stuck for 10 seconds or so, etc., but when i run qb from the terminal (`qutebrowser` command symlinked to /Applicaitons/qutebrowser/Content/MacOs/qutebrowser) it works perfect, instant response speed, no lag, no freezing, nothing, all good.

However, when i run qb in this way (from the terminal), when i try to open a new tab or any url from the terminal or any external source (anything that uses the default browser), instead of opening it in a new tab as expected, it opens a new window, doesn't open the url and just pops up DDG.

Any idea of what could it be?

**Comment by The-Compiler** [comment]
> When i open ob from the app icon, qb works extremely slow, takes a long time to open, every time i open a new tab it gets stuck for 10 seconds or so, etc., but when i run qb from the terminal (`qutebrowser` command symlinked to /Applicaitons/qutebrowser/Content/MacOs/qutebrowser) it works perfect, instant response speed, no lag, no freezing, nothing, all good.

Let's continue this in #5095.

> However, when i run qb in this way (from the terminal), when i try to open a new tab or any url from the terminal or any external source (anything that uses the default browser), instead of opening it in a new tab as expected, it opens a new window, doesn't open the url and just pops up DDG.

macOS is weird in how it handles this: Instead of running something like `qutebrowser https://example.org/` like every other platform, it opens qutebrowser and sends a special `OpenEvent` to it. It's entirely possible macOS becomes confused there because the application *is* already running, but not with the name (the macOS bundle name) it expects as it's run without its `Info.plist`. I don't think qutebrowser can/should do anything about this.
