### ISSUE TITLE
Make it possible to enable/disable wrapping-around for :search-next and :search-prev

### ISSUE THREAD

**Issue by k0ral** [qutebrowser/qutebrowser#5136]
Maybe I just missed it, but it seems that `:search-next` and `:search-prev` always wrap around at the moment.
Would it be possible to add a boolean argument to these commands to control whether search wraps around ?

**Comment by The-Compiler** [comment]
Currently, this isn't possible with the API we get. However, it should be possible to implement with Qt 5.14 with the [new QWebEngineFindTextResult class](https://codereview.qt-project.org/c/qt/qtwebengine/+/267764) (see #4616). The Qt 5.14 release is planned for next week.

**Comment by Soul-Drake** [comment]
Maybe I'm just not creative enough, but I've had a look at the relevant code and the new FindTextResult class (I thought I might try this as my first contribution) and don't see how this could be consistently implemented, as the FindTextResult is only available when the first search is finished (through the signal `findTextFinished`). So the result could be used in `:search-next` or `:search-prev` to prevent wrapping, but the first search would still wrap around at the end (or beginning) of the page. Maybe someone else knows how to 'fake' the first search so that we know whether it would wrap? Or maybe there's something else I haven't considered...

**Comment by The-Compiler** [comment]
I don't really follow - how is it possible for the first match to wrap around? Searches always start at the top of the page - so either there is a result somewhere on the page (and there's no need to wrap around), or there was no result (and thus no match). Am I missing something?

Let me also note that a proper fix for this should also:

- Set the `QWebPage.FindWrapsAroundDocument` flag on QtWebKit (which is hardcoded to be set at the moment)
- Make sure that nothing breaks on Qt versions older than Qt 5.14

**Comment by Soul-Drake** [comment]
From my experiments with the behaviour, it seemed like the search started from the current scroll position - so `--reverse` would scroll up, while the default would scroll down (unless of course there was wrapping). For example, when I scrolled past the first instance of the word and then searched with `--reverse`, the search snapped to the first instance, even though there were instances further down on the page. Given that, if searches always start at the top, how does `--reverse` actually work on the first search?

**Comment by The-Compiler** [comment]
What `--reverse` does is essentially setting QtWebEngine's `FindBackward` flag, which in turn passes it to Chromium. All the internals are handled by Chromium, so I can only observe what it does: It seems to start at the first match at the bottom of the page then. Is this also what you're seeing? If not, which Qt version, qutebrowser version and backend are you on? (see `:version`)

**Comment by Soul-Drake** [comment]
Hmm. Now it's working in the way you describe - maybe my search history was messing with me in testing. Anyway, that's good news - it means that the implementation could work properly. I'll try some things in the next few days. (Btw, thank you for your quick response! I was looking for a good first project to contribute to and was very impressed with the contributing info and the availability of "easy" issues - very welcoming.)

**Comment by The-Compiler** [comment]
I'm glad to hear that! Let me note that reviewing/merging the PR might take a longer while because of the rather big PR backlog (and me losing track of that for a rather long time). I'm now trying to get things ramped up again and this one hopefully should be rather small - but it might still take a couple of days or weeks until I get back to you.

I really appreciate you reaching out before starting things! Always helps to get everyone on the same page first. Let me know if you get stuck somewhere!

**Comment by Soul-Drake** [comment]
Hmm. I've run into an unfortunate obstacle: I think it would be good to have a similar message when wrapping as when a wrap has been prevented; this isn't a problem with the WebEngine implementation, since I can just show a "Search hit TOP/BOTTOM" message when I prevent a wrap. But in WebKit, there's no information on whether a wrap was prevented or not, so I can't show a message. Should I also remove the message from WebEngine for the sake of consistency?

**Comment by The-Compiler** [comment]
Seems fine to me to show it with QtWebEngine only - it's likely only a very small minority using QtWebKit anyways.
