### ISSUE TITLE
Qt 5.14.1

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5202]
- [x] ~~Upgrade requirements as soon as PyQt 5.14.2 with Qt 5.14.1 is out~~
- [ ] Adjust documentation to recommend Qt 5.14.1
- [ ] Update changelog for macOS/Windows builds

**Comment by rien333** [comment]
Note that Qt 5.14.1 has been released, as of this morning: https://download.qt.io/official_releases/qt/5.14/

**Comment by The-Compiler** [comment]
@rien333 Awesome! How did you find out so fast? I'll still wait a couple of days for a PyQt release bundling it though. I could [bundle it myself](https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#bundling-qt-using-pyqt-bundle), but it's something I'd need to do on three platforms separately, so I'd rather wait :laughing:

**Comment by rien333** [comment]
> How did you find out so fast?

The Qt team is pretty bad with releasing or updating info on new (minor) releases, in the sense that their normal communication channels often lack behind a bit (see https://wiki.qt.io/Qt_5.14_Release, also no easily accessible changelog yet, except when you dig through their git repo). Because I've had problems with with some Qt releases, I just got in the habit of checking the ultimate source https://download.qt.io/official_releases/. By pure change, I did so early this morning.

**Comment by The-Compiler** [comment]
FWIW I usually watch [the blog](https://www.qt.io/blog) and various mailinglists ([announce](https://lists.qt-project.org/mailman/listinfo/announce), [releasing](https://lists.qt-project.org/mailman/listinfo/releasing)) - those do lack behind a bit, but we're talking 3-4 hours which seems fine (considering that people might be using different mirrors which also need some time to propagate, etc.). The wiki seems to be updated by now as well.

**Comment by The-Compiler** [comment]
PyQt pushed new releases with Qt 5.14.1 - things [are looking good](https://travis-ci.org/qutebrowser/qutebrowser/jobs/644568675)!
