### ISSUE TITLE
There is a huge Security Bug  while using Socks5 Proxy.

### ISSUE THREAD

**Issue by a8vbtb7p** [qutebrowser/qutebrowser#5221]
I decide to report this bug public, so people can fix it for their self before there is a official fix in next patch.

It is not recommended to use Tor in Qutebrowser. There is a huge DNS Leak, for example on "browserleaks.com/ip". I also disabled systemd-resolved. I am using Ubuntu with KDE/Plasma, DNS on Gentoo leaks too.

**Comment by The-Compiler** [comment]
This isn't a security bug - Chromium (and thus qutebrowser) does not proxy DNS requests.

**Comment by fturco** [comment]
Isn't the `content.proxy_dns_requests` setting about avoiding DNS leaks?

**Comment by The-Compiler** [comment]
@fturco Yes, but that setting is only available with the (non-default and generally insecure) QtWebKit backend. While it does set the respective flag for QtWebEngine, it's not read by QtWebEngine so it won't do anything.

It looks like the situation about this changed since I last tested though - it looks like Chromium does proxy DNS requests by default, however according to [Configuring a SOCKS proxy server in Chrome - The Chromium Projects](https://sites.google.com/a/chromium.org/dev/developers/design-documents/network-stack/socks-proxy) it can still happen that other components inside Chromium do raw DNS requests, unless a `host-resolver-rules` flag is given - so it might be pure luck that I don't see my normal name servers during testing.

That flag might allow qutebrowser to implement `content.proxy_dns_requests` for QtWebEngine as well, I opened #5731 for that.

As for the OP, I still stand by the fact that calling this a "huge security bug" is... quite a stretch.
