### ISSUE TITLE
Wouldn't many tests that rely on pytest's parametrize be better rewritten using Hypothesis?

### ISSUE THREAD

**Issue by Kharacternyk** [qutebrowser/qutebrowser#5247]
Related: #830

For example, many tests found in `test/utils/test_utils.py` seem easy to rewrite to properties, because of pure-functional nature of the util functions. Would a PR that one by one converts those tests to properties make sense?

**Comment by The-Compiler** [comment]
I don't think rewriting them makes sense. Having explicit examples in tests have a lot of upsides: They're explicit, they serve as good documentation about the behavior of the code, and they're much simpler and faster than hypothesis-based tests.

However, *adding* more hypothesis-tests in addition to the explicit ones is something I'd certainly welcome!

**Comment by Kharacternyk** [comment]
Hypothesis has `@example` decorator that serves the purpose of forcing some values to be checked every run. A test with this decorator serves as documentation just like a parametrized test, doesn't it?

I don't think adding Hypothesis tests makes sense, because they would almost duplicate the code of the parametrized tests.

**Comment by The-Compiler** [comment]
Sorry for the late answer, this got buried in my inbox. No, a test with an `@example` decorator doesn't tell as much, because you can only see the input, not the expected output - and you don't *test* the expected output either, only some invariants which, depending on the function under test exactly, can't test very much.

Also, Hypothesis doesn't play very nice with pytest features in general (per-test fixtures only run once for the entire repeated hypothesis test and probably will stop working entirely at some point, see https://github.com/HypothesisWorks/hypothesis/issues/2370).

I also disagree on hypothesis tests duplicating the parametrized ones - they *will* be different, because they will need to formulate invariants rather than input/output pairs. Do you have a concrete example where a hypothesis test really would test the same as the current parametrized ones?

**Comment by Kharacternyk** [comment]
I don't have a strong opinion on this anymore. This was my thought while I was writing tests for #5236. I guess you are absolutely right.
