### ISSUE TITLE
Reader mode

### ISSUE THREAD

**Issue by stozi** [qutebrowser/qutebrowser#5278]
I like this browser but most of what I do is reading and writing articles. Chromium & Firefox have a reader mode that gives you the main body of text of a given page in a clear, readable (and customizable) format. I'd have a hard time living without that.

**Comment by ninewise** [comment]
So does qutebrowser: check out the readability userscripts https://github.ugent.be/Prog2/OGPRog-project-2019-2020

**Comment by mepowerleo10** [comment]
Could the installation process of the readability userscripts be more precise and less vague. Because I'm using Arch linux, but installing the libs readability or breadability and putting the userscript in the script directories, still I'm getting this log.

`07:49:22
ERROR   
procs
guiprocess:_on_finished:122
Process stderr:
Traceback (most recent call last):
  File "/home/mepowerleo10/.local/share/qutebrowser/userscripts/readability", line 50, in <module>
    from breadability.readable import Article as reader
ModuleNotFoundError: No module named 'breadability'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mepowerleo10/.local/share/qutebrowser/userscripts/readability", line 55, in <module>
    from readability import Document
ModuleNotFoundError: No module named 'readability'`

**Comment by The-Compiler** [comment]
@mepowerleo10 Not really, because how to set things up properly differs a lot between different systems/setups. 

I tried with `pip install --user breadability` on Archlinux and it works fine, so you'll need to be more specific about what you did exactly - I suggest you open a [new discussion](https://github.com/qutebrowser/qutebrowser/discussions/new) with more details about how you installed (b)readability, your full `:version` output and the output of `which python`, `python -V` and `python -v -c "import breadability"`.

That all being said, I'd recommend using the `readability-js` userscript instead, as its output tends to be much nicer in most cases (it's the same Firefox uses for its reader mode).
