### ISSUE TITLE
Chrome-Dark-Theme bind

### ISSUE THREAD

**Issue by kufue** [qutebrowser/qutebrowser#5307]
I would like a bind for dark mode https://github.com/the1812/Chrome-Dark-Theme/blob/master/manifest.json . I didn't figure out how to do it with existing features

**Comment by The-Compiler** [comment]
The link you posted is just a Chrome theme which styles its UI elements. Here is how it looks when installed in Chrome without any other customization:

![image](https://user-images.githubusercontent.com/625793/77634247-f2375200-6f50-11ea-8e3b-bac8b5dba865.png)

qutebrowser doesn't have any Chrome UI elements, so that doesn't make any sense. You'd instead use the `colors.*` settings to customize how qutebrowser's UI looks.

If what you really want is to recolor websites (which has nothing to do with that theme), you might want to look at the `content.user_stylesheets` setting or https://github.com/qutebrowser/qutebrowser/issues/2377#issuecomment-577689021 (which isn't possible to toggle at runtime).
