### ISSUE TITLE
Insert mode on twitter not triggered (content editable field)

### ISSUE THREAD

**Issue by andys8** [qutebrowser/qutebrowser#5349]
**Version info**:

qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

https://paste.the-compiler.org/view/430dbcd9
https://github.com/andys8/dotfiles/blob/master/qutebrowser/config.py

(I've the same behavior on a different machine with arch instead of ubuntu and newer qtwebengine)

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

Some websites do not use input fields as they were meant to be used. Instead they mark html notes as content-editable.

```html
<div contenteditable="true">
  This text can be edited by the user.
</div>
```

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

This doesn't trigger insert mode in qutebrowser. It is used on some websites, for example twitter.com. For comparison: vimium in chrome is working fine with these kind of input fields.

![image](https://user-images.githubusercontent.com/13085980/79071356-918f6f80-7cdb-11ea-93c3-dfe232ebb772.png)

For me it's a large painpoint, because you can't trust qutebrowser. I click on a text field and start typing. It has the focus, but if qutebrowser didn't start the insert mode, the typed characters will be represented as normal mode keybindings, and changes are high you close the website or jump somewhere else accidentally.

**How to reproduce**

1. Open https://twitter.com
2. Login
3. Try to click into field to write a new tweet
4. Insert mode will not be triggered

![qutebrowser_twitter_bad](https://user-images.githubusercontent.com/13085980/79071042-ae2aa800-7cd9-11ea-8d22-6111304547ea.gif)

**Fix**

I tested #4722 with https://github.com/jgkamat/qutebrowser/tree/integration to verify it'll fix the behavior with twitter.com (because it's a large example). The insert mode indicator (magenta) is triggered. It's the case for other examples like the minimal one, too.

![qutebrowser_twitter_ok](https://user-images.githubusercontent.com/13085980/79071040-a965f400-7cd9-11ea-9e30-61074bcbc242.gif)

It would be awesome if you @The-Compiler could have another look at #4722 and consider merging it or solving the issue in another way. Thanks a lot!

**Comment by jgkamat** [comment]
Partially unrelated but the fork I'm maintaining for myself is on [gitlab](https://gitlab.com/jgkamat/qutebrowser/-/tree/integration), I'm no longer regularly updating the github one. However it should be almost the same at this time at least.

**Comment by andys8** [comment]
@The-Compiler Sorry to bother you, but could you leave a short statement if there is something wrong with the PR #4722, something blocking or to do, or if you didn't have the time to consider it. Thank you.

**Comment by The-Compiler** [comment]
@andys8 Short statement: The latter.

Slightly longer answer: There was a longer time where I couldn't look at PRs due to various reasons (which was clearly stated in the contribution docs at the time), which caused a lot of things to pile up. This should slowly improve now that I can spend more time on qutebrowser again (after having spent some time with various bureaucracy work related to setting up a [crowdfunding](https://github.com/sponsors/The-Compiler/) and [related one-man company](https://bruhin.software/) so I can work part-time on qutebrowser). Given the huge backlog and other maintenance work which needs to be done but often ends on my plate, that will still take some time.

I plan to send out an announcement on how I plan to handle things going forward as soon as I get confirmation that all the bureaucracy stuff is over for now and things are handled correctly (tax-wise and such). I was told should happen in the next 1-2 weeks.

**Comment by andys8** [comment]
That sounds awesome. I hope it works out. Regarding the issue: No prob. I'll fork for now. Take your time and prioritize the way it makes sense for you.
