### ISSUE TITLE
screensharing under wayland via WebRTC

### ISSUE THREAD

**Issue by pltrz** [qutebrowser/qutebrowser#5421]
As I understand it, desktop sharing via the WebRTC currently does not work under wayland unless qtwebengine is compiled with PipeWire support via the `RTC_USE_PIPEWIRE=true` compile-time option (see [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr/wiki/Screencast-Compatibility)).

I have yet to verify this actually works; after the weekend I can test this to close the issue.

**Comment by pltrz** [comment]
after compiling webengine with pipewire support, I still seem to get the same result as before: when attempting to share the screen, it shares as an empty black screen, with a mouse cursor in the centre

**Comment by The-Compiler** [comment]
Nothing qutebrowser can do here - you'd need to report this to the [Qt Bug tracker](https://bugreports.qt.io/). Make sure you get it working in Chromium first, though. FWIW you might also need to start with `--qt-flag enable-webrtc-pipewire-capturer`.

**Comment by maximbaz** [comment]
FYI the correct flag is `--qt-flag enable-features=WebRTCPipeWireCapturer`, together with qt5-webengine compiled with pipewire support this allows qutebrowser to share screen on Wayland!

**Comment by pltrz** [comment]
@maximbaz thanks for the tip! I am compiling `qt5-webengine` and trying it out

**Comment by pltrz** [comment]
@maximbaz can you elaborate with more details? I recompiled `qt5-webengine` on arch, modifying the `PKGBUILD` to include `export RTC_USE_PIPEWIRE=true` and installed `xdg-desktop-portal` and `xdg-desktop-portal-wlr`, run qutebrowser with `--qt-flag enable-features=WebRTCPipeWireCapturer`, but still no luck, just black screen with the cursor in the centre (using sway).

**Comment by maximbaz** [comment]
Since you are on Arch, feel free to take my build:

**Comment by The-Compiler** [comment]
@pltrz Do you use the latest git master? If so, could you try whether starting with `-s scrolling.bar never` changes anything? (That *does* sound totally random, but the new default `overlay` also uses an `enable-features` flag, and I'm not sure if it's allowed to repeat them)

**Comment by maximbaz** [comment]
Since you are on Arch, feel free to take my build:

https://pkgbuild.com/~maximbaz/repo/qt5-webengine-5.15.0-2-x86_64.pkg.tar.zst

I have started a discussion with maintainers of `qt5-webengine` package on Arch, hopefully we will be able to compile it with pipewire support for everyone, so that custom build will not be required anymore.

---

Here's the full list of actions I did:

1. Install `libpipewire02` and `AUR/xdg-desktop-portal-wlr`
2. Have these environment variables exported before sway starts:

```
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
```

3. Launch `qutebrowser --qt-arg enable-features=WebRTCPipeWireCapturer`
4. Test screen share on https://mozilla.github.io/webrtc-landing/gum_test.html

------

> I recompiled qt5-webengine on arch, modifying the PKGBUILD to include export RTC_USE_PIPEWIRE=true

If the build didn't crash because of missing `libpipewire02` make dependency, your variable wasn't respected. I don't know how to properly pass chromium compilation switch when compiling qt5-webengine, so in my test build I cheated by applying the patch below:

```patch
+++ b/third_party/webrtc/webrtc.gni
@@ -112,7 +112,7 @@ declare_args() {
   # By default it's only enabled on desktop Linux (excludes ChromeOS) and
   # only when using the sysroot as PipeWire is not available in older and                                                                                                                                      
   # supported Ubuntu and Debian distributions.                                                                                                                                                                 
-  rtc_use_pipewire = is_desktop_linux && use_sysroot
+  rtc_use_pipewire = true
 
   # Set this to link PipeWire directly instead of using the dlopen.
   rtc_link_pipewire = false   
```

**Comment by pltrz** [comment]
Alright, so no success still, with the required packages and with your build of webengine. But slightly different result now. I get a square black screen with nothing visible. The result before (and I didn't have libpipewire02 installed before) was that I got a rectangular black screen with a visible mouse cursor in the centre. Note that in both cases, the test on the website returned a status of "Success!", even though it clearly wasn't.

**Comment by maximbaz** [comment]
What version of qutebrowser do you use? And are you sure that you exported variables before away started? Maybe reboot just in case.

**Comment by pltrz** [comment]
yes, I've been careful about sourcing these in my `~/.bash_profile` before, and I just confirmed that the environment variables are set

**Comment by maximbaz** [comment]
For reference, created the following bug to find a way to compile QtWebEngine with PipeWire support: https://bugreports.qt.io/browse/QTBUG-85309

Once we have a build parameter to enable PipeWire (or at least a merged patch that we will backport to Qt 5.15, since it seems to be a small patch), we will enable this in the Arch package and getting screenshare under Wayland will become a little easier 🙂

**Comment by maximbaz** [comment]
Hello again, the bug is now closed, patch is merged in webengine and backported to Arch package, screen sharing under Wayland is now possible with `extra/qt5-webenginge 5.15.0-5` 🚀

**Comment by The-Compiler** [comment]
@maximbaz Thanks for taking care of everything! :heart:

**Comment by pltrz** [comment]
@maximbaz awesome!! Does it work by default, or need some specific settings or tweaks? I've updated my system, pulled in `extra/qt5-webengine 5.15.0-5`, still have the same result as before. I've also got `xdg-desktop-portal`, `xdg-desktop-portal-wlr` (AUR), and `libpipewire02` installed.

**Comment by maximbaz** [comment]
Everything that you describe is still needed, you only don't need to compile a custom version of webengine anymore. Could you try this command and then test https://mozilla.github.io/webrtc-landing/gum_test.html ?

```
$ qutebrowser --temp-basedir --qt-flag enable-features=WebRTCPipeWireCapturer -s scrolling.bar always
```

I don't know how this is even possible or related, but I'm testing right now the command above, and without `scrolling.bar=always` the screen share is not working... 😕 

I could swear it wasn't required before, but at the same time I had that setting in my `config.py` since forever, maybe it somehow slipped my attention when I was testing with `--temp-basedir`.

**Comment by pltrz** [comment]
Seems like `--qt-flag enable-features=WebRTCPipeWireCapturer` is the key here. Can this be passed in qutebrowser's `config.py`?

**Comment by The-Compiler** [comment]
@maximbaz The default `scrolling.bar = 'overlay'` internally passes `--enable-features=OverlayScrollbar` to Chromium. Looks like you can't pass `--enable-features` twice, or one will override the other. I guess I'll have to parse existing `--enable-features` flags from the config and if they exist, add `OverlayScrollbar` there instead of passing the switch... I'll take a look.

@pltrz You can set `qt.args` to `['enable-features=WebRTCPipeWireCapturer']` (and `scrolling.bar` to `always`, `when-searching` or `never`, as per above).

**Comment by The-Compiler** [comment]
I was wondering if qutebrowser should just enable that by default on Wayland. The related [Chromium change](https://chromium-review.googlesource.com/c/chromium/src/+/1402441) says:

> The flag is disabled by default, due to the user experience as it
> involves two extra confirmation dialogs outside of Chromium - requested
> by Weiyong Yao. It could change the default, once it goes through Chromium
> UI review.

@maximbaz @pltrz Can you elaborate on what that means exactly? I didn't find any context on that...

**Comment by maximbaz** [comment]
I think I found some context, they refer to how many confirmation dialogs are being opened by Chromium once you click a button to start screen share. See here:

- https://bugs.chromium.org/p/chromium/issues/detail?id=682122#c50
- https://github.com/flatpak/xdg-desktop-portal-gtk/issues/204#issuecomment-510159005

I don't think it applies to qutebrowser, which at least for me only shows a single confirmation dialog (below), but I could be wrong, maybe some specific desktop environments show more dialogs when they detect screen share request 🤔 

![image](https://user-images.githubusercontent.com/1177900/87134030-698eb880-c298-11ea-8b78-c78e0446e795.png)

**Comment by maximbaz** [comment]
@The-Compiler by the way, when I try to screen share in Chromium, it also shows a confirmation dialog, and one of the options is to share a single tab instead of the entire desktop. What's interesting is that contrary to desktop sharing, sharing a single tab does not require pipewire installed or any Chromium flags, it just works out of the box.

![image](https://user-images.githubusercontent.com/1177900/87137228-dc9a2e00-c29c-11ea-9b64-bdd556520267.png)

Do you know if it's possible to add in qutebrowser? On the one hand it is quite limited comparing to be able to share the entire desktop, on the other hand it doesn't require setting so much things up, could be helpful to some folks. But to be honest I'm not sure how useful it is to spend time on, instead of just enabling desktop sharing... 🤔

**Comment by The-Compiler** [comment]
> I think I found some context, they refer to how many confirmation dialogs are being opened by Chromium once you click a button to start screen share.

Ah, right I missed that. Even if additional dialogs would show up on qutebrowser, I don't think that's a good enough reason to disable the feature entirely by default.

I pushed a couple of commits - qutebrowser now combines the internal `enable-features` flags with existing ones (1a9e74bfaf9a9db2a510dc14572d33ded6040a57) and enables the WebRTC pipewire capturer by default (cfc8aefc46266217c4c94b0e128aed1bb671c84f).

> What's interesting is that contrary to desktop sharing, sharing a single tab does not require pipewire installed or any Chromium flags, it just works out of the box.

I suppose that's because Chromium knows itself what it's drawing inside that tab, so it doesn't need any support from the desktop environment.

> Do you know if it's possible to add in qutebrowser?

Not without QtWebEngine support, see [[QTBUG-70077] QtWebEngine should provide a list of capture devices - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-70077)

**Comment by dofinn** [comment]
Hi, im trying to follow the thread, should screen sharing work on wayland now if I build from source with virtual env? I am on fedora with wayland it currently fails to screen share. Thanks for the awesome browser BTW, this is the only missing peice for me :+1:

**Comment by The-Compiler** [comment]
@dofinn Define "build from source" - by default, installing via a virtualenv will give you a pre-build Qt, which (if I remember correctly) doesn't contain the Wayland platform plugin, so it'd run via XWayland.

**Comment by dofinn** [comment]
Thanks for the response @The-Compiler . You are correct, i installed with virtualenv. When you say Qt you mean Qt or QtWebEngine?

**Comment by The-Compiler** [comment]
@dofinn Both. QtWebEngine is a part of Qt.

**Comment by dofinn** [comment]
Thanks. Looks like I need to go do some research in this area. If anyone else gets this working on Fedora, please let me know :)

**Comment by dgpalmieri** [comment]
Hi! I've been using qutebrowser for a couple weeks now, and I'm really enjoying it. I was working on getting the screen-sharing functionality set up, and I'm running into some issues.
After following some of the notes in the thread, this is my current understanding of what screen sharing requires:
```
$XDG_CURRENT_DESKTOP=sway
$XDG_SESSION_TYPE=wayland
$RTC_USE_PIPEWIRE=true
Qutebrowser with enable-features set to WebRTCPipeWireCapturer
```
To that effect, during my most recent attempt to get this working I started qutebrowser from the command line with this command:
```
export XDG_CURRENT_DESKTOP=sway && export XDG_SESSION_TYPE=wayland && export RTC_USE_PIPEWIRE=true && qutebrowser --temp-basedir --qt-flag enable-features=WebRTCPipeWireCapturer -s scrolling.bar never
```
(I'm using the temp base as a way to make sure that none of my configuration options are interfering, and the scrolling.bar never just to cover all my bases, although if I understand correctly the issue with feature options overwriting each other was fixed)

When I go to https://mozilla.github.io/webrtc-landing/gum_test.html and click the "Screen capture" button, I get the "mozilla.github.io would like to access your desktop" dialog, and when I press 'y' I get this error:
```
[3599:3629:0222/165324.351822:ERROR:shared_x_display.cc(37)] Unable to open display
```
FWIW, I have qt5-webengine 5.15.2-5, libpipewire02 0.2.7-1, xdg-desktop-portal 1.8.0-1, and xdg-desktop-portal-wlr 0.2.0-1 all installed earlier today (2021-02-22) from the official Arch repos.

I'm a bit lost as to what I'm missing or how I can go about debugging this, so any resources/advice would be appreciated. Thank you!

**Comment by The-Compiler** [comment]
@dgpalmieri Since v1.14.0, qutebrowser does set `WebRTCPipeWireCapturer` by itself already. You can confirm by starting with `--debug --logfilter init` and looking at the "Qt arguments" line. You also won't need `-s scrolling.bar never` anymore nowadays.

QtWebEngine 5.15.2 had various issues related to screen sharing, see e.g. [Fix getDefaultScreenId on X11 (I8e513aa4) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/319623).

I think there are more (though not entirely sure!), so it might make sense to retry with QtWebEngine 5.15.3 (targetted for "end of February" as far as I know).

**Comment by maximbaz** [comment]
There is also [this issue](https://github.com/emersion/xdg-desktop-portal-wlr/issues/89) to be aware (workaround [is available](https://github.com/emersion/xdg-desktop-portal-wlr/issues/89#issuecomment-784004556), but it's quite interesting that your error is about X display even though you use Wayland 🤔

**Comment by dgpalmieri** [comment]
@maximbaz I took a look at the issue that you linked, and after trying some of the debugging tactics and fixes there, I'm still having the same issue. I learned a lot just from reading that, though, thank you for linking it! I am also quite confused as to why it's looking for an X display, as I don't even have the xorg-xwayland package installed, so as far as I know there's no way to start an X session on my machine in its current state.

@The-Compiler I did confirm that I was able to get the same result (error) starting with only `qutebrowser`, so that's a lot less typing for me lol.

Doing some further research, I was able to find [shared_x_display.cc](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/modules/desktop_capture/linux/shared_x_display.cc) and it seems that it's trying to get the name of an X display, which understandably fails since I'm using 100% native Wayland (as mentioned above).

While looking around at why chromium might try to link to an X display over Wayland, I found that my pipewire log is giving an "old version detected" message twice whenever I click the share screen button on the website, which I feel like I've seen before, I just can't seem to find where. The search continues!

**Comment by The-Compiler** [comment]
FWIW it's also entirely possible that something regressed with the Chromium update in QtWebEngine 5.15.1/.2. Strangely enough, Wayland is not an [officially supported platform](https://doc.qt.io/qt-5/supported-platforms.html) for Qt (so it's not tested, AFAIK).

On top of that, Wayland support in QtWebEngine is somewhat tricky, since AFAIK Wayland support in Chromium [is quite new](https://wiki.archlinux.org/index.php/chromium#Native_Wayland_support).

Since I don't use Wayland myself either (and I don't really know much about it), I mostly rely on users to report bugs (ideally directly to QtWebEngine).

Based on that Arch Wiki link, I wonder if `--qt-flag enable-features=UseOzonePlatform` either with or without `--qt-flag ozone-platform=wayland` changes anything. I only get a fatal `Invalid ozone platform: wayland` error from Chromium if I try, though.

**Comment by The-Compiler** [comment]
It looks like with QtWebEngine 5.15.3, screen sharing on Google Meet crashes qutebrowser.

It seems like this is this issue: [[QTBUG-91857] 5.15.3: Segfault in webrtc_event_logging::WebRtcEventLogManager::IsRemoteLoggingAllowedForBrowserContext when refreshing after screen sharing on Google Meet - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-91857)

There's a fix: [Fix WebRtcLoggingController for QtWebEngine (I70e1ab23) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/338964)

**Comment by doctorcolossus** [comment]
I am just trying qutebrowser 2.4.0-2 for the first time on sway 1:1.6.1-2 in Arch Linux with qt5-webengine 5.15.7-2.

I have tested screen-sharing in Jitsi and Mozilla's [gum_test](https://mozilla.github.io/webrtc-landing/gum_test.html) (mentioned above) and experience segfaults. When I attempt to share my screen, I am first prompted by qutebrowser for permission, then by wofi to select the screen I want to share. Then, after a pause, qutebrowser segfaults. I also tried with both of the flags you wondered about in the second-to-last comment:

With `enable-features=UseOzonePlatform`, the result was the same as without any flags:
```
$ qutebrowser --qt-flag enable-features=UseOzonePlatform
04:17:42 WARNING: Wayland does not support QWindow::requestActivate()
Segmentation fault (core dumped)
```

With both `enable-features=UseOzonePlatform` and `ozone-platform=wayland`, qutebrowser wouldn't run at all for me:
```
$ qutebrowser --qt-flag enable-features=UseOzonePlatform --qt-flag ozone-platform=wayland
[181910:181910:1225/041807.346041:FATAL:platform_selection.cc(48)] Invalid ozone platform: wayland
Trace/breakpoint trap (core dumped)
```

I have `xdg-desktop-portal-wlr` installed, configured, and working properly with these same pages in Firefox. I've downgraded mesa to 21.2.5-1 due to the flickering regression, but otherwise all of my packages are up-to-date.
