### ISSUE TITLE
'isolated' window support

### ISSUE THREAD

**Issue by GasparVardanyan** [qutebrowser/qutebrowser#5547]
I want to have an 'isolated' qutebrowser window, where I can for example play a music video, but when there is only that 'isolated' window and I opel urls, for example from terminal or with xdg-open, I want to get opened that urls in another qutebrowser window, not in the 'isolated' one.

**Comment by GasparVardanyan** [comment]
P.S. Sorry if already there is a some feature like that, but I don't know.

**Comment by The-Compiler** [comment]
You're looking for the `--basedir` commandline argument (or `--temp-basedir`).

**Comment by GasparVardanyan** [comment]
Thank you. --temp-basedir helped me, now I have another question: how can I set qutebrowser's 'instance' xorg property (the first value in WM_CLASS(STRING)).

**Comment by The-Compiler** [comment]
You can use `--qt-flag name ...`, see point 19 in the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc).

**Comment by GasparVardanyan** [comment]
But --temp-basedir doesn't load my configs, cache (( I want an 'isolated' qutebrowser window, where I can play youtube music videos form my youtube account which I have logged in in normal qutebrowser session.

**Comment by The-Compiler** [comment]
You can instead use `--basedir` to point to a separate directory, and then log in there again (and e.g. symlink your config).

**Comment by ninewise** [comment]
I'm getting the impression you don't actually want an isolated environment, just a separate window. With `:set new_instance_open_target_window first-opened` you can start qb, open a new window, and URLs opened from elsewhere would still go to the first window.

**Comment by GasparVardanyan** [comment]
But what if I have opened only the 'isolated' window?

**Comment by GasparVardanyan** [comment]
@The-Compiler sorry for disturbing so much ))
I've done this:
```
devos -> [ scratchqb ] :: pwd
/home/gaspar/.local/share/scratchqb
devos -> [ scratchqb ] :: ls -l
total 12K
lrwxrwxrwx 1 gaspar gaspar 27 Jun 25 16:48 cache -> ../../../.cache/qutebrowser/
lrwxrwxrwx 1 gaspar gaspar 28 Jun 25 16:48 config -> ../../../.config/qutebrowser/
lrwxrwxrwx 1 gaspar gaspar 14 Jun 25 16:49 data -> ../qutebrowser/
drwx------ 1 gaspar gaspar 72 Jun 25 16:50 runtime/
devos -> [ scratchqb ] ::
```
Is everything done right?

**Comment by The-Compiler** [comment]
@GasparVardanyan QtWebEngine won't support symlinking the cache and data, so this might cause data corruption. I'd recommend only symlinking the config (ideally a `config.py`).

**Comment by GasparVardanyan** [comment]
I've just wanted a qutebrowser window, with different 'instance' property, which wouldn't accept url requests from outside.
So the exact situation is: I use the dwm window manager, with [namedscratchpeds](https://dwm.suckless.org/patches/namedscratchpads/) patch, and I'm trying to have a keybinding to show/hide an 'isolated' qutebrowser window, for playing youtube videos and other stuff, like I have a [terminal scratchpad](https://github.com/GasparVardanyan/dwm/blob/master/config.h#L66). To have that window work with the namedscratchpads patch, I have to assign it a specific 'instance' value, but it's bad to have different cache folder, and log in my sites again, and also it's bad to get opened urls with xdg-open in that scratchpad window...
So what do you suggest?

**Comment by The-Compiler** [comment]
So to have a different instance in `WM_CLASS` , you will need to pass a separate qutebrowser instance, because Qt only supports setting that value globally (that also means you can't just spawn a separate window in an existing instance, like @ninewise suggested).

To spawn a separate qutebrowser instance, its data and cache need to be separate from the existing instance, because that's what Chromium (and thus QtWebEngine) expect. Thus, what I'm suggesting is that:

- You start a second instance with `--basedir ~/.local/share/scratchqb --qt-flag name scratchqb`
- You log in a second time there (which will be stored in `/.local/share/scratchqb`)
- You move your configuration to a `config.py` file, and symlink that (and only that) to `~/.local/share/scratchqb/config.py`

**Comment by markstos** [comment]
I'll note that the above instructions don't work if qutebrowser is running as Wayland app instead of an X11 app. In that case, "app_id" is used instead of "WM_CLASS", and "app_id" does not end up getting changed.

**Comment by The-Compiler** [comment]
@markstos See #5245

**Comment by prosoitos** [comment]
I have a use case that is slightly different and all the options I have found (including those discussed here and in #5245) don't really work in my case:

**I would like to be able to have different default zoom values for different windows.**

Because I haven't found any way to set this, I have explored options using a 2nd instance, but nothing feels satisfactory:

- Test 1: Using `qutebrowser --config-py file-with-proper-zoom-for-2nd-instance.py`.

For some reason, the zoom is still the zoom of the 1st instance (I guess there must be something in the cache or similar). Note also that I also noticed that the 2 instances are not fully independent as reloading one reloads both.

- Test 2: Using `qutebrowser --temp-basedir --config-py file-with-proper-zoom-for-2nd-instance.py`.

This works for the zoom, but I can't access my bookmarks and quickmarks and because I use those all the time, that is quite a bit limitation.

I have done all sorts of other test copying part of my `~/.config/qutebrowser` files into a new dir and use `--basedir` and a config.py with the proper zoom but I still can't access my bookmarks in the 2nd instance or if I find a way that works, then the default zoom from instance 1 also kicks in and it becomes really messy to have copies, etc.

What I would like is simply to be able to set different zoom values for different windows, keeping all else the same (same cache, same config, same bookmarks, etc.)

## Use case:

For me, it is because I give many workshops and webinars on Zoom and I want to have one window on one monitor with some high zoom (the one I will share with people) and one window on the other screen with normal zoom (for me).

But I can see other use cases for people who have monitors of vastly different sizes and who would like to have different zooms on different screens.

Note that I use i3 and I would be ok to set something using workspace-specific settings, but the situation in #5245 is quite different and doesn't really solve my (much simpler) issue.

Did I miss something? What would you suggest? If there is no easy option, might this be something that could be implemented??

Thank you!!
