### ISSUE TITLE
Make Pygments an optional dependency?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5555]
Pygments is only used in two non-essential places:

- `:view-source` with `--pygments` or with QtWebKit
- `qute://configdiff/old`

For v2.0.0, it might be a good idea to move it to an optional dependency?

**Comment by mschilli87** [comment]
I'm always in favour of dropping dependencies.
Personally, I'd still need Pygments though for docutils which is a dependency of SSHFS.
So I'm not sure how many people could actually drop a package from their system due to this change.
Especially given that unlike Gentoo (where docutils is also pulled in by the default `eselect` package unless one sets `USE=-doc`), most distribution would probably opt to keep including this rather 'cheap' dependency (that every qutebrowser user had installed before anyways) instead of potentially missing out on (optional) features.
