### ISSUE TITLE
Make :undo automatically distinguish between windows/tabs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5628]
It'd be nice if `:undo` could automatically find out whether the last closed thing is a window or a tab, and act accordingly (instead of the user having to do `:undo --window`.

I first thought all that's needed is some kind of `last_close_was_window` boolean which gets set when closing, but that will break things when `:undo` is used multiple times in a row. Right now, the only proper solution I can think of is giving every `_WindowUndoEntry` and `_UndoEntry` a timestamp field, and when using `:undo`, those would be merged and sorted according to that before finding out what action to take. Maybe @toofar can think of something better?

**Comment by user202729** [comment]
* Regarding backward compatibility: should there be an `:undo --last`, or make that `:undo`'s default behavior and `:undo --tab` undoes the last closed tab of the current window?
* Also: Assumes that the list of event so far is

```
tab on window A is closed
window B is closed
tab on window C is closed
```

Then `:undo` is called on window A, should window B be reopened (because it's more recent) or the tab on window A? Assumes the former, should another undo undoes the closure of window B or shows the "nothing to undo" message? (which can be confusing, because then window B can only be undoed from window C)

**Comment by The-Compiler** [comment]
I think it'd be fine for `:undo` to do the automatic thing and have an `:undo --tab` to force undoing a tab instead.

As for the second question: Good point, and I have no idea. This actually turns out much more complex than I thought it would be. Maybe it's best (also from an user perspective) to keep the two separate instead. @user202729 What do you think?

**Comment by The-Compiler** [comment]
Closing this as I think there are too many corner cases to handle this in a consistent way. FWIW other browsers also have separate shortcuts for the two actions.
