### ISSUE TITLE
Scroll bars for overflowing divs no longer render or render only momentarily.

### ISSUE THREAD

**Issue by ervandew** [qutebrowser/qutebrowser#5675]
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When viewing a page with scrollbars on a div, the scrollbars either don't render at all or only render momentarily. I'm noticing the issue on the text field i'm typing this in (vertical scroll bar shows up while typing in this case, but disappears moments after I stop).

I upgraded from qutebrowser 1.11 and Qt 5.14 yesterday when this appears to have started.

**How to reproduce**
https://www.w3schools.com/css/tryit.asp?filename=trycss_overflow_scroll
Note that the scroll bar for the overflow div is missing (shows up in chromium).

**Comment by The-Compiler** [comment]
That's how Chromium's overlay scrollbar (which is the default since v1.13.0) works - you'll see the same with `chromium --enable-features=OverlayScrollbar`. If you prefer normal scrollbars, you can set `scrolling.bar` back to `when-searching` (or `always`).

**Comment by ervandew** [comment]
hmm, curious how their overlay scrollbar is suppose to work since no amount of hovering, clicking, etc renders them again.

**Comment by ervandew** [comment]
actually, if i scroll down with the mouse while hovering it works. to scroll horizontally i have to hover and use the keyboard.

I'll play with that `scrolling.bar` setting, thanks!

**Comment by The-Compiler** [comment]
There's also `OverlayScrollbarFlashAfterAnyScrollUpdate` and `OverlayScrollbarFlashWhenMouseEnter` which you can use (via `--qt-flag enable-features=OverlayScrollbarFlashAfterAnyScrollUpdate,OverlayScrollbarFlashWhenMouseEnter` in qutebrowser, or via `--enable-features=OverlayScrollbar,...` in Chromium).

I didn't enable it by default because I didn't understand what they are supposed to do - I now found a related Chromium bug which explains them: [746342 - Overlay scrollbar incorrectly suggests no more content is available in overflow div - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=746342)

However, on the w3schools site I don't notice any difference in behavior, and on the linked [stackexchange site](https://mathematica.stackexchange.com/questions/6144/looking-for-longest-common-substring-solution) there are persistent scrollbars in there...

Do you have any other example I could test with, or do you see any behavior change with those flags?

**Comment by ervandew** [comment]
My motivating issue is using jira for work. if there is a code block in a ticket i can't scroll that div with the current default settings. the mouse enter feature sounded promising, unfortunately adding those qt-flag features didn't seem to change the behavior. I also can't click the div in jira to focus it since that opens the editor for that field, so on that site I have no way to scroll horizontally.

switching `scrolling.bar` to `always` makes jira usable again for me. seems like the overlay scrollbar needs some usability work upstream.

**Comment by ervandew** [comment]
and just a random side note: Thank you so much for the in window devtools. Makes usage so much better with my xmonad setup.

**Comment by The-Compiler** [comment]
Do you have a scroll wheel? For me on e.g. https://bugreports.qt.io/browse/QTBUG-85863 using that (or actually my middle mouse button + [TrackPoint™-style pointer](https://xkcd.com/243/)) with the mouse being over the codeblock works fine.

You're welcome! Thanks forwarded to @helbling who started it all :slightly_smiling_face:

**Comment by ervandew** [comment]
I use a [Kensington wireless orbit](https://www.kensington.com/p/products/ergonomic-desk-accessorries/ergonomic-input-devices/orbit-wireless-mobile-trackball/), so I have a touch sensitive vertical scroll but no horizontal scrolling.  I also use an external monitor/keyboard so my laptop's touchpad isn't convenient to access either.  perhaps i'm just not the target audience for overlay scrollbars ;)

**Comment by toofar** [comment]
shift+scrollwheel should scroll horizontally too (at least it does for me, I don't think I did anything to set it up)

**Comment by ervandew** [comment]
lol, i think once upon a time i knew about that. good tip!
