### ISSUE TITLE
Stylish in Qutebrowser

### ISSUE THREAD

**Issue by ZaxonXP** [qutebrowser/qutebrowser#5692]
Is there a way to change web pages using similar approach as it is in the Stylish Firefox extension?

Some of the recently visited pages has some content that I would like to remove/change by changing page styles. Is this possible to do this in a current version of `Qutebrowser` or this is something that would have to be implemented?

Regards,
Piotr

**Comment by mschilli87** [comment]
@ZaxonXP: Never heard of that extension so I can't really answer with certainty.
However, if you want to change page styles, your best bet is probably [`content.user_stylesheets`](https://qutebrowser.org/doc/help/settings.html#content.user_stylesheets).

If that doesn't help, maybe you can share some examples (maybe incl. screenshots) highlighting what exactly it is you are after.
Without providing an implementation yourself, however, I would not get my hopes too high to see a new feature request implemented in the short term (unless it turns out to be trivial). There have been a lot of bigger changes in [~Q~q](https://github.com/qutebrowser/qutebrowser/pull/3257#discussion_r149582958)utebrowser recently so there is [quite a backlog with existing contributions](https://github.com/qutebrowser/qutebrowser/projects/4).
Also, there is a chance that this kind of feature won't be added to qutebrowsers core code at all, but rather as an extension (like in Firefox, apparently). In this case, there would be [even more work to be done before](https://github.com/qutebrowser/qutebrowser/projects/4).

**Comment by The-Compiler** [comment]
Agreed, this should be covered once there's per-domain support for `content.user_stylesheet`, see #3636 and #3854.

**Comment by ZaxonXP** [comment]
I think the #3854 covers the feature I was asking for.
