### ISSUE TITLE
Shrink viewport when autocompletion window open

### ISSUE THREAD

**Issue by amacfie** [qutebrowser/qutebrowser#5789]
When the completion window is open, the viewport should shrink to the visible area, i.e. excluding the autocompletion window. Currently the autocompletion window hides stuff at the bottom of the page and there's no way to see it.

Pentadactyl shrinks the viewport like this. I don't see a good reason not to (but I could be wrong). I guess the current behavior is analogous to the Chrome URL bar.

**Comment by The-Compiler** [comment]
It would mean the web contents would jump around - I can't test Pentadactyl right now, but anything I can test (Tridactyl, luakit, vimb) has the same behavior as qutebrowser has, and I only see downsides to changing it.

**Comment by amacfie** [comment]
I just mentioned an upside to changing it. Maybe try it before dismissing it?

**Comment by The-Compiler** [comment]
Can you elaborate what the problem with not seeing text on the page while the completion is open is? I'm willing to reconsider if other people feel the same, but this is the first time this comes up in ~7 years, while the opposite problem (site moving around instead of having an "overlay") comes up again and again with the statusbar/tabbar (for people who have them hidden by default).

**Comment by amacfie** [comment]
If I'm the only one who cares then fair enough, feel free to ignore!

For example, you want to open a url based on some text on the page. If the text is at the very bottom of the page, you can't see it.

**Comment by The-Compiler** [comment]
So I've just tried Pentadactyl (in Pale Moon) as well - it does indeed shrink the viewport, but I don't see how that changes anything about not seeing the text on the bottom of the page. Given that it keeps the top of the viewport at the same position, the effect pretty much seems to be the same for most websites:

![image](https://user-images.githubusercontent.com/625793/95683581-8ff02700-0bec-11eb-90c4-bcfc5eece735.png)

![image](https://user-images.githubusercontent.com/625793/95683586-97afcb80-0bec-11eb-8603-685c5a18c758.png)

**Comment by amacfie** [comment]
Yeah I guess the only difference is you can scroll down.

**Comment by toofar** [comment]
> For example, you want to open a url based on some text on the page. If the text is at the very bottom of the page, you can't see it when you're trying to type it.

I get annoyed by that too. Note that you can set completion.shrink to make the completion go away more easily. It tried binding `config-cycle statusbar.position top bottom` in command mode and that does toggle the statusbar between the top and the bottom but the completion stays where it is until you close and re-open it. (Same with completion.show)

**Comment by bitraid** [comment]
> > For example, you want to open a url based on some text on the page. If the text is at the very bottom of the page, you can't see it when you're trying to type it.
> 
> I get annoyed by that too. Note that you can set completion.shrink to make the completion go away more easily. It tried binding `config-cycle statusbar.position top bottom` in command mode and that does toggle the statusbar between the top and the bottom but the completion stays where it is until you close and re-open it. (Same with completion.show)

I just have the completion bg colors semitransparent.

**Comment by The-Compiler** [comment]
Reopening this for now as a "wishlist" item - right now I suspect it'd be quite messy code-wise to offer both variants (it would need to be configurable because shrinking the viewport would likely be rather disruptive with the completion at the top). But maybe that'll change if/when the tab/statusbar are configurable as an overlay as well and we have some more generic way of attaching widgets either as overlays or "normally".

**Comment by amacfie** [comment]
Better solution: key binding that toggles completion window, e.g.
`bind --mode command <ctrl-space> :config-cycle completion.height 0% 38%`
