### ISSUE TITLE
Switch to tab on notification activation

### ISSUE THREAD

**Issue by peacememories** [qutebrowser/qutebrowser#5796]
At least libnotify allows notification senders to request an action to be performed when the user "activates" the notification (e.g. by clicking on it). Browsers typically use this to focus the tab where the notification originated, so users don't have to manually look over their tabs. I would really like for this behaviour to be at least an option if not the default.

**Comment by The-Compiler** [comment]
Currently the notifications are handled entirely by Qt. This might be possible after #5457 though.

**Comment by chvp** [comment]
Do you have a better idea if this is possible now that #5457 was merged?

**Comment by The-Compiler** [comment]
It's still kind of tricky unfortunately, since qutebrowser doesn't know which tab the notification came from. The only information it gets is the origin (i.e. the hostname, not sure if the path is even included) of the notification. It could in theory try to find the tab using that information, but there will be cases where it's wrong (because there are multiple tabs on the same hostname).
