### ISSUE TITLE
Taking a tab doesn't close the tab if it's the only tab in a window

### ISSUE THREAD

**Issue by drehak** [qutebrowser/qutebrowser#5836]
**Version info**:
qutebrowser v1.11.1
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
If you take a tab to window A from window B using `tab-take`, it's opened in window A and the instance in window B closes, likely through `tab-close`. (This, I presume, is the expected behavior.) However, if the tab is the only tab in window B, `tab-take` doesn't close the tab, so there's a copy in both window A and window B.

**How to reproduce**
1. Open two windows of qutebrowser.
2. From the first window, run: `tab-take 1/0`

**Comment by The-Compiler** [comment]
This is consistent with what happens when you try to close the last tab in a window normally (i.e. via `d`). If you prefer the window to be closed in such cases, you can set `tabs.last_close` to `close`.

However, since this isn't the first time this is coming up (#4979, cc @jhultman), I'm okay with forcing the window to close (no matter what `tabs.last_close` is) in that case.

**Comment by drehak** [comment]
I didn't know about that option, it seems to solve the problem. Thanks for the quick reply!

**Comment by andrewcarlotti** [comment]
This is also an issue with tab-give, though in that case it's less inconvenient to close it as a separate step.

I have tabs.last_close set to ignore because I found that it made it easier to recover from accidentally closing tabs. This usually happened due to thinking I was in insert mode, and then typing something with a 'd' in it.

tab-give and tab-take don't have default key-bindings (and I wouldn't expect anyone add a single-key binding), so I think the main reasons for using the tabs.last_close setting don't apply here. So I'd support either always closing in this situation, or having a "tabs.last_give" setting to determine behaviour in this case. However, I don't think it's a particular important issue.

**Comment by The-Compiler** [comment]
@andrewcarlotti FWIW with `:undo --window` (`Shift-U`) being a thing now, this would only apply if you accidentally close the last tab in the last window (causing qutebrowser to quit).
