### ISSUE TITLE
Using numbers to swap between tabs

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#5883]
Another possible feature could be to use the numbers to swap between tabs. As far as I know the numbers are not used for anything else so it would be great to be able to simply type "3" and jump to tab 3

**Comment by The-Compiler** [comment]
The numbers are used to pass a count to a command, so that you can use e.g. `5j` to go down 5 times, etc.

`:tab-focus` which is bound to `T` takes the tab number as a count already, so you can use e.g. `5T` - in addition to that, `<Alt+[number]>` is bound to switching to those tabs (like in other browsers) as well.
