### ISSUE TITLE
Empty query in searchengine

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#5886]
You should be able to leave the search query blank and come to the home page of the site you are looking for. For example, if you have "y" for youtube, simply writing ":open y" should take you to youtube.com. If its hard to implement you could even let it continue with the query but leaving the string blank. For example if you have no string, "youtube/results?seach_query=" still takes you to youtube which is preferable to going to duckduckgo with the search "y".

**Comment by The-Compiler** [comment]
It's unclear what the proper behavior would be (what is the "home page of the site"? Is it just an empty query? Removing the query? Something else?) which is why this isn't the default behavior. You can set `url.open_base_url` however, to open the engine with an empty search term.

Alternatively, you can add a `y` quickmark pointing to YouTube, which then also is used when using `:open y`.

**Comment by premell** [comment]
Oh my bad,  I didnt know "url.open_base_url" existed! Should be the default imo
