### ISSUE TITLE
Right-click makes qutebrowser crash on OS X Big Sur

### ISSUE THREAD

**Issue by maxime-michel** [qutebrowser/qutebrowser#5896]
**Version info**:
qutebrowser v1.14.0
Git commit: f5a25c429 on HEAD (2020-10-15 14:42:10 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I upgraded to Big Sur on Friday and was running into qutebrowser crashes here and there. I only now found out how to reproduce them consistently. I'm not really sure what is happening behind the scenes, though.

**How to reproduce**
1. Open qutebrowser with ``--temp-basedir``
2. right-click in the unloaded or loaded DuckDuckGo default window (or in any other site for that matter)
3. qutebrowser becomes unresponsive and never recovers, with high CPU usage

**Comment by The-Compiler** [comment]
There is some previous discussion about this in https://github.com/qutebrowser/qutebrowser/issues/5663#issuecomment-726823643 but I agree it'd be good to have a separate issue about it.

Can you (and/or someone else affected) please try creating a `~/.qutebrowser/config.py` with something like:

```python
import os
config.load_autoconfig()
os.environ['QT_MAC_WANTS_LAYER'] = '1'
```

and see if that changes anything?

**Comment by maxime-michel** [comment]
I'd not seen that the right-click issue was brought up in there. Your snippet works around the issue, though. I can resume using the browser. Thanks!

**Comment by The-Compiler** [comment]
Interesting, so this is probably the same bug as this: [[QTBUG-87014] Qt application gets stuck trying to open main window under Big Sur - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-87014)

There's a fix in the works for Qt 5.15.3: [macOS: Account for Big Sur always enabling layer backed views (I867edc00) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/322228)

And apparently PyQt 5.15.2 will fix it as well: [PyQt5 and Big Sur](https://www.riverbankcomputing.com/pipermail/pyqt/2020-November/043399.html)

So I'm guessing this will be fixed with the next release - still keeping this open until someone can confirm when it's ready.

@maxime-michel Could you check if it changes anything about the rendering issues as well (assuming that you see those too), and comment on #5663 about that?

**Comment by The-Compiler** [comment]
PyQt 5.15.2 was released today, and I built a preliminary dmg with the latest v1.14.x branch of qutebrowser: https://t.cmpl.cc/qutebrowser-1.14.1-pre.dmg - it should fix both the styling issues (with the default font) and the hangs, could someone confirm?

**Comment by cgrinds** [comment]
@The-Compiler I can confirm this fixes the issue on Big Sur. Thanks!

**Comment by The-Compiler** [comment]
Amazing! Closing this then, the fix will be in the next release - that'll either be v1.14.1 or v1.15.0, and hopefully happen over the next couple of days.
