### ISSUE TITLE
Add units to :later command

### ISSUE THREAD

**Issue by Soundtoxin** [qutebrowser/qutebrowser#5934]
Similar to how the `sleep` shell command works, it would be nice if you could do `:later 5s` instead of `:later 5000`, and it becomes even more useful if you want to do increments like 30 minutes or 24 hours, where converting to ms would be very troublesome.

**Comment by The-Compiler** [comment]
I wonder if it should be possible to combine e.g. "1m 30s"? If so, this would either need to be quoted:

```
:later "1m 30s" message-info test
```

or without a space:

```
:later 1m30s message-info test
```

though I suppose the former would be easier to parse.

---

This should be a good first contribution - if someone wants to tackle this, the steps would roughly be:

- Add some tests to `tests/unit/utils/test_utils.py` testing the expected behavior - you can take `test_format_seconds` as an example, this would almost be the opposite (but with a slightly different format).
- Add a `parse_duration` function to `qutebrowser/utils/utils.py` implementing the parsing (taking a string like mentioned above and returning milliseconds)
- Change the `later` command in `qutebrowser/misc/utilcmds.py` to use this new function.

**Comment by m-zat** [comment]
@The-Compiler I would be interested to contribute to this issue as first contribution to Qutebrowser.
Just wondering what would be the specs for this feature:

1. if `int` is input shall we keep backward compatibility and assume milliseconds?
2. where do we want to stop? Maybe maximum could be hours? For instance valid could be `3h32m29s`.

I'd try to implement the one without spaces as I prefer to avoid double quotes when invoking a command
