### ISSUE TITLE
InsertEnter and InsertLeave hooks for qutebrowser

### ISSUE THREAD

**Issue by pspiagicw** [qutebrowser/qutebrowser#5954]
I am using qutebrowser with EXWM(Emacs) and want to run a command while entering insert mode and leaving insert mode in qutebrowser.I saw the documentation but could not able to pull it off.Is there a hack to this.

If the feature is not available then it would be of great help.

**Comment by The-Compiler** [comment]
See #35 - there might be a way to hack this in `config.py`, but I haven't gotten around to answering to [your Reddit post](https://www.reddit.com/r/qutebrowser/comments/k7ncqf/way_to_provide_insertenter_and_insertleave_hooks/) yet. I'll post there if I manage to cook up something.

**Comment by lrustand** [comment]
I managed to do this using the following code:

```
from qutebrowser.keyinput import modeman
from qutebrowser.utils import objreg
from qutebrowser.mainwindow import mainwindow

def on_enter_insert_mode(mode):
    message.info(f"Entered {mode}")

def on_leave_insert_mode(mode):
    message.info(f"Left {mode}")

mode_manager = modeman.instance(objreg.last_visible_window().win_id)
mode_manager.entered.connect(on_enter_insert_mode)
mode_manager.left.connect(on_leave_insert_mode)
```

The only problem I had with this code is that it crashes if it runs during startup of qutebrowser, but it works fine if you source it after the browser has started.

**Comment by lrustand** [comment]
I found out that the above code only works for a single window, so I added a hook to the new window signal as well. My code now looks like this:

```
from qutebrowser.api import message
from qutebrowser.keyinput import modeman
from qutebrowser.misc import objects

def on_enter_insert_mode(mode):
    message.info(f"Entered {mode}")

def on_leave_insert_mode(mode):
    message.info(f"Left {mode}")

def on_new(window):
    mode_manager = modeman.instance(window.win_id)
    mode_manager.entered.connect(on_enter_insert_mode)
    mode_manager.left.connect(on_leave_insert_mode)

objects.qapp.new_window.connect(on_new)
```
After making these changes, the mode enter/leave hooks trigger in all windows. I still have the problem that the code fails at startup though. I have tracked down the reason for this problem to the following part of `app.py`:

```
    log.init.debug("Initializing config...")
    configinit.early_init(args)

    log.init.debug("Initializing application...")
    app = Application(args)
    objects.qapp = app
```
Since the qapp is not initialized at the point the config file is being initialized, setting up the new window hook fails. I have noticed that there is both a function called `configinit.early_init`, and a function called `configinit.late_init`. The late init seems to be late enough that the qapp show be initialized, but I cant figure out how I can mark any lines in my config to be executed in the late_init instead of early init. How can I do this?

**Comment by anyakichi** [comment]
We can do it, but with a dirty hack...

```
import qutebrowser.app
from qutebrowser.api import message
from qutebrowser.keyinput import modeman


def on_entered(mode):
    message.info(f"Entered {mode}")


def on_left(mode):
    message.info(f"Left {mode}")


def on_new_window(window):
    mode_manager = modeman.instance(window.win_id)
    mode_manager.entered.connect(on_entered)
    mode_manager.left.connect(on_left)


class MyApplication(qutebrowser.app.Application):
    def __init__(self, args):
        super().__init__(args)
        self.new_window.connect(on_new_window)


qutebrowser.app.Application = MyApplication
```
