### ISSUE TITLE
Allow sourcing bookmarks and quickmarks from user defined location

### ISSUE THREAD

**Issue by bunwayenterprises** [qutebrowser/qutebrowser#6051]
At the moment qutebrowser allows you to source the config file from an alternate location at runtime with the `-C` option, while the quickmarks and bookmarks files are limited to the base config directory.

It would be great if it could also allow sourcing of bookmarks and quickmarks from outside of the base config directory, either by adding something like `--bookmarks-location $PATH` and `--quickmarks-location $PATH`, or allowing the paths to be specified as options in the config file.

**Comment by The-Compiler** [comment]
Can you elaborate on why/how you'd use this?

**Comment by bunwayenterprises** [comment]
No problems :)

At the moment i'm using NixOS with home-manager.

Home manager dynamically builds your dotfiles to allow a stateless and reproduceable user configuration. To make it stateless it locks the files that it creates by marking them as read only. Any changes require a rebuild of your dotfiles with home-manager. 

Since the bookmark and quickmark files are read-only, saving bookmarks and quickmarks from within qutebrowser won't work.

I keep my dynamic data and for various applications in a different location and would like to keep my bookmarks and quickmarks there also.

**Comment by The-Compiler** [comment]
Can't you just symlink them there? I'd rather not do this, otherwise we'd need to have a flag/setting for all the files qutebrowser stores. `config.py` is a bit of a special case, because qutebrowser doesn't write to it (so you can e.g. share it between different instances with different `--basedir` flags).

**Comment by bunwayenterprises** [comment]
I can do, no problem there.

Thought it might be a useful feature to keep user data out of config.

Feel free to close if you don't think it adds any value.

**Comment by The-Compiler** [comment]
Closing this then, as I'm afraid I don't think this will scale (and having configurable filepaths for everything adds quite a bit of complexity).

**Comment by Gochkin** [comment]
Apologies for surfacing this old issue. I would also like to express my interest in the ability to dynamically load quickmarks.

Here are my potential use cases:

1. Managing Multiple Browser Contexts: As a software engineer, I frequently launch separate browser instances with different base directories (using `--basedir` or `--temp-basedir`). I do this for several reasons:

    - To test features or run automation scripts in a clean browser environment.
 
    - To log into a single platform with multiple user accounts simultaneously, which is necessary for sites that only allow one logged-in session at a time.

    In these scenarios, it would be extremely useful to have all my standard quickmarks available without having to manually configure them for each new context.

2. Modularizing Quickmark Files: I would like to split my quickmarks into different files based on their purpose (e.g., 'work' and 'personal'). This would make management much simpler. For example, if I were to leave a workplace, I could just delete the corresponding quickmark file rather than manually removing each now-irrelevant entry from a single, monolithic file.

I am mindful of not wanting to add unnecessary complexity to the codebase or its maintainability. With that in mind, I have two potential solutions to propose.

### Proposal 1: Simple, Read-Only Import
A straightforward solution could be to introduce a new configuration directive in `config.py`.

Functionality: This directive would allow a user to specify one or more additional quickmark files to be loaded in a read-only state.

Management: These imported quickmarks could not be changed or deleted from within the qutebrowser UI. Management would be handled by the user editing the files directly. Users comfortable with config.py are typically capable of this.

Benefit: This approach would add the desired functionality with minimal changes to the existing code for adding, changing, and deleting quickmarks, which would continue to work with the default quickmarks file as usual.

### Proposal 2: Flexible, Settings-Based Approach
A more powerful, though potentially more complex, alternative would be to treat quickmarks like any other browser setting, similar to how search engines are defined (c.url.searchengines).

Functionality: This would allow quickmarks to be defined and managed directly within `config.py` and through the qutebrowser UI.

Benefit: This method would offer the most power and flexibility, creating a unified system for managing quickmarks from either the configuration file or the browser interface.
