### ISSUE TITLE
Tab focus behaviour changed after upgrade to v2.0.1

### ISSUE THREAD

**Issue by zimhat** [qutebrowser/qutebrowser#6125]
**Version info**:

qutebrowser v2.0.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
**Does the bug happen if you start with `--temp-basedir`?**:
Yes it does
**Description**
Before upgrading to 2.0.1, ``right-click -> open link in new tab`` kept the focus on the page where the link was and not the new tab. It had the same behaviour as ``ctrl - left-click``. Now the focus is on the new tab with right-click. I tried looking into the settings but I couldn't find a way to set it up as it used to be.

**Comment by The-Compiler** [comment]
That's because `tabs.background` got set to `true` - if you set it to `false` again, you will get the original behavior back.

It sounds confusing, but the underlying issue is similar to #3231. Having a custom context menu (#349) would likely allow to fix this properly, but in the meantime you might also want to use hints instead (i.e. `f` and friends).
