### ISSUE TITLE
不支持MP4,videos.js视频播放

### ISSUE THREAD

**Issue by huaxing88** [qutebrowser/qutebrowser#6146]
https://videojs.com/
这个网站里面的视频都不能正常显示，这样对浏览器来说很不友好！

**Comment by The-Compiler** [comment]
This works fine if you have a QtWebEngine with proprietary codecs installed. The Windows and macOS releases of qutebrowser come without proprietary codecs, because distributing them needs a license and requires recompiling the QtWebEngine library from source (which is a pain).

---

自动翻译（由[DeepL](https://www.deepl.com/translator)）。如果你的QtWebEngine安装了专有的编解码器，这就可以正常工作。Windows和macOS版本的qutebrowser没有专有的编解码器，因为发布它们需要许可证，并且需要从源码重新编译QtWebEngine库（这很麻烦）。

**Comment by huaxing88** [comment]
Recompiling the QtWebEngine library from source.Can this support Pyqt5?

**Comment by The-Compiler** [comment]
Yes, if you also [build PyQt5 from source](https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#building-and-installing-from-source) and use `--qmake` to point to your custom Qt's qmake binary.
