### ISSUE TITLE
macos: can't scroll through tabbar

### ISSUE THREAD

**Issue by neeasade** [qutebrowser/qutebrowser#6148]
**Version info**:

qutebrowser v2.0.2
Git commit: f11cdd0bf on HEAD (2021-02-04 10:19:33 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
running the scrollwheel with the mouse hovered over the tabbar on macos doesn't cycle through tabs

**How to reproduce**
NA/description

**Comment by The-Compiler** [comment]
I think Qt does some special stuff to use macOS' tab implementation for its `QTabBar`, which might be causing this. I'll try to take a closer look sometime soon, haven't gotten around to it yet.

**Comment by The-Compiler** [comment]
I can reproduce - it looks like this is deliberately ignored in Qt:

- [[QTBUG-8428] wheel event should not change active tab - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-8428)
- [QTabBar: Disable wheel events on Mac (Ifab663b4) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/109523)

Here's the Qt 5.15.2 doing so: https://github.com/qt/qtbase/blob/v5.15.2/src/widgets/widgets/qtabbar.cpp#L2325-L2352
It looks like Qt 6 made it configurable: https://github.com/qt/qtbase/blob/v6.1.0-alpha1/src/widgets/widgets/qtabbar.cpp#L2363-L2386 ([control scrolling of QTabBar using StyleHint (I99eeb5a1) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/327746)).

We already override `wheelEvent` for the `tabs.mousewheel_switching` option, so we might as well just reimplement those couple of lines of logic for macOS instead of relying on the Qt implementation...
