### ISSUE TITLE
Throttle/debounce/delay audible status ([A]) in tabs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6168]
This used to be done by Qt, but isn't anymore in more recent versions, so `[A]` can get added/removed somewhat erratically. We should delay it (maybe using `misc.throttle`?) so it's a bit smoother.

(I thought there was an issue about this already, but I don't think so?)

**Comment by chimak111** [comment]
In addition to adding a delay, is it possible to replace `[A]` with an equivalent length of blank space to eliminate the sliding effect each time `[A]` appears or disappears?

**Comment by toofar** [comment]
> In addition to adding a delay, is it possible to replace `[A]` with an equivalent length of blank space to eliminate the sliding effect each time `[A]` appears or disappears?

I believe that has been discussed before and some people didn't want that because it would make all the other tab titles have pointless leading whitespace, which seems sensible. And if you did it just for tabs that had ever been audible you may still be annoyed at it for tabs that only made noises occasionally. So maybe it would be equivalent whitespace for a only a while which would mean another timer. Possibly we could make it get the audibility prefixes from the custom function but that should probably wait until tabs are part of the extension API.

**Comment by The-Compiler** [comment]
Also see #4089 which provides a hack to set those texts.

**Comment by laalsaas** [comment]
> > In addition to adding a delay, is it possible to replace `[A]` with an equivalent length of blank space to eliminate the sliding effect each time `[A]` appears or disappears?
> 
> I believe that has been discussed before and some people didn't want that because it would make all the other tab titles have pointless leading whitespace, which seems sensible.

Hey, What about displaying the [A] at the right edge of the Tab, so basically how it is done with the Speaker logo in Firefox and Chromium? For me, this does seem like a good idea, but i don't know how much programming-effort this would add.

**Comment by The-Compiler** [comment]
@laalsaas You can do that by changing `tabs.title.format` already.

**Comment by amacfie** [comment]
Qt bug? We check `page.recentlyAudible()` which is "whether audio was _recently_ played". There's some stuff in Chromium [here](https://chromium.googlesource.com/chromium/src/+/master/chrome/browser/ui/recently_audible_helper.h) about setting the recently audible status based on a timer.

**Comment by The-Compiler** [comment]
I guess we could open a QtWebEngine issue as well, but we'd still need a workaround until a fix actually arrives and we drop older versions. Given that a fix should be relatively simple, I don't really see the point of reporting this upstream.

**Comment by gerrywastaken** [comment]
Firstly **Quickfix**. Put the audio segment at the end (probably invisible, but won't cause a shift when the state changes. 
`config.set('tabs.title.format', '{index}:{current_title}:{audio}')`

Note: You can also move the index numbers if you never actually used them. 

This ticket was really difficult to find given a search for "A" doesn't work so well. :) So I'll add some keywords for others:
Youtube title flickering when playing "[A]" "A" audio AUDIBLE_STRING

Finally I noticed that there is a green bar to far left of all tab titles indicating the page has loaded. Is it possible to just change that to blue when audio is playing? It's always there so wouldn't lead to shifts in the title and I think changing that would be much cleaner than an [A]. Just a thought.

**Comment by gerrywastaken** [comment]
I tried out a  (seriously non-prod ready and even dangerous code) bodge implimentation of the above idea:
qutebrowser/mainwindow/tabwidget.py:147 (inside update_tab_title)
```py
        if fields['audio'] != '':
            self.set_tab_indicator_color(idx, QColor('pink'))
        else:
            self.set_tab_indicator_color(idx, QColor('green'))
```

Despite how bad the code is, I really love the effect. Even though it still changes when the audio is quite, this allows me to instantly spot which tab is my music or video from the tab with the annoying ad that started playing. This was always an issue for me in Chrome or Firefox when I had a lot of tabs. There would normally be one tab playing something I wanted and one playing something I didn't ask for and finding them still not super fast. Because it's a thin strip it isn't distracting when you are not looking for it and actually really nice when you are.

**Comment by The-Compiler** [comment]
Reported upstream as well: [[QTBUG-98918] [REG] recentlyAudible does not implement 2s cooldown anymore - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-98918)
