### ISSUE TITLE
Feature request: allow userscripts to use native qutebrowser prompts/selection

### ISSUE THREAD

**Issue by ethan-leba** [qutebrowser/qutebrowser#6178]
I've noticed that many of the qutebrowser userscripts in the repository rely on `dmenu`, which is not available on MacOS or Windows. It would be a great feature to be able to utilize the native qutebrowsers prompts or selection menus in a userscript to make writing cross-compatible scripts easy!

**Comment by The-Compiler** [comment]
The communication between userscripts and qutebrowser is unidirectional - i.e. there are no ways for qutebrowser to send things back (other than the initially provided values via environment variables).

There is no plan to change this, because it'd mean we'd need to rely on a more sophisticated protocol between userscripts and qutebrowser, which compromises the simplicity of writing a userscript.

For more sophisticated things, the plan is to cover them via a future Python extension API (see #30) which would then make it possible to use qutebrowser's prompts and completion as well.

Note that userscripts can already use PyQt to display simple prompts in a platform-independent way, see e.g. [qute-keepass](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-keepass) or [add-nextcloud-bookmarks](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/add-nextcloud-bookmarks).

Finally, at least for Windows I suspect you can already run dmenu/rofi with WSL (if the GUI support in WSL landed already, not sure). For macOS, there might be a way to run an X server as well - but no idea how well this actually works for either of those. Maybe there are also native drop-in alternatives which behave the same way.

**Comment by The-Compiler** [comment]
Also somewhat related, though only for prompts rather than completions: https://github.com/qutebrowser/qutebrowser/issues/3007#issuecomment-792681321
