### ISSUE TITLE
v2.0.2 release assets missing

### ISSUE THREAD

**Issue by mcastorina** [qutebrowser/qutebrowser#6196]
I think some of the assets are missing from the v2.0.2 release page: https://github.com/qutebrowser/qutebrowser/releases/tag/v2.0.2

This also causes `scoop` to fail installation on Windows:

```
Installing 'qutebrowser' (2.0.2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/qutebrowser/qutebrowser/releases/download/v2.0.2/qutebrowser-2.0.2-windows-standalone-amd64.zip is not valid
```

**Comment by The-Compiler** [comment]
I deleted them some 10 minutes ago because I'm regenerating them due to #6194. I ran into some issues, but they will be up again in a couple of minutes if everything works alright now.

**Comment by The-Compiler** [comment]
They are now up again, though Chocolatey/Scoop/... will need some adjustment because the checksums and filenames changed.

Pulling the old releases clearly wasn't a good decision, I didn't consider that it'd break those package managers...

Also pinging @Ash258 and @AeliusSaionji to make them aware. Sorry for the trouble! :sweat_smile:. Note that the version number in the file- and directory names changed to `2.0.2.post1` too.

**Comment by mcastorina** [comment]
Haha, what a coincidence! I was wondering why no one noticed.

Thanks for the fast response :)
