### ISSUE TITLE
Support directory in external file pickers

### ISSUE THREAD

**Issue by pastalian** [qutebrowser/qutebrowser#6218]
Although not exposed as [FileSelectionMode](https://doc.qt.io/qt-5/qwebenginepage.html#FileSelectionMode-enum), qtwebengine has a directory selection mode.
When this mode is selected, the external picker's directory selection option should be used.

See: https://github.com/qt/qtwebengine/blob/dev/src/core/file_picker_controller.h#L65-L70

**Comment by The-Compiler** [comment]
I guess there's a reason it's not exposed? Do you have an example website where this is actually used?

**Comment by pastalian** [comment]
Onedrive, Google Drive, major cloud storage service sites use this.

https://codereview.qt-project.org/c/qt/qtwebengine/+/74325
`// Chromium extension, not exposed as part of the public API for now.`
It's 7 years old comment, I don't think there is a real reason anymore.

**Comment by The-Compiler** [comment]
Right, looks like the [`webkitdirectory` attribute](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) causes this to happen, and like you say it seems to be used commonly, despite [being non-standard](https://caniuse.com/mdn-api_htmlinputelement_webkitdirectory). I found a [demo page](https://codepen.io/monjer/pen/JKRLzM) as well.

The enum value is `2` and our `chooseFiles` overload gets called, so we could indeed implement support for it. @AckslD is this something you'd like to work on? Here's what I'd propose:

- Add a new `FileSelection` enum in `shared.py` with values `open_single`, `open_multiple` and `upload_folder` or so (let's not care about the `save` one [in the code](https://github.com/qt/qtwebengine/blob/dev/src/core/file_picker_controller.h#L65-L70), as I can't find a way to actually trigger it).
- Rewrite the existing code to use those enum values instead of a `multiple` boolean argument. It should probably have a dictionary mapping the QtWebEngine values to our enum, with `2` hardcoded as a key for the directory mode (and an appropriate comment).
- For future-proofing, it should log a warning and call the superclass implementation if it gets any value other than those three.
- Also add a new end2end test for `webkitdirectory`.

**Comment by AckslD** [comment]
Sounds good @The-Compiler, I'll take a look at it

**Comment by The-Compiler** [comment]
Also reported to Qt now: [[QTBUG-91489] Missing FileSelectionMode::FileSelectUploadFolder member - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-91489)
