### ISSUE TITLE
Is it possible to run a Greasemonkey function inside :jseval?

### ISSUE THREAD

**Issue by Gira-X** [qutebrowser/qutebrowser#6303]
I am using this Greasemonkey script with some dummy calls:

```
// ==UserScript==
// @name         Test
// @match        *://*/*
// ==/UserScript==

function hey() {
    alert('hi')
    window.scrollBy({top: -300, left: 0, behavior: 'smooth'});
}

hey() // just as a test to see if the script loads
```

In my config, I have this set:`config.bind("q", "jseval -w=main hey()")`
Calling it always shows `No output or error`, even when I use some other non-existing function.
Same behavior when the `alert()` call is removed and any other code is used there instead.

**Comment by The-Compiler** [comment]
Please use [discussions](https://github.com/qutebrowser/qutebrowser/discussions) rather than issues in the future for support questions.

By default, `:jseval` commands run in a separate JS world (i.e. context/scope) than Greasemonkey scripts do. This should work if you add `--world=main`, see `:help :jseval`.

**Comment by toofar** [comment]
You might have to bind the function to `unsafeWindow` in the greasemonkey script to call it via jseval (in the main world). At least that is what I set up some time ago one thing I use like that.
For the "no output or error" thing make sure you check the developer tools console too because not all errors are reported that way.

**Comment by Gira-X** [comment]
> Please use discussions rather than issues in the future for support questions.

I will!

---

Just now I tried with `config.bind("q", "jseval --world=main hey()")` and it also does not work.

**Comment by Gira-X** [comment]
Aha, so this is what worked in the end:

```
unsafeWindow.hey = function() {
    alert('hi')
    window.scrollBy({top: -300, left: 0, behavior: 'smooth'});
};
```

```
config.bind("q", "jseval --world=main hey()")
```

Thanks for the info about `unsafeWindow`. Maybe it could be noted somewhere?

**Comment by The-Compiler** [comment]
That's just [a standard Greasemonkey thing](https://wiki.greasespot.net/UnsafeWindow), not qutebrowser-specific. I don't think it makes sense for qutebrowser to replicate Greasemonkey's documentation.

Also, depending on your use-case, it might be a better solution to use `@qute-js-world jseval` in the userscript instead - otherwise, you're injecting the code to the web page's JS world, which might conflict with things done by the website you visit.

Finally, note that you can use `:jseval -f` to evaluate a file, so you might not need Greasemonkey at all.
