### ISSUE TITLE
qute-bitwarden script fails to find username and password

### ISSUE THREAD

**Issue by frnkshin** [qutebrowser/qutebrowser#6376]
**Version info**:
qutebrowser v2.1.0
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.0

sip: 4.19.24
colorama: no
jinja2: 2.11.3
pygments: 2.6.1
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1k  FIPS 25 Mar 2021**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
Installing `Bitwarden CLI (or bw)` from `Snap` on `Fedora version > 32` produces a `stderr` output which reads:
`WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement`.
Because this is treated as an error, not a warning, the `pass_` function returns an empty list `[]`.

Quick work-around is to add `and not err.startswith("WARNING"):` to line 157 of `qute-bitwarden` script for anyone who's encountering the same issue.

**How to reproduce**
1. `# snap install bw`
2. `$ bw login`
3. `:spawn --userscript qute-bitwarden`
4. `:messages` to observe the issue.

**Comment by The-Compiler** [comment]
cc @JonnyHaystack @typerslow - maybe the script should check the exit status of `bw` instead of checking whether there's something on stderr?

https://github.com/qutebrowser/qutebrowser/blob/f22ea9b81d5b2aeba21c02eb13786b49f499aff0/misc/userscripts/qute-bitwarden#L156-L160

I guess it could still print the error, but only abort when the exit status was != 1.

**Comment by JonnyHaystack** [comment]
Sorry for late reply. Yeah I agree it would for sure be better to check exit status. I can't remember exactly how it works currently.
