### ISSUE TITLE
text: in statusbar is undocumented

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6414]
See #6413 - cc @markstos @Nicholas42

**Comment by Nicholas42** [comment]
I thought I documented that, but it seems I missed it. Will fix soon.

**Comment by The-Compiler** [comment]
Right, I was confused by @markstos' PR, it's in there actually:

> List of widgets displayed in the statusbar. In addition to the listed values there is also the possibility to add `text:foo` widgets that will display `foo`.

I don't think it's worth the trouble trying to add this to the generated "Valid values:" list below that.

**Comment by Nicholas42** [comment]
Yes, I agree, that would be overkill.

**Comment by markstos** [comment]
I disagree. 

I read through the current list twice to be sure I didn't see `text:` in there before writing the patch. I see now it's there, but it's inconsistent to list all the valid values but one in the list, and include the final valid value in the paragraph description. 

I think it would be clearer and more consistent to remove it from the description but have in the list.

**Comment by Nicholas42** [comment]
The problem is that this part of the documentation is generated from the valid values. But `text:` has to be handled separately due to it having an argument. I think that the only option to get its documentation at the same point, without completely reworking that part of the documentation generation, is to add `text` or `text:` as an allowed value. That's a bit hacky but not that bad, in my opinion. If @The-Compiler is fine with that I can do a pull request, should be pretty straight-forward.

**Comment by The-Compiler** [comment]
Right, I didn't consider that possibility. That might actually work out nicely, and also add the `text:` value as a choice in the completion.
