### ISSUE TITLE
Keep file extension when renaming

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6511]
At the moment the file extension is removed when you name downloaded files, so you have to write it aswell. Chrome and firefox have so that you just name the file and the extension name is reattached at the end.

**Comment by The-Compiler** [comment]
I don't like the idea of appending the extension - and neither Chrome nor Firefox do so for me. If an user enters `somefilename` without an extension, it should be saved there.

What Chrome and Firefox do however is highlighting the filename part (without extension) so that it doesn't need to be retyped. You can set `downloads.location.suggestion` to `both` to get something similar, minus the initial selection - which is already tracked in #3874, so I'm closing this.
