### ISSUE TITLE
Alt+num can not switch tabs on Windows 10

### ISSUE THREAD

**Issue by dinkocar** [qutebrowser/qutebrowser#6526]
**Version info**:
qutebrowser v2.2.3
Git commit: f35f56eca on HEAD (2021-06-01 18:31:44 +0200)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.4
PyQt: 5.15.3

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When I try to switch tabs with Alt+num passthrough mode is activated, and tab is not switched.
When I run debug-keytester and press Alt it says that I have pressed Alt, but when I press Alt+num (any number from 0-9) it says that I have pressed Ctrl-v which is command for passthrough mode.
This only happens on my Win10 laptop, Linux version works as expected. I use Croatian keyboard on Windows and Linux.
I have this issue since version 1.X, but I was too lazy to report, so this is not something introduced in newer versions.

**How to reproduce**
See description.

**Comment by The-Compiler** [comment]
Works fine in my Windows VM. The keytester widget [is quite simple](https://github.com/qutebrowser/qutebrowser/blob/v2.2.3/qutebrowser/misc/miscwidgets.py#L486-L506) and pretty much directly displays what it got from Qt, so this doesn't seem like a qutebrowser-specific issue.

Can you show a screenshot from the keytester so I can take a look at the other values as well? Do you have any software which might mess with system-wide key bindings? What happens if you press those shortcuts in other browsers (like Firefox or Chrome)?

**Comment by dinkocar** [comment]
OMG. I had clipboard manager which I haven't used for quite some time. It uses Alt+num for pasting clipboard entries, and that is why I was getting Ctrl-v. I have changed it to use different key combo, and now Alt+num works in qutebrowser.

**Comment by The-Compiler** [comment]
[One of those strange issues](https://twitter.com/the_compiler/status/1401958396220395523) solved then! Thanks for the quick update :slightly_smiling_face:
