### ISSUE TITLE
Add python-tldextract as an optional dependency for the archlinux packages

### ISSUE THREAD

**Issue by noahares** [qutebrowser/qutebrowser#6528]
Using the qute-pass userscript requires python-tldextract, but it is not listed as an optional dependency for the qutebrowser and qutebrowser-git packages on archlinux.
I don't like having dependency packages installed without `--asdeps` and I like to clean-up my orphaned packages regulary, such that tldextract is removed in the process, which is annoying.
Is there any reason not to include it as an optional dependency? Otherwise I would be happy if this was added to the PKGBUILDs.

**Comment by The-Compiler** [comment]
I've discussed this with the Arch maintainer - since the userscripts are pretty much a kind of "contrib" part (and not part of qutebrowser itself, just distributed it for convenience), and it's hard to draw the line what would be an optional dependency and what wouldn't be, we agreed to not include them:

**Comment by noahares** [comment]
Alright, thanks for the info.
