### ISSUE TITLE
qutebrowser does not resolve IPv6 addresses of yggdrasil (.ygg / .anon) sites.

### ISSUE THREAD

**Issue by Oxyd76** [qutebrowser/qutebrowser#6557]
**Version info**:

[qutebrowser v2.3.3 on Manjaro Linux](https://paste.the-compiler.org/view/4674064a)

**Does the bug happen if you start with `--temp-basedir`?**:

Yes. This bug is happen with `--temp-basedir` and cleared profile.

**Description**

My system is configured with `systemd-networkd` and `systemd-resolved` and `yggdrasil` IPv6 network.
My router sends IPv4 addresses and DNS for clearweb via DHCP. IPv6 address and DNS of yggdrassil network configured via `systemd-networkd`. If i am try to open yggdrasil site via IPv6 address, all ok. If i am try to resolve yggdrasil site via `dig` / `nslookup` also all ok. Also sites succefully opens via other browsers (Palemoon, Brave). qutebrowser does not open sites with `ERR_NAME_NOT_RESOLVED` error.

**How to reproduce**

[Debug log](https://termbin.com/tyrm) (`qutebrowser --temp-basedir -d` and try to open http://flibusta.ygg)

_Resolve site via dig and nslookup:_
`dig IN AAAA flibusta.ygg`:

```; <<>> DiG 9.16.16 <<>> IN AAAA flibusta.ygg
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46966
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;flibusta.ygg.                  IN      AAAA

;; ANSWER SECTION:
flibusta.ygg.           547     IN      AAAA    304:4738:37c6:d295::7

;; AUTHORITY SECTION:
ygg.                    547     IN      NS      ns.alfis.name.

;; Query time: 6 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Jun 18 07:30:07 MSK 2021
;; MSG SIZE  rcvd: 96
```

`nslookup flibusta.ygg`:

```
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   flibusta.ygg
Address: 304:4738:37c6:d295::7
```
Also site succesfully opened via Brave browser.
![image](https://user-images.githubusercontent.com/7885175/122507406-d104ca80-d008-11eb-88d5-9efb49bbdd27.png)

**Comment by The-Compiler** [comment]
Could you try with another QtWebEngine-based browser, such as [KDE Falkon](https://www.falkon.org/)?

**Comment by Oxyd76** [comment]
> Could you try with another QtWebEngine-based browser, such as [KDE Falkon](https://www.falkon.org/)?

I'm install KDE Falkon, and got the same error. Now I try to switch to qtwebkit.

**Comment by The-Compiler** [comment]
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

As for QtWebKit, note that it's based on a WebKit from September 2016 with no process isolation/sandboxing and no security fixes for years.
