### ISSUE TITLE
Qt components

### ISSUE THREAD

**Issue by ruby-zen** [qutebrowser/qutebrowser#6605]
### Discussed in https://github.com/qutebrowser/qutebrowser/discussions/6604

<div type='discussions-op-text'>

<sup>Originally posted by **ruby-zen** July 16, 2021</sup>
None of the components that are listed under `Qt` (see below) are available in the Custom Installation of the latest Qt open source installer version `6.1.1` (there are other versions as well). Could you please say what components must be selected in the custom installation of the Qt installer? There are no components by any of the names given below. I am new to this. Could you please say what components must be selected?

```
Qt 5.12.0 or newer (5.12 LTS or 5.15 recommended) with the following modules:

QtCore / qtbase

QtQuick (part of qtbase or qtdeclarative in some distributions)

QtSQL (part of qtbase in some distributions)

QtDBus (part of qtbase in some distributions; note that a connection to DBus at runtime is optional)

QtOpenGL

QtWebEngine, or

alternatively QtWebKit (5.212)
```</div>

**Comment by The-Compiler** [comment]
The list is correct. There's no clear mapping from the list of [Qt Modules](https://doc.qt.io/qt-5/qtmodules.html) (which the README refers to, and which is how Qt is usually packaged on distributions) to those installer components.

That being said, you'll need Qt 5 with the base install and QtWebEngine - but installing Qt binaries seems like a very cumbersome way of getting things up and running (because you still need to build PyQt from sources, with no benefits over just using PyQt's binaries).
