### ISSUE TITLE
Possible memory leak in tab

### ISSUE THREAD

**Issue by GbGp** [qutebrowser/qutebrowser#6623]
**Version info**:
https://paste.the-compiler.org/view/4a6445c1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I am observing a large memory leak when I open and close tabs. The leak is large enough to deplete my system memory during a normal browsing session and make my system irresponsive.

![20210728_18h56m17s_grim](https://user-images.githubusercontent.com/59691707/127367081-d303bd7a-ed6e-4b96-beae-5f953fb851a9.png)

I've been observing this for at least a month, and since I don't see similar issues I assume it must be something on my system or some package from my distro.

Any tip to debug this?

**How to reproduce**
execute the command:
``:repeat 100 open -t;;tab-close``

Memory use is at least ~10 GB.

**Comment by The-Compiler** [comment]
There's a memory leak somewhere indeed, see #1476 (and especially https://github.com/qutebrowser/qutebrowser/issues/1476#issuecomment-733019169).

Your reproducer doesn't tell anything however, since this is virtual memory, i.e. not memory that's necessarily used. In your screenshot you can see qutebrowser using more virtual memory than you have physical RAM in your system, so that information really doesn't say much :wink:. If I open a fresh Chromium instance on my machine, that's instantly "using" around 20GB of virtual memory.

**Comment by GbGp** [comment]
Yes, I know. To be honest I'm a bit confused how to read htop output in this case:
the purple segment you can see on the memory bar on top is all "shared" memory used by qutebrowser (it grows in correlation of the number of tabs until it nearly locks my system and gets freed immediately after I close qutebrowser), but I can't see it reported for the qutebrowser process..
something must be wrong my htop configuration.

Anyway I tried to count the number of thread with `ps hH <qutebrowser_pid> | wc -l`, I can see the number threads creeping up and not going back down when I close tabs.
I will post any update in the other thread.
