### ISSUE TITLE
same-domain policy of headers.referer is not working as intended

### ISSUE THREAD

**Issue by rnhmjoj** [qutebrowser/qutebrowser#6640]
**Version info**:

qutebrowser v2.2.3
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2
CPython: 3.8.9
PyQt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

The same-domain policy should set the full HTTP referer only when browsing between pages of the same domain, otherwise strip the path from the URL. Instead, the path is sent in full: this is security concern.

**How to reproduce**

1. set `content.headers.referer` to `same-domain`
2. click on this link: https://whatsmyreferer.com/
4. notice the full url

**Comment by The-Compiler** [comment]
The setting requires a restart. Does it work after `:restart`?

**Comment by rnhmjoj** [comment]
No, still not working. I also tried with:
```
qutebrowser -T -s content.headers.referer same-domain
```

**Comment by The-Compiler** [comment]
I can reproduce.

From what I can see so far, qutebrowser is passing `--reduced-referrer-granularity` (older Chromium versions) / `--enable-features=ReducedReferrerGranularity` (newer Chromium versions) to the underlying Chromium correctly, and they *do* seem work for [our tests](https://github.com/qutebrowser/qutebrowser/blob/v2.3.1/tests/end2end/test_invocations.py#L414-L444).

I have no idea why they don't seem to work for this page (or possibly in more scenarios), but this might not be something we can fix I'm afraid.

I'll take a closer look after my holidays, in a week or so. FWIW disagreed on this being a security concern, though - it's a privacy concern.

**Comment by The-Compiler** [comment]
Ah, it is working properly, it's just GitHub that's overriding it, via a `Referrer-Policy: no-referrer-when-downgrade` header - you can also reproduce this in Chromium/Chrome which uses the stricter policy [by default](https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default) since a while as well.

If you visit the page [from another website](https://qutebrowser.org/tmp/6640.html) which doesn't override the referer policy, it does work. I'm afraid there's nothing qutebrowser can do to change that, though I clarified the documentation to reflect that.

**Comment by The-Compiler** [comment]
Actually there might be a hack for qutebrowser to override this, see #6643.
