### ISSUE TITLE
Webengine cookies database is locked 

### ISSUE THREAD

**Issue by amerlyq** [qutebrowser/qutebrowser#6680]
**Version info**:

qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.5, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.6
PyQt: 5.15.4

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
At least for several years I was still able to open Cookies DB at the same time, as I have qutebrowser instance running.
But several month ago Webengine had imposed "uniq lock" -- without any reason.
Is it tweakable to allow shared (readonly) access again?

Usage scenario: 
* share some link from logged-in site into qutebrowser plugin by keybinding
* access running qutebrowser Cookies db to get login cookie to that site.
* download page or send some external GET/POST being logged into site.

**How to reproduce**
```bash
$ cd /home/user/.local/share/qutebrowser/webengine
$ sqlite3 Cookies '.tables'
$ sqlite3 "file://$PWD/Cookies?mode=ro" '.tables'
Error: database is locked
```

**Comment by The-Compiler** [comment]
Nope, that's entirely handled by the underlying Chromium.

**Comment by The-Compiler** [comment]
Somewhat related: #5500 - though I'd still prefer using Chromium's storage instead of writing our own.

**Comment by amerlyq** [comment]
Hm, let's approach the problem from other perspectives then:

1) `$QUTE_COOKIE` env var for current opened tab.
2) qute command to query cookie from FIFO `open -t https://www.dict.cc/?s=$QUTE_SELECTED_TEXT`
3) python-qutescript (or another library) to allow to connect to qutebrowser instance externally and access various DB through qutebrowser itself.

Does qutebrowser instance has access to Cookies db, or does Webengine locks it ultimately to single internal connection, inaccessible by qutebrowser?

**Comment by The-Compiler** [comment]
There only is the [QWebEngineCookieStore](https://doc.qt.io/qt-5/qwebenginecookiestore.html) API mentioned in #5500. It doesn't seem to allow reading individual cookies without having to store all of them manually from what I understood. That being said I never quite understood that API.

Looking at your suggestions above:

 1. is likely to run into limits with the maximum environment size, so they'd need to be written to a file, like with e.g.  `QUTE_HTML`. Not sure if it's worth writing it by default for all userscripts though, especially because it might contain sensitive information.
 2. and 3. are not possible because the FIFO is unidirectional

What do you think about a  `cookie-export` command which writes the cookies to the specified location (perhaps optionally filtering for the current tab, though not sure to what extent that is possible)? If it e.g. wrote them to a [netscape-like]{https://unix.stackexchange.com/questions/36531/format-of-cookies-when-using-wget/210282) cookies.txt, that would be useful for manual usage as well, and something I'd probably use myself from time to time too.

Your userscript would then need to run that command and wait a bit for that file to appear. Not exactly perfect but doable. In the future, we could offer nicer programmatic access via Python extensions (#30) perhaps. I can't really tell how complex implementing such a thing would be, though, as like I said I'm a bit confused about how this cookie API works.

As for PRs, the situation is as usual, there's quite a backlog and a lot more people are writing code than there are people reviewing it. Due to a new employment situation (and some other changes coming up, like Qt 6 support) I expect to be busier until the end of the year, but then have more time for qutebrowser between January and August 2022. If such a change turns out simple enough I'll probably find the time to look at it, but I have no idea if it will.

**Comment by amerlyq** [comment]
> (1) is likely to run into limits with the maximum environment size

Hm... I expected $QUTE_COOKIE (passed to plugin) to contain only cookies of current site in tab only, not all cookies at once.
However, considering site may have many cookies at once... the env size you mentioned can become a concern for some BSD, yes.

> It doesn't seem to allow reading individual cookies without having to store all of them manually from what I understood.

If cookies API aren't exposed to qutebrowser, then there is no sense to reimplement all cookies management ourselves only for this small feature. I fear a "very dirty" way I may find to expose inner details in unstable manner won't pass review anyway. Or, more likely considering the schedule, there won't be any desire even to review it :)

> What do you think about a cookie-export command which writes the cookies to the specified location
Your userscript would then need to run that command and wait a bit for that file to appear.

Nice workaround to have, I would love it. 
I can use `inotify` to wait on file create + close, or use sleep if inotify won't work.

> (2) and (3) are not possible because the FIFO is unidirectional
In the future, we could offer nicer programmatic access via Python extensions

It would be really nice to import and access qutebrowser *instance* as library.
Some workflows could be automated in truest sense then, so we could build some kind of ecosystem based on qute.

P.S. 
> optionally filtering for the current tab, though not sure to what extent that is possible

Usually login cookie has same hostkey as site domain. So externally I used something like this to get latest cookie:
```python
    dbpath = Path("~/.local/share/qutebrowser/webengine/Cookies").expanduser()
    fields = ("creation_utc", "expires_utc", "last_access_utc", "name", "value")
    stmt = f"""SELECT {",".join(fields)} FROM cookies
      WHERE host_key=? ORDER BY creation_utc;"""
    hostkey = urlsplit(urllogin).hostname
```
It isn't "generic" enough to cover querying all cookies bound to site, but there is no request for other cookies yet :)
