### ISSUE TITLE
Nyxt info in Readme is outdated

### ISSUE THREAD

**Issue by florhizome** [qutebrowser/qutebrowser#6705]
**Description**
Nyxt doesn't have an active QtWebkit Version anymore. More importantly, how relevant is that security bug still?

**How to reproduce**
[Read Here.](https://github.com/qutebrowser/qutebrowser#similar-projects).

If you want to go that far, I think the relevant info is that Nyxt is designed with the goal to be engine-agnostic and there were versions with QtWebengine and QtWebkit, but since a while only GTKWebkit is actively pursued by the team. 
As a Nyxt user (not only), I was wondering if that security issue is still relevant? because it's 3 years gone and the changes described in the blog post seem to have been implemented. Since it's the only browser you are listing a past bug, does that mean you still have reservations - if yes it would be good to be more concise, to help users and devs make decisions. At least I don't really understand what the issue is, anymore.

**Comment by The-Compiler** [comment]
> If you want to go that far, I think the relevant info is that Nyxt is designed with the goal to be engine-agnostic

I think that that mentioning that it's capable of using two different engines does bring that point across - anything else is more of a theoretical architectural thing.

>  there were versions with QtWebengine and QtWebkit

Updated to point to QtWebEngine instead, since indeed the QtWebKit remark probably isn't relevant anymore.

> but since a while only GTKWebkit is actively pursued by the team

Do you have a source on that? The [FAQ](https://nyxt.atlas.engineer/faq) says *Currently, we support WebKit and WebEngine (Blink).* and the [README](https://github.com/atlas-engineer/nyxt) says *Nyxt has engine support for WebKit and experimental support for WebEngine/Blink.*.

> As a Nyxt user (not only), I was wondering if that security issue is still relevant? because it's 3 years gone and the changes described in the blog post seem to have been implemented. Since it's the only browser you are listing a past bug, does that mean you still have reservations - if yes it would be good to be more concise, to help users and devs make decisions. At least I don't really understand what the issue is, anymore.

Yes, I do still have reservations, based on how:

- They handled this security issue (the right thing to do would have been to fix it and issue a CVE. Instead, if memory serves me right, the people behind that blog post (@jgkamat and @wasamasa) weren't really taken seriously before making the issue public.
- The issue was something I've suspected just by reading the README and the design of Nyxt mentioned there. I admittedly haven't really been following the development since then, but the design still seems to be the same, and I'm not exactly convinced that there won't be any further security issues like this one.
- The developers had a history of claiming things that just aren't factually true, and also made the impression of, let's say, not exactly taking security seriously. This might or might not have changed. I'm afraid I won't have the time to dig into Reddit archives and such, but I know I'm not the only one with this impression.
- In general, the whole thing was marketed very aggressively while disregarding security concerns. 

So, yes, agreed that the blog post probably doesn't exactly point the whole picture. At the same time, I don't think qutebrowser's readme is the right place for my opinion about Nyxt. However, I also think people should be made aware of this when pointing them to Nyxt, and linking to that blog post is the best way to do so. Everyone is free to make their own informed decision based on that.

**Comment by jmercouris** [comment]
I just wanted to make it very clear:

1. we take security very seriously
2. we take privacy very seriously

A major reason why our source code is publicly available is so that it can be audited and problems like the above can be resolved. All of that said, the vulnerability in question has not been valid for several years now.

**Comment by wasamasa** [comment]
The really interesting question is though, do your actions match your words? Putting up source code and saying that you take security and privacy seriously is easy. Actually following through isn't.
