### ISSUE TITLE
[Bug?]: no env variable

### ISSUE THREAD

**Issue by gadefox** [qutebrowser/qutebrowser#6717]
`echo $GNUPGHOME`
/home/fox/.local/share/gpg

`env | grep GNUPGHOME`
GNUPGHOME=/home/fox/.local/share/gpg

but `os.getenv('GNUPGHOME')` returns `None` in the py script..
[version](https://paste.the-compiler.org/view/d4e0d347)

**Comment by The-Compiler** [comment]
Make sure you set your environment variables in a place they are set for all GUI applications, not just your shell.

**Comment by emanuele6** [comment]
Probably `qutebrowser` was started in an environment in which `GNUPGHOME` is not present.

You can check like so:
```bash
$ # get qutebrowsers pid e.g. like so:
$ pgrep qutebrowser
705
$ # run this awk command where 705 is qutebrowser's pid:
$ awk -vRS='\0' -F= -vvarname=GNUPGHOME '$1==varname' /proc/705/environ
```
If the awk command outputs something, that is value of `GNUPGHOME` in the environment of the qutebrowser process; if nothing is outputed, `GNUPGHOME` is not present in the environment of the qutebrowser process.

----

One explaination of this could be that you are setting this variable in your shell's `rc` file (rarely a good idea to do this) which is only run when you start an interactive shell. If that is the case, `GNUPGHOME` will only be set in the environment of your shells are running a terminal and in the programs (e.g. `env(1)` in your example) that you launch from these shell.

You are probably launching `qutebrowser` (for example) from an icon of your desktop environment (that will use the environment of the desktop environment process) that was likely not launched from an interactive shell.

If you kill all the `qutebrowser` processes, e.g. closing all windows or running `killall qutebrowser` and you then launch `qutebrowser` from a terminal, you should see that `GNUPGHOME` will be set in qutebrowser's environment.

What you should do instead of set and "exporting" `GNUPGHOME` in your shell's `rc` file, is setting and exporting it in your login shell's profile file (`~/.bash_profile` for `bash`).

**Comment by gadefox** [comment]
The `qutebrowser` was started from the terminal and I'm using GUI apps which can see env variables, but I'll check this out.
