### ISSUE TITLE
Ability to show info/warning message after script is finished successfully

### ISSUE THREAD

**Issue by gadefox** [qutebrowser/qutebrowser#6718]
Let's say the last line in stdout when info/warning tag is used..

**Comment by The-Compiler** [comment]
See `:help :spawn`...

**Comment by gadefox** [comment]
I understand you're pretty busy, please don't close the issues so quickly.. I mean the message, which is created by a script - so I can't use `--output-messages`, I don't want to show output in other tab and `--verbose` shows diff information..

**Comment by gadefox** [comment]
Let's say I create a `script is_it_raining`, which shows `yes` as a warning and `no` as a message/

**Comment by The-Compiler** [comment]
If I suspect whatever you're opening isn't a bug or valid feature request, I'm going to close it. It's easy to reopen if I happen to be wrong. Consider opening a discussion for more long-lived things, and perhaps also describing your issues in a way they are understandable.

Here it sounds like you want a userscript instead,  using `: message-info` and friends.

**Comment by gadefox** [comment]
I'm pretty sure the issue is self explanatory especially when I use the term stdout

**Comment by The-Compiler** [comment]
Well, I'm pretty sure it was not, as evident above. If you spend a minimal effort on describing an issue, don't be surprised if I take a guess rather than spending countless more round-trips making sure I guessed correctly. Those things go both ways.

Anways, all a closed issue means that there's probably nothing actionable to do for qutebrowser, which is the case here. It doesn't mean it's impossible to continue discussion (contrary to some other projects, I deliberately don't lock closed issues), and I do follow up on comments on closed issues too.

**Comment by gadefox** [comment]
Florian, please consider this as a valid request. Let's say, you launch a **USER**script by a :spawn or a shortcur (:bind). The script is executed successfully, but I'd like to inform the user (me) or show the warning. Thanks a lot..

**Comment by The-Compiler** [comment]
As explained above you can already do that by using the respective `:message-*` commands from there.

**Comment by gadefox** [comment]
Oh, I see.. You mean directly in the **USER**script code(?).. Okay, I'll try. Thanks..

**Comment by amalgame21** [comment]
I think something like `echo ":message-info \"$YOURMESSAGE\"" >> $QUTE_FIFO` in bash userscripts can do this...just for someone searching for the solution.
