### ISSUE TITLE
Network Issue

### ISSUE THREAD

**Issue by rlelchev** [qutebrowser/qutebrowser#6767]
**Version info**:

qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.6, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
 Yes, it does.
**Description**
When i wait a little not using the browser, the internet just stops working and i have to reconnect using networkmanager to use the internet again. It stops only in the browser, anything other than it seems to be able to use the internet.
**How to reproduce**

**Comment by rlelchev** [comment]
Nope. No error messages and it just happens so much. If I have a tab with a lot of network usage at some point the internet on other tabs just stops. When I try to go to a website, it shows an "No internet" error.

**Comment by The-Compiler** [comment]
All the networking stuff is handled by the underlying QtWebEngine/Chromium, so that seems like a problem on your end rather than something in qutebrowser. You'd probably see the same issues with something like KDE Falkon or even Chromium. Converting this to a discussion - maybe someone has an idea, but I doubt there's anything qutebrowser can do.
