### ISSUE TITLE
Some video players are not loading properly

### ISSUE THREAD

**Issue by rlelchev** [qutebrowser/qutebrowser#6847]
**Version info**:

qutebrowser v2.4.0
Git commit: 5e475f415 on master (2021-11-22 18:09:17 +0100)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
Some video players can't load properly and show the default html5 video player layout
**How to reproduce**
 Go to any reddit video and some html5 video players

**Comment by The-Compiler** [comment]
Can you please show your full `:version` information? Do you have a link and ideally a screeshot?

**Comment by rlelchev** [comment]
[This is the link to the version information](https://campfirebg.eu5.org/upload/linux/version.txt)

**Comment by The-Compiler** [comment]
You're using a virtualenv install with a prebuilt Qt/PyQt. Those prebuilt binaries come without proprietary codec support.

**Comment by rlelchev** [comment]
Can i install the proprietary codecs without compiling qutebrowser. I know how slow it is to compile qtwebengine, because i tried doing it, but it even failed. It would be the best if i can somehow make the codecs work with virtualenv

**Comment by The-Compiler** [comment]
No, unless you find someone who offers binary packages of QtWebEngine for Gentoo with proprietary codecs enabled.

**Comment by mschilli87** [comment]
@rlelchev:
>  I know how slow it is to compile qtwebengine, because i tried doing it, but it even failed.

@The-Compiler 
> ...binary packages of QtWebEngine for Gentoo...

[Very unlikely.](https://bugs.gentoo.org/669082) :wink: 

> ...binary packages of QtWebEngine for Gentoo with proprietary codecs enabled.

Even less likely. :stuck_out_tongue_winking_eye: 


Gentoo user here myself. I regularly emerge qutebrowser (and build QtWebEngine) on a > 10 years old notebook. So while, yes, it takes forever, unless you are on a raspberry pi or sth like that, it should be possible for you as well.
Note that having `USE=jumbo-build` for ` dev-qt/qtwebengine` helps and I had to set `MAKEOPTS="-j3"` just for that package (via `/etc/portage/package.env`) to reduce the RAM requirements (I have 16 G, if you have less, an even lower value might be required, which would mean even longer build times though).
If this not working for you on one specific piece of (old) hardware, you could use a faster Gentoo box with `USE=bindist` to make your own binary package or (if architectures don't) match, setuop cross-compiling over your network via `distcc`.
Hope this helps.

**Comment by rlelchev** [comment]
@The-Compiler How do i compile qtwebengine with proprietary codecs enabled? Any use flags i need to set? Any Variables i need to change?

**Comment by The-Compiler** [comment]
I've never used Gentoo. See https://wiki.gentoo.org/wiki/Qutebrowser#USE_flags I guess.

**Comment by rlelchev** [comment]
@mschilli87 Do you think i would need to compile qtwebengine with the bindist use flag turned off to enable proprietary codec support? It says on the Gentoo wiki that you would need to compile qutebrowser with the bindist flag turned off to enable most other codecs, but there isn't even a page for qtwebengine for me to check about it too.

**Comment by mschilli87** [comment]
@rlelchev:
> Do you think i would need to compile qtwebengine with the bindist use flag turned off to enable proprietary codec support?

I don't think I ever tried so I cannot tell you for sure but I have `USE=-bindist` for `dev-qt/qtwebengine` on my systems.
Also, it makes sense that `bindist` would disable the inclusion of proprietary codecs if those are licensed in a way that does not allow binary distribution. Sorry for suggesting `bindist` as a solution for underpowered hardware. I was thinking of [`emerge --buildpkg`](https://wiki.gentoo.org/wiki/Binary_package_guide#Using_--buildpkg_as_an_emerge_option)/[`FEATUTRS=buildpkg`](https://wiki.gentoo.org/wiki/Binary_package_guide#Implementing_buildpkg_as_a_Portage_feature) (on the host combined with an [SHH](https://wiki.gentoo.org/wiki/Binary_package_guide#SSH_binary_package_host)/[NFS binary packge host](https://wiki.gentoo.org/wiki/Binary_package_guide#SSH_binary_package_host) setup on the client) instead. I'll update my comment accordingly.
But like I said, this  requires matching architecture, so probably you'd have/want to go the [`distcc` crossbuilding](https://wiki.gentoo.org/wiki/Raspberry_Pi/Cross_building) route anyways.

Finally, let me suggest to take any further discussion about this to the appropriate Genntoo help channels (forums, IRC, user mailing list) rather than contiuoung to spam the almost 200 GitHub users following qutebrowser, most of which do not even use Gentoo. All that is left here is Gentoo-specific and unrelated to qutebrowser and IMHO there is enough information here for other Gentoo users coming here for help to understand that.

I'd suggest you to update/improve the Gentoo documentation (*e.g.* in their wiki) once you have solved your issue and link that solution here. Since one can comment on closed issues as well. I don't even see a reason to leave this issue open until then TBH since there is nothing actionable for any qutebrowser developer here.
