### ISSUE TITLE
move webengine garbage to .cache

### ISSUE THREAD

**Issue by ura43** [qutebrowser/qutebrowser#6856]
**Version info**:
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**: na

**Description**
The data stored in .local/share/qutebrowser includes a massive subdirectory called webengine. Most of the subdirectories in the webengine dir contain "cache" in their name or otherwise heavily indicate that they are not meant to be human readable or persistent.
Instead I'd expect the webengine cache to be placed into .cache.

**How to reproduce**
Install qutebrowser and use it for a short while

**Comment by The-Compiler** [comment]
The data QtWebEngine/Chromium classifies as cache data is already in `~/.cache/qutebrowser/webengine`. Data in `~/.local/share/qutebrowser/webengine` is stuff QtWebEngine/Chromium considers data which should be persistent. For most of it, that's the case. For things like `Application Cache` or `GPUCache` (2 of 32 isn't "most of it" in my book), you'd need to take it to Chromium.

**Comment by ura43** [comment]
Thanks for the quick feedback, I may take it to chromium :+1:

**Comment by ura43** [comment]
Just to further clarify, I confused `Application Cache` `blob_storage` `GPUCache` `QuotaManager` `Service Worker` `Session Storage` `VideoDecodeStats` `Visited Links` to be cache, but I realize that there is nothing you can reasonably be expected to do about the naming convention of webengine sub folders

**Comment by The-Compiler** [comment]
Yep, indeed all that qutebrowser does is setting the [cachePath](https://doc.qt.io/qt-5/qwebengineprofile.html#cachePath) (to `~/.cache/qutebrowser/webengine`) and [persistentStoragePath](https://doc.qt.io/qt-5/qwebengineprofile.html#persistentStoragePath) (to `~/.local/share/qutebrowser/webengine`).

Chromium does a rather bad job at it indeed, most of its storage is in `~/.config/chromium` despite not being config.

I doubt they will care much to be honest... and without knowing what the data represents in detail, it's hard to say whether it's really cache or persistent data. I know `Visited Links` should be persistent, that's about turning previously visited links e.g. purple instead of blue.
