### ISSUE TITLE
stackexchange and cookies

### ISSUE THREAD

**Issue by intuser** [qutebrowser/qutebrowser#6885]
**Version info**:
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**
Since some month ago, if I visit a page in the stackexchange universe, there would pop up a window asking me about my cookies preferences. I could click on "Accept all cookies" and proceed, or on "Customize settings", choose my preferences and then proceed. That was fine.

Since around two or three weeks clicking on one of those options doesn't do anything. I'm stuck with the pop up window. Because of my weak eyesight I need a zoom factor of 200 or more, and with this factor the pop up window blocks the page, making it unusable.

I have to switch to firefox or crome to visit the page, but of course I would like to continue with qutebrowser.

**How to reproduce**

Visit https://unix.stackexchange.com/ with a high zoom setting. Click on "Accept all cookies" or on "Customize settings" - nothing happens.

**Comment by The-Compiler** [comment]
It doesn't seem to be connected to the zoom factor. It's because you are running Qt 5.12 which is based on Chromium 69, from September 2018. The StackExchange websites seem to be using [the `globalThis` JS builtin](https://caniuse.com/mdn-javascript_builtins_globalthis) which was only introduced in Chromium 71.

That being said, qutebrowser still supports Qt 5.12 for the time being (this might change with qutebrowser v3.0.0). Given we already had a workaround for this for other pages, I extended it to apply to stack exchange pages too.

You could probably make things work on your older version by grabbing [the workaround](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/javascript/quirks/globalthis.user.js), turning it into a proper Greasemonkey script and using that (see `:help :greasemonkey-reload`).

However, I'd recommend looking into getting a more recent Qt and qutebrowser instead, e.g. via a [virtualenv install](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-qutebrowser-with-virtualenv).
