### ISSUE TITLE
YouTube Render Process Crashed (segfault wt. single-process) on Alpine Linux

### ISSUE THREAD

**Issue by applesud** [qutebrowser/qutebrowser#6895]
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.3, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
On Alpine Linux (musl), I get a "Render Process Crashed" whenever I visit youtube, or any site that embeds youtube. It seems to have been getting more frequent for me: at first, it seemed to happen rarely; then it happened a few seconds after each page load; now it happens immediately.
[GDB Stacktrace](https://github.com/qutebrowser/qutebrowser/files/7726129/gdb-stacktrace.txt)
Edit, possibly(?) worth mentioning: I'm using wayland (sway, v1.6.1).

**How to reproduce**
Visit [YouTube](https://youtube.com/) (or any site which embeds YT, possibly other sites as well).
The render process should crash (if single-process, qutebrowser should segfault).

**Comment by The-Compiler** [comment]
The crash happens deep inside Chromium's JS machinery (v8) - there is nothing qutebrowser can do about it.

Since musl is unsupported by both QtWebEngine and the underlying Chromium, your best bet would be to take it to musl or perhaps Alpine Linux (given that they seem to have [various custom patches](https://git.alpinelinux.org/aports/tree/community/qt5-qtwebengine) on top of QtWebEngine related to musl).

**Comment by The-Compiler** [comment]
See also: [Falkon fails to load youtube page — alpinelinux lists](https://lists.alpinelinux.org/~alpine/users/%3C20211213183618.160d836ee12fc78e655b907c%40gmail.com%3E)

**Comment by dm1tz** [comment]
Fixed in [#13333](https://gitlab.alpinelinux.org/alpine/aports/-/issues/13333).
