### ISSUE TITLE
Always show tab number

### ISSUE THREAD

**Issue by Ninmi** [qutebrowser/qutebrowser#6927]
I use `[number]ä` keybind to jump to a specific tab instantly, but the problem has been that the tab number no longer shows once there are too many tabs. Is there a way to force tab numbers to be visible instead of the less useful ... ?

**Comment by toofar** [comment]
You can set `tabs.min_width` to something large enough that it'll still show the start of the tab title. There is currently no option to get rid of the ellipses (unless you pin all the tabs ;)).

I don't think anything has changed in this area recently in our side. It sets the size using https://doc.qt.io/qt-5/qtabbar.html#minimumSizeHint and I have no idea what the units on that are. Possibly it depends on your screen resolution and that's what has changed?

Adding an option to get rid of the ellipses might be a bit tricky because the tab index doesn't have to be the first thing in the tab title, that's just the default first text in `tabs.title.format`. So if someone didn't have the index leading and we truncated the text to some amount it might not be clear in that case that some text had been elided, which is the point of the ellipses.
Possible having a `tabs.shrink = ellipses|never|plain` or something like that. Maybe.

**Comment by Ninmi** [comment]
Unfortunately `tabs.min_width` doesn't seem to be the only constraint affecting the tab size. You can make the tabs 1 pixel wide if you want, but they seem to still be affected by the available overall space, meaning the attribute has no effect once you have too many tabs open. Increasing it ridiculously high up has the same effect, it will simply stop increasing the size of tabs once you run out of space.

It's not really an optimal solution either, so something like `tabs.truncate` seems ideal.

**Comment by toofar** [comment]
> the attribute has no effect once you have too many tabs open

Hmm? It seems to do stuff for me:

`-1` (default)

![image](https://user-images.githubusercontent.com/7419144/147887917-5f59df1f-954d-4e79-a082-97a9b80aaea4.png)

`45`

![image](https://user-images.githubusercontent.com/7419144/147887934-79902401-0dd1-4c7a-b204-cac12c5be7e3.png)

`1000`

![image](https://user-images.githubusercontent.com/7419144/147887958-a5ba2ea9-7b50-4062-881f-374cc7d76329.png)

If I'm misunderstanding what issue you are facing maybe you could describe it further for me?

**Comment by The-Compiler** [comment]
@Ninmi any update on this?

**Comment by Ninmi** [comment]
Sorry, forgot in the midst of holiday stuff.

I tried 10, 100 and 9000 again now like I did last time just to make sure and now it does work, just like toofar demonstrated. So apart from the ... still taking a tiny bit of space unecessarily, this can be closed. I have no clue what I did wrong two weeks ago.
