### ISSUE TITLE
"This browser is no longer supported" errors in Github

### ISSUE THREAD

**Issue by alexkohler** [qutebrowser/qutebrowser#7015]
**Version info**:
qutebrowser v2.4.0
Git commit: 02e23ef12 on master (2022-02-08 20:31:15 +0100)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
I'm suddenly seeing "This browser is no longer supported" issues when navigating to Github. It's accompanied by various drop-downs not loading, etc. e.g., the drop-down for my Github profile on the top right:
![image](https://user-images.githubusercontent.com/5650126/153497800-e15ed1e6-dfd1-4e5c-a57a-ac2b55e53a63.png).

 I tried using a newer user agent with `:set content.headers.user_agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.0.0 Safari/537.36"`, but didn't have any luck there either. Any ideas? Happy to provide additional info.

**How to reproduce**
I''m able to reproduce this simply by navigating to github.com (with/without `temp-basedir`).

---

**Edit by @The-Compiler: See my [comment below](https://github.com/qutebrowser/qutebrowser/issues/7015#issuecomment-1035975151) for some more information about this.**

**Comment by toofar** [comment]
Hmm, what system are you on that ships 5.15.2? It seems to work fine on 5.15.7 (87 based).

> various drop-downs not loading

Can you see if there are any errors in the console of the developer tools (`:devtools`). Might be able to work around it with a polyfill script.

**Comment by alexkohler** [comment]
> Hmm, what system are you on that ships 5.15.2? It seems to work fine on 5.15.7 (87 based).

I'm on an employer-issued image of Ubuntu 18.04. I'm not super familiar with updating QtWebEngine to be completely honest - is there an easy way to install 5.15.7 or would I have to build it from source?

> Can you see if there are any errors in the console of the developer tools (:devtools). Might be able to work around it with a polyfill script.

Was thinking the same thing - didn't end up seeing any errors in the console. Interestingly, I didn't see any requests going out in the Network tab either.

**Comment by toofar** [comment]
You can install qutebrowser and webengine in a virtualenv, see the notes and links in the docs https://qutebrowser.org/doc/install.html#_debian_buster_ubuntu_18_04_lts_linux_mint_19
Maybe relevant: the binary you get when install webengine that way doesn't include any support for proprietary media codecs/formats.

It would be good to dig into why it's functionally breaking at some point but maybe a virtualenv will work for you.

**Comment by The-Compiler** [comment]
A virtualenv install will unfortunately give you QtWebEngine 5.15.2, as later released were source-only...

**Comment by alexkohler** [comment]
Ah yeah that's actually how I originally installed (via cloning + running `python3 scripts/mkvenv.py`). Would  `--pyqt-type link` be an option? (I'm not sure how to install/update QtWebEngine, but I'd be willing to try assuming it's not too difficult :laugh

**Comment by thavelick** [comment]
I have the same issue, and in my dev console I see `GET https://github.githubassets.com/assets/optimizely-ee113889.js net::ERR_BLOCKED_BY_CLIENT`. Interestingly though, I can get to that url if I visit it directly. I've tried turning adblock off and still get that problm.

**Comment by toofar** [comment]
I don't think it is optimizely being blocked, that's just the adblocker doing that.
It seems to be all the "hovercard" functionality isn't being triggered. Looks like whatever part of their framework that registers event listeners isn't running. Actually it looks like none of the modules being imported in https://github.githubassets.com/assets/app/assets/modules/system-lite.js are being executed at all. Not sure why.
It looks like their System.import() isn't working somehow?
Eg on a github page `System.import('./asdf.js').then(() => console.log('yes')).catch((e) => console.log(e))` returns an error (could not load) on 6.2 but nothing on 5.15.2.
idk :shrug:

**Comment by thavelick** [comment]
I now agree, the optimizely snippet has nothing to do with it. I restarted my browser and the blocked url stopped but the problem of certain content remains. At least it does on my mac. On my archlinux machine things seems fine.

**Comment by The-Compiler** [comment]
So, let me elaborate a bit how this happens:

- With Linux distributions like Ubuntu LTS or Debian Stable, you usually get a very old QtWebEngine, e.g. [5.12 on Ubuntu 20.04 LTS](https://packages.ubuntu.com/search?keywords=libqt5webengine5&searchon=names&suite=all&section=all), based on Chromium 69 from September 2018. This is problematic for a lot of websites obviously, and I'm considering dropping support for Qt 5.12 (and possibly 5.13 and 5.14) with qutebrowser 3.0.0. The main problem there is that there is no upgrade path yet with Ubuntu 22.04, though that's coming soon in April. But I digress...
- For a long time, this wasn't too much of a problem, since we could tell people to [install via a virtualenv](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#tox). This installs PyQt5 from PyPI (the Python package index), which contains a newer prebuilt version of QtWebEngine. Problem solved!
- However, the Qt company made [LTS releases commercial only](https://lists.qt-project.org/pipermail/development/2021-January/040798.html) once Qt 6.0 was released in January 2021 ([original announcement](https://www.qt.io/blog/qt-offering-changes-2020)). This was a quite... questionable move, given that QtWebEngine support only came back in September or so, as part of the Qt 6.2 release.
- Thanks to third-party LGPL code from the Chromium project, they were not legally allowed to make QtWebEngine commercial-only though (yay!), however they did the next best thing: Source-only releases without binary builds.
- The newest Qt 5 release, QtWebEngine 5.15.8 (or anything after 5.15.3), is based on Chromium 87 (December 2020), and all seems to still work there.
- However, when installing from binaries, the latest you can get is QtWebEngine 5.15.2, based on Chromium 83 (June 2020). Apparently GitHub has now decided to drop support for that. Can't exactly blame them for it.
- Qt 6 is distributed normally and has QtWebEngine support since Qt 6.2 (September 2021). It comes with a newer Chromium again (90 from April 2021, in [about a month](https://wiki.qt.io/Qt_6.3_Release), 94 from September 2021). However, qutebrowser doesn't fully support it yet (see below).

With all that in mind, there are three ways out of this essentially:

- Get a QtWebEngine 5.15.3+. That's what you get on rolling-release distributions like Archlinux (and many others). On Ubuntu, things get more difficult: You'd either need to build QtWebEngine from source (which is a pain, takes multiple hours even on a modern laptop, various things can go wrong, and you probably need at least 16 GB of RAM). Maybe the [Flatpak](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#via-flatpak) would be an option? That [seems to be using](https://github.com/flathub/io.qt.qtwebengine.BaseApp/blob/branch/5.15-21.08/io.qt.qtwebengine.BaseApp.json#L44) QtWebEngine 5.15.8.
- For us to find a way to [Polyfill](https://en.wikipedia.org/wiki/Polyfill_(programming)) the remaining bits. Might or might not be possible, someone needs to dig in to figure out what's actually missing and triggering this first.
- Using Qt 6 with a much newer QtWebEngine and binary builds available again. This needs major changes to qutebrowser, see #5395. The major problem aren't the changes themselves (those are mostly done in a `qt6-test` branch, minus some remaining bugs and crashes). The major problem is that those changes introduce a lot of code churn, thus making a lot of [open PRs](https://github.com/qutebrowser/qutebrowser/pulls) conflict. Thus, my plan has been to get the PR backlog down a bit again before looking at merging it, but I've been very busy since about August with teaching Python to >100 first-semester students. I have my last deadline for that (grading student projects) this Sunday. After that (and some desperately needed time to recharge), I plan to pick this up again, and I won't be doing anything for the dayjob at the university until July or so.

From an user's perspective, what you can do right now (assuming that you don't want to get into the pain of building QtWebEngine, and don't want to switch distributions) is to either try the Flatpak, or try the `qt6-test` branch, see [instructions](https://github.com/qutebrowser/qutebrowser/issues/5395#issuecomment-964569192). There are still some crashes and rough edges with it, though.

**Comment by alexkohler** [comment]
Really appreciate the detailed reply! I see why building QtWebEngine from source isn't exactly a viable upgrade path for most now. Flatpak seems decent, although the sandboxing is a bit of pain if you want to invoke other binaries from within `qutebrowser`.

If I wanted to use the `qt6-test` branch, are there any prerequisites? I'm currently running into this:
```
➡ python3 scripts/mkvenv.py --venv-dir .venv-qt
...
ERROR: Could not find a version that satisfies the requirement PyQt6-Qt6==6.2.1 (from versions: none)
ERROR: No matching distribution found for PyQt6-Qt6==6.2.1
Subprocess failed, exiting
```

As an aside, a big thanks to all of the maintainers of qutebrowser. It's a fantastic browser that I have hard time living without :slightly_smiling_face:

**Comment by The-Compiler** [comment]
> Flatpak seems decent, although the sandboxing is a bit of pain if you want to invoke other binaries from within qutebrowser.

I think @tinywrkb told me somewhere that there's a way for users to disable the sandbox, so that things like `:spawn` and such work normally - but I can't seem to find it right now.

> ERROR: No matching distribution found for PyQt6-Qt6==6.2.1

Oh, that's something I didn't encounter so far. I suspect this happens because PyQt6-Qt6 is a [manylinux_2_28 wheel](https://pypi.org/project/PyQt6-Qt6/#files), declaring compatibility with glibc 2.28, while Ubuntu 18.04 [ships with](https://packages.ubuntu.com/bionic/libc6) glibc 2.27. Indeed Qt 6 [seems to have dropped](https://doc.qt.io/qt-6/supported-platforms.html) support for Ubuntu 18.04, at least for [its binary packages](https://doc.qt.io/qt-6/supported-platforms.html#availability-of-packages):

> Note: Linux binary packages are linked against glibc 2.28. If you are using a glibc version older than that you need to build Qt from sources or upgrade glibc to 2.28 or newer.

So back to using Flatpak or building from source, I guess. Maybe tell your employer to upgrade to Ubuntu 20.04 or 22.04 somewhen soon :wink:

**Comment by alexkohler** [comment]
Thanks for all of the suggestions! FWIW, Github randomly started working for me again on my `qutebrowser` built with 5.15.2 - maybe something changed/was reverted on Github's end? :shrug:

**Comment by The-Compiler** [comment]
Yup, GitHub Support got back to me too:

>Thanks for getting in touch. We've actually deployed a change today that should make a difference to people on less commonly used browsers.

Case closed, then! Glad to see they care about those even if they don't officially support them. :tada:

**Comment by alexkohler** [comment]
Thanks again for all the help/support debugging this @The-Compiler / @tinywrkb  :partying_face:

**Comment by markstos** [comment]
I can't log into Slack with Qutebrowser today. It may or may not be related to the banner on the login page that says "This browser won't be supported starting March 1, 2022".

**Comment by mschilli87** [comment]
@markstos: FWIW it still works for me but this could depend on which server you end up being served by.

**Comment by markstos** [comment]
Looks like Slack is having an outage today, so I have 8 more days or so until it quits working in Qutebrowser. https://status.slack.com/2022-02/3083852db30af86f

**Comment by toofar** [comment]
@markstos that is true, slack issue https://github.com/qutebrowser/qutebrowser/issues/6822
I can't remember if I tried changing the user agent for it or not, but that might work. Otherwise you'll have to use the qt6-test branch (probably with a different basedir) or their desktop "app".

**Comment by tinywrkb** [comment]
If this still an issue, then you can try the Flathub app.  
I've added a flatpak-spawn wrapper to help running commands on the host, and if nothing will go wrong, then I'll merge flathub/org.qutebrowser.qutebrowser/pull/154 which adds a good number of dependencies for userscripts. It will take a couple of hours for the Flathub app to be updated, so you can try the test build from this PR if you need the extra dependencies.  
Not much userscripts validation has done, and no documentation yet.

Until the docs are up, here are a few hints:

* To give flatpak-spawn access to the host, you need to allow dbus session talk with `org.freedesktop.Flatpak`. This can be done with Flatseal or `flatpak override`.
```
$ flatpak override --user --talk-name=org.freedesktop.Flatpak org.qutebrowser.qutebrowser
```
Note that this will allow running any host command from the sandbox, including executing suid binaries.

* Some userscripts share a temp file with a host application, and by default it's created under `/tmp`, so you might want to have `/tmp` from the host bind-mounted into the sandbox. e.g.
```
$ flatpak override --user --filesystem=/tmp org.qutebrowser.qutebrowser
```
* The launched host command's environment is the same one as that of the System **user** service `flatpak-session-helper.service`.  
If you need to change environment variables, then set them in the environment of the systemd user session. You can do this with `environment.d` or `systemd.generator`.  
* If you need more access to host resources, like pass dir, ssh-agent's socket, etc, then read the `flatpak-override.2` man page.
* `~/.var/app/org.qutebrowser.qutebrowser/data/bin` is in the sandbox's PATH. Create there a symlink pointing to `/app/lib/flatpak-spawn-wrapper/wrapper` with a name of the host command you want to run.  
Commands that are needed for the userscripts [documented in the repo](https://github.com/qutebrowser/qutebrowser/tree/master/misc/userscripts) already have symlinks in `/app/bin`.
* I'm not sure how well it work, but we also have the Python user installation dir in PATH, meaning `~/.var/app/org.qutebrowser.qutebrowser/data/python/bin`.
  * Install the SDK as the runtime is missing pip.
  ```
  $ flatpak install flathub $(flatpak info --show-sdk org.qutebrowser.qutebrowser)
  ```
  * Install pip and wheel to the Python user installation
  ```
  $ flatpak run --devel --command=pip3 org.qutebrowser.qutebrowser install --user --ignore-installed pip wheel
  ```
  * You can remove now the SDK
  ```
  $  flatpak remove flathub $(flatpak info --show-sdk org.qutebrowser.qutebrowser)
  ```
  * Install whatever Python module you need
  ```
  $ flatpak run --command=pip org.qutebrowser.qutebrowser install <python-module>
  ```

**Comment by markstos** [comment]
@tinywrkb Thanks for the notes on Flatpak, How can the Flatpak fix the issue if the port to QT 6 isn't done yet? I'm interested in the security fixes which are including in the newer version of Chromium that QT6 is based on.

**Comment by tinywrkb** [comment]
@markstos OP's issue was due to being stuck on QtWebEngine 5.15.2. Flatpak ship QtWebEngine 5.15.8.  
Chromium source is [this branch](https://invent.kde.org/qt/qt/qtwebengine-chromium/-/commits/87-based/) which has backports for security fixes.  
Specificaly we're on [0ad2814370799a2161057d92231fe3ee00e2fe98](https://invent.kde.org/qt/qt/qtwebengine-chromium/-/tree/0ad2814370799a2161057d92231fe3ee00e2fe98), but I guess we can bump to the latest commit.
