### ISSUE TITLE
Grafana v8.4.2 not working in current macOS Build

### ISSUE THREAD

**Issue by hpfmn** [qutebrowser/qutebrowser#7051]
**Version info**:

```
qutebrowser v2.4.0
Git commit: 36ffff2f6 on HEAD (2021-10-21 18:50:06 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

Instead of grafana you're seeing a page saying 
![image](https://user-images.githubusercontent.com/3973466/156727759-943b3a9d-47a9-476c-8b9a-c342f7ef89dc.png)

and in the console you get the error: `5893.0361824977a7ff2ec46b.js:2 Uncaught SyntaxError: Unexpected token '='`

**How to reproduce**

Install current release of qutebrowser and go to [https://play.grafana.org/](https://play.grafana.org/)

I tested the qt6 branch it isn't affected

**Comment by The-Compiler** [comment]
The browser console shows `Uncaught SyntaxError: Unexpected token '='`, with the error pointing to [this line](https://github.com/grafana/grafana/blob/v8.4.3/packages/grafana-data/src/transformations/transformers/labelsToFields.ts#L73), added in https://github.com/grafana/grafana/pull/40779.

It looks like they're using a [Logical OR assignment (`||=`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment), support for which was [introduced in](https://caniuse.com/mdn-javascript_operators_logical_or_assignment) Chromium 85.

Unfortunately, the macOS releases are based on Chromium 83, because that was the last QtWebEngine release available as a binary (later releases with Chromium upgraded to 87 have been source-only, due to [Qt LTS releases going commercial](https://lists.qt-project.org/pipermail/development/2021-January/040798.html), but Qt is forced to release QtWebEngine sources due to third-party LGPL code from Chromium).

Unfortunately, given that there is a syntax error which can't be worked around / polyfilled, I only see three possible solutions:

- qutebrowser releasing with Qt 6, which is a high priority at the moment (#5395), but will still need some major work to be integrated fully
- qutebrowser building its own QtWebEngine from source for the macOS/Windows releases, which is quite a pain, and not something I'm going to do I'm afraid, especially given that the current situation is temporary
- Grafana avoiding breaking compatibility with Chromium 83, either by not using that operator, or by adjusting their toolchain setting to target an older version when bundling/minifying their JS. I suppose you can ask them, but I wouldn't be surprised if they deem it too old to support (Chromium 85  is from August 2020, so they might decide that that's conservative enough)

No better solution at the moment I'm afraid. Worst-case, it will resolve once Qt 6 support is fully ready.
