### ISSUE TITLE
Store data in custom directory 

### ISSUE THREAD

**Issue by zstg** [qutebrowser/qutebrowser#7212]
Is there a way to set the location where QuteBrowser stores its data ? Instead of `Appdata\Local` and `\AppData\Roaming` ? Maybe by setting an environment variable? 

I’d like it to be contained in , for instance, my conda venv …

**Comment by The-Compiler** [comment]
There's `--basedir`.

**Comment by zstg** [comment]
Sorry, how do i use this flag? 
Should i add it every time i use Qb , or is there a config in the `config.py` file?

**Comment by The-Compiler** [comment]
It can't be in the config file because it also defines where the config file should be stored :wink: 

Either add it manually (when launching from a shell or so), define an alias, or perhaps edit the shortcut you use to launch qutebrowser to include it (I'm not much of a Windows person, but I think that should work).

**Comment by zstg** [comment]
Thanks a lot, that’s just what i did !
