### ISSUE TITLE
Qt 6: Make sure macOS sandboxing is reenabled

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7278]
See https://github.com/pyinstaller/pyinstaller/pull/6903 and https://github.com/qutebrowser/qutebrowser/issues/7252#issuecomment-1160147130

**Comment by hpfmn** [comment]
Is here anything I could help with to progress with this issue?

**Comment by The-Compiler** [comment]
@hpfmn This needs to be fixed in PyInstaller, maybe @rokm can say more.

**Comment by rokm** [comment]
We need to implement support for symlinks in PyInstaller so we can satisfy PyInstaller's current assumptions about library locations *and* stop butchering Qt .framework bundles. Until this is done and the structure of those .framework bundles is properly preserved, it's either disabled sandbox or non-functioning executable (unless, perhaps behavior changed in 6.4.0...).

Or, you can use PySide6 < Qt 6.3.1 and undo the effect of runtime hook from pyinstaller/pyinstaller#6903 by resetting `QTWEBENGINE_DISABLE_SANDBOX` environment variable at the start of your program.

**Comment by toofar** [comment]
PyInstaller has a new release coming up that should address this. It fixes some issues and hacks around collecting stuff (especially around Qt wrappers it seems) and packaging stuff for macOS. The release notes for [5.13.0](https://github.com/pyinstaller/pyinstaller/releases) (the previous release) says that those changes can be breaking and will only be included in a 6.0.0 release.

That has me a bit worried since we want to re-enable webengine (actually chromium) sandbox on mac for the 3.0 release. We do have a WIP PR up to enable that on our side but since there is an upstream fix now it would be good to look at that. I've hacked up [a branch](https://github.com/qutebrowser/qutebrowser/compare/feat/test_pre_release_pyinstaller?expand=1) to do the nightly build jobs with an updated PyInstaller (from their develop branch) to have an early look at any issues. It's failing :smiling_face_with_tear: 

macOS is currently failing in `patch_mac_app` with FileNotFound for `dist/qutebrowser.app/Contents/MacOS/PyQt5/Qt5/lib/QtWebEngineCore.framework/Resources` (same error for PyQt5 and 6 with with different numbers in the path).

Both windows builds are crashing in the smoke test with no log output. Not sure why, there are some "lib not found" warnings in the pyinstaller run but those are present in the current (working) PyQt5 nightly builds too.

As to how we can check that sandboxing is re-enabled on macOS, since the `chrome://sandbox/` page apparently doesn't work there, I think there are three options:
1. try to run an exploit that the sandbox would prevent
2. look at the CLI args of a rendered process for the `--no-sandbox` arg, since that's all `QTWEBENGINE_DISABLE_SANDBOX=1` does
3. look for the info log message [Sandboxing disabled by user.](https://github.com/qt/qtwebengine/blob/6.5.2/src/core/web_engine_context.cpp#L683) that webengine logs when that env var is set

We are already doing (3) but have removed it [temporarily](https://github.com/qutebrowser/qutebrowser/blob/d9e8b63/scripts/dev/build_release.py#L188) for macOS. So just removing that should be fine :crossed_fingers:. Checking a renderer CLI args in a "unit" test probably wouldn't be too hard either.

**Comment by hpfmn** [comment]
You can check if the sandbox is enabled in macOS activity monitor. You can right click on the column names and add the "sandbox" column. The qutebrowser's main process should not be sandboxed but all child processes. It's the same with chrome.

**Comment by rokm** [comment]
> macOS is currently failing in `patch_mac_app` with FileNotFound for `dist/qutebrowser.app/Contents/MacOS/PyQt5/Qt5/lib/QtWebEngineCore.framework/Resources` (same error for PyQt5 and 6 with with different numbers in the path).

The contents are now distributed between `Contents/Frameworks` and `Contents/Resources`. `Contents/MacOS` contains only the program executable.

> Both windows builds are crashing in the smoke test with no log output. Not sure why, there are some "lib not found" warnings in the pyinstaller run but those are present in the current (working) PyQt5 nightly builds too.

For "regular" onedir builds, the layout has also changed - everything but the executable is put into a sub-directory (although that's a different PR).

As a side note, for the `develop` branch to actually work, you need to rebuild the bootloader yourself (or force it to be re-built during installation, by setting `PYINSTALLER_COMPILE_BOOTLOADER=1` environment variable). Otherwise the search locations will not match the new layout (this goes both for macOS .app bundles and for regular onedir builds).

**Comment by toofar** [comment]
> As a side note, for the develop branch to actually work, you need to rebuild the bootloader yourself (or force it to be re-built during installation, by setting PYINSTALLER_COMPILE_BOOTLOADER=1 environment variable). Otherwise the search locations will not match the new layout (this goes both for macOS .app bundles and for regular onedir builds).

Aha, thanks for the info! I'll try to see if I can get that working on CI. Is that a normal step for using develop or just because stuff moved recently and the boatloader hasn't been rebuilt and commited back to the repo yet?

**Comment by rokm** [comment]
> > As a side note, for the develop branch to actually work, you need to rebuild the bootloader yourself (or force it to be re-built during installation, by setting PYINSTALLER_COMPILE_BOOTLOADER=1 environment variable). Otherwise the search locations will not match the new layout (this goes both for macOS .app bundles and for regular onedir builds).
> 
> Aha, thanks for the info! I'll try to see if I can get that working on CI. Is that a normal step for using develop or just because stuff moved recently and the boatloader hasn't been rebuilt and commited back to the repo yet?

We usually rebuild and commit bootloaders only when we make new release, so if you want to use `develop`, it is safest to always rebuild the bootloader yourself (i.e., you can get away without it only if there are no changes in bootloader code since the last release).

**Comment by toofar** [comment]
Looks like the smoke test is working with pyinstaller develop now :tada:. And that includes removing the allowance for "Sandboxing disabled by user", so it should be sandboxing now. The relevant production code change was just:

```path
diff --git a/qutebrowser/utils/resources.py b/qutebrowser/utils/resources.py
index 44e4687368a..b299e4d7e2e 100644
--- a/qutebrowser/utils/resources.py
+++ b/qutebrowser/utils/resources.py
@@ -52,7 +52,16 @@ def _path(filename: str) -> _ResourceType:
     if hasattr(sys, 'frozen'):
         # For PyInstaller, where we can't store resource files in a qutebrowser/ folder
         # because the executable is already named "qutebrowser" (at least on macOS).
-        return pathlib.Path(sys.executable).parent / filename
+        return pathlib.Path(__file__).parent.parent.parent / filename
 
     return importlib_resources.files(qutebrowser) / filename
```

To follow the [recommended way](https://pyinstaller.org/en/stable/runtime-information.html) of finding data files. (The comment above the changed line is probably no-longer true.) There's still some work to do to clean up our build scripts, and I would like to arrange a bit of manual testing (esp for the mac build), but this seems pretty de-risked now in my opinion.

I'm not sure how to suggest going about manual testing. If you install these versions you should *not* open your normal qutbrowser profile with them, wait until a proper release comes you. You could install them and open a temp basedir for testing (find the executable and open it with -T on the command line) the re-install the last release afterwards. So you can open your normal profile again. Sounds cumbersome. You should be able to install as an alternate user or in a VM too...

**Comment by The-Compiler** [comment]
@toofar PyInstaller [seems to support](https://pyinstaller.org/en/stable/CHANGES.html?highlight=importlib.resources#id94) importlib.resources nowadays - while you're at it, any chance you could try what happens if you drop that `if hasattr(sys, 'frozen'):` entirely?

**Comment by toofar** [comment]
Yep, looks like that works (at least as per the smoke tests) after adjusting the data paths to match the source build:

```path
diff --git i/misc/qutebrowser.spec w/misc/qutebrowser.spec
index c74171543fb8..a74a1a1082a8 100644
--- i/misc/qutebrowser.spec
+++ w/misc/qutebrowser.spec
@@ -64,17 +64,17 @@ INFO_PLIST_UPDATES = {

 def get_data_files():
     data_files = [
-        ('../qutebrowser/html', 'html'),
-        ('../qutebrowser/img', 'img'),
-        ('../qutebrowser/icons', 'icons'),
-        ('../qutebrowser/javascript', 'javascript'),
-        ('../qutebrowser/html/doc', 'html/doc'),
-        ('../qutebrowser/git-commit-id', '.'),
-        ('../qutebrowser/config/configdata.yml', 'config'),
+        ('../qutebrowser/html', 'qutebrowser/html'),
+        ('../qutebrowser/img', 'qutebrowser/img'),
+        ('../qutebrowser/icons', 'qutebrowser/icons'),
+        ('../qutebrowser/javascript', 'qutebrowser/javascript'),
+        ('../qutebrowser/html/doc', 'qutebrowser/html/doc'),
+        ('../qutebrowser/git-commit-id', 'qutebrowser/git-commit-id'),
+        ('../qutebrowser/config/configdata.yml', 'qutebrowser/config'),
     ]

     if os.path.exists(os.path.join('qutebrowser', '3rdparty', 'pdfjs')):
-        data_files.append(('../qutebrowser/3rdparty/pdfjs', '3rdparty/pdfjs'))
+        data_files.append(('../qutebrowser/3rdparty/pdfjs', 'qutebrowser/3rdparty/pdfjs'))
     else:
         print("Warning: excluding pdfjs as it's not present!")
```

**Comment by toofar** [comment]
> You can check if the sandbox is enabled in macOS activity monitor. You can right click on the column names and add the "sandbox" column. The qutebrowser's main process should not be sandboxed but all child processes. It's the same with chrome.

![image](https://github.com/qutebrowser/qutebrowser/assets/7419144/2e66f09c-b40b-4fdb-bd72-8641044a4421)

Alright, seems to work on a mac I managed to scrounge up. I'll work on cleaning up my branch this week and than I guess we'll hope a PyInstaller release comes out before the other tasks in the milestone get done (probably 2-3 weeks).
