### ISSUE TITLE
Can't access udrop.com

### ISSUE THREAD

**Issue by GasparVardanyan** [qutebrowser/qutebrowser#7285]
**Version info**:
https://paste.the-compiler.org/view/37285db4

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
I'm getting ERR_EMPTY_RESPONSE opening udrop.com, the site works in lynx and on my phone.

**How to reproduce**
qutebrowser -T udrop.com
lynx udrop.com

**Comment by rien333** [comment]
> the site works in lynx and on my phone

If I switch to a mobile user agent on qutebrowser, the site works for me too. Lynx probably gets delivered a mobile website, because it handles the modern web about as well  as Netscape would. 

In other words, the site probably is just failing to deliver its desktop version. The `ERR_EMPTY_RESPONSE` error indicates as much. Try it on chrome, and if it works, try it on qutebrowser again. 

If it doesn't work on chrome (or firefox, if you prefer), then there's nothing qutebrowser can do (the problem may be with the site admins). 

Workaround (add the ability to switch to a mobile user agent, by pressing <kbd>alt</kbd>+ <kbd>m</kbd>(obile)):

```python
config.bind('<Alt-m>', "message-info 'Toggling desktop/mobile';; config-cycle content.headers.user_agent 'Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Mobile Safari/537.36' 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}'")
```

**Comment by The-Compiler** [comment]
@rien333 is spot-on:

![image](https://user-images.githubusercontent.com/625793/175907957-1100f91a-ba96-44b2-bc8d-55b0b9a533bd.png)

![image](https://user-images.githubusercontent.com/625793/175907978-a219f87d-e622-4fcf-b473-7b81c6152884.png)

**Comment by The-Compiler** [comment]
You mean like the per-domain settings which have been around for a couple of years now?

**Comment by GasparVardanyan** [comment]
Sorry, I've looked for a config option with 'agent' in name and found only the clobal option. Thank you a lot. This is the best web browser I've used ever!

**Comment by GasparVardanyan** [comment]
Seems I have to write a simple greasemonkey userscript
