### ISSUE TITLE
Violentmonkey support

### ISSUE THREAD

**Issue by binex-dsk** [qutebrowser/qutebrowser#7286]
Greasemonkey is continually losing support as more and more scripts are made that Greasemonkey can't run.

Since Violentmonkey is free software, it would be nice to have an implementation containing a majority or all of its features.

**Comment by The-Compiler** [comment]
Care to elaborate? Those are both based on the same syntax, so I don't follow what would be missing at all.

**Comment by binex-dsk** [comment]
This means implementing a good chunk of the features present in the Chrome/FF extension Violentmonkey. Almost all scripts made recently only support Violent/Tampermonkey, and in fact, I believe Greasemonkey was deprecated some time ago.

The extension is open source, so in theory it *should* be possible to port that code over into qutebrowser.

**Comment by The-Compiler** [comment]
Do you have a concrete example of such scripts? Porting the exact code over isn't going to happen I'm afraid.

**Comment by toofar** [comment]
Note that both Greasemonky and Violentmonkey implement that same API. I've had a skim through the release notes of [violentmonkey](https://github.com/violentmonkey/violentmonkey/releases) and [greasemonkey](https://www.greasespot.net/) and haven't seen any significant changes in either API since the [Greasemonkey 4 release](https://www.greasespot.net/2017/09/greasemonkey-4-announcement.html). Which, fwiw, both us and [violentmonkey](https://violentmonkey.github.io/api/gm/#gm) support.

I see that development on Tampermonkey has gone closed source and [Greasemonkey](https://github.com/greasemonkey/greasemonkey/graphs/contributors) has stalled while Violentmonkey is still going strong. So I assume that's what you are referring to. Given that context we could update our docs to be more generic and not refer to Greasemonkey so much, although doing https://github.com/qutebrowser/qutebrowser/issues/6063 first to avoid creating even more confusion (qutescripts are used more then greasemonkey/violentmonkey scripts in qutebrowser) would be good. I added a note to #3238 to track that

I'm going to close this assuming your request was due to confusing naming. To the extent that we support the API used by Violentmonkey, Greasemonkey and Tampermonkey then scripts written for any/all of them should work here too. Although we only implement the most often used parts of the API and don't have a nice management interface or anything (again, see #3238).

If I'm missing something and Violentmonkey has implemented some new API method which lots of scripts are starting to rely on then please let us know!

**Comment by binex-dsk** [comment]
Thanks for clarifying the naming.

There is certainly some API supported only by Tamper & Violentmonkey and not qutebrowser's Greasemonkey implementation. For example - [7kttube](https://github.com/7kt-swe/7kttube) works perfectly fine on Violentmonkey on Brave, but gives a bunch of errors when using it on qutebrowser.

The creator of 7kttube said "Greasemonkey doesn't even support a third of the features this script uses". This doesn't sound true, but based upon my experience, I would not be surprised.

If I can get ahold of all the features Violentmonkey has that aren't present here, I'll let you know :)
