### ISSUE TITLE
[QT6] Focused tabs do not display the title

### ISSUE THREAD

**Issue by palb91** [qutebrowser/qutebrowser#7313]
**Version info**:
https://paste.the-compiler.org/view/ddba7268

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When `tabs.position` is set to `left` or `right`, the current page title disappears. It seems that when there is no favicon, the text is replaced with `...`, and with a favicon there is no text at all.

Maybe related to #7205, it affects only the focused tab and the bug appears with the QT6 version.

**How to reproduce**
``qutebrowser --temp-basedir -s tabs.position left "https://duckduckgo.com" "about:blank"``

**Comment by kekscode** [comment]
Same problem here. If a fix or at least a workaround is possible, i am happy to help testing.

**Comment by toofar** [comment]
So far I've found where stuff is going wrong. I don't understand why this is happening though. Hopefully someone else can see what the actual cause is and we can figure out how to fix it properly.

Firstly this only happens when two things are true:

1. `:set tabs.title.elide` is set to anything other than none (is it something to do with the eliding code? Maybe!)
2. The TabBar stylesheet includes a font override for  `TabBar::tab:selected`  [here](https://github.com/qutebrowser/qutebrowser/blob/a00a14c/qutebrowser/mainwindow/tabwidget.py#L398)

When (printf) debugging and comparing the case with tabs.title.elide set to `right` vs `none` I could see that the place where text first shows up in the `none` case where it didn't show in the `right` case was right after the call to `initStyleOptions()` in [paintEvent](https://github.com/qutebrowser/qutebrowser/blob/09761e2556e045cd299d30e94d39aeb17b7529ff/qutebrowser/mainwindow/tabwidget.py#L709) on our TabBar widget.

[Here](https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/widgets/qtabbar.cpp?h=6.5.0#n210)'s the implementation of `initStyleOptions()`. Only two paths, would be easy to see which one of those the issue lay down if I could be bothered building a debug build (I have not).

Long story short, in the Qt `initStyleOptions()` implementation, in this line:

> QRect textRect = style()->subElementRect(QStyle::SE_TabBarTabText, option, this);

it does not seem to be calling into our custom [QProxyStyle](https://github.com/qutebrowser/qutebrowser/blob/09761e2556e045cd299d30e94d39aeb17b7529ff/qutebrowser/mainwindow/tabwidget.py#L778) that we set with [setStyle()](https://github.com/qutebrowser/qutebrowser/blob/09761e2556e045cd299d30e94d39aeb17b7529ff/qutebrowser/mainwindow/tabwidget.py#L408) in the TabBar constructor.

I can see on Qt5 our `subElementRect()` gets called by `initStyleOptions()`, on Qt6 it doesn't. Even on Qt5 our style proxy doesn't get called directly, when you add a stylesheet to a widget an additional proxy is set on top of the style class. So there's a bit of indirection I haven't got my head around. You can see a QStyleSheetStyle [is initialized](https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/kernel/qwidget.cpp?h=6.5.0#n2569) here, nothing seems to have changed around that area. But there have been a number of changes around SE_TabBarTabText specifically in [QStyleSheetStyle](https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/styles/qstylesheetstyle.cpp?h=6.5.0#n6286). But there seems to only be one new code path there that would cause it to drop down and it doesn't seem very likely (the QStyleOptionTab cast being null?) so not 100% that one of them is the cause (QTBUG-92988, QTBUG-50637 (although that was in 5.15 too) and 729f1ab9a0b9fe6ffdef that doesn't have a ticket in the commit message).

Anyway, it seems to me that our custom style proxy isn't getting called in that case. Turning off elide mode avoids the issue not because it makes our style proxy get called but just because nothing uses the width in that case. So a workaround is to re-do the text eliding in our own code but with the proper text width. Here's a patch that does that with some extra logging to confirm when our proxy style gets called and that it always returns correct sizes:

```patch

diff --git i/qutebrowser/mainwindow/tabwidget.py w/qutebrowser/mainwindow/tabwidget.py
index 5e4f519fa95c..7597afdd58b0 100644
--- i/qutebrowser/mainwindow/tabwidget.py
+++ w/qutebrowser/mainwindow/tabwidget.py
@@ -405,7 +409,8 @@ class TabBar(QTabBar):
     def __init__(self, win_id, parent=None):
         super().__init__(parent)
         self._win_id = win_id
-        self.setStyle(TabBarStyle())
+        self._my_style = TabBarStyle()
+        self.setStyle(self._my_style)
         self.vertical = False
         self._auto_hide_timer = QTimer()
         self._auto_hide_timer.setSingleShot(True)
@@ -696,6 +701,32 @@ class TabBar(QTabBar):
         qtutils.ensure_valid(size)
         return size
 
+    def initStyleOption(self, opt, idx):
+        # call base initStyleOption
+        super().initStyleOption(opt, idx)
+        print(f"initStyleOption: post super init {opt.text=} {opt.rect=}")
+
+        # copy how text is elided in QTabBar
+        def _elided_text(rect):
+            return self.fontMetrics().elidedText(
+                self.tabText(idx),
+                self.elideMode(),
+                rect.width(),
+                Qt.TextFlag.TextShowMnemonic,
+            )
+
+        # compare measurements from a few different style choices
+        our_text_rect = self._my_style.subElementRect(QStyle.SubElement.SE_TabBarTabText, opt, self)
+        style_text_rect = self.style().subElementRect(QStyle.SubElement.SE_TabBarTabText, opt, self)
+        base_text_rect = self._my_style.baseStyle().subElementRect(QStyle.SubElement.SE_TabBarTabText, opt, self)
+        print(f"initStyleOption: {our_text_rect=} elided_text='{_elided_text(our_text_rect)}'")
+        print(f"initStyleOption: {style_text_rect=} elided_text='{_elided_text(style_text_rect)}'")
+        print(f"initStyleOption: {base_text_rect=} elided_text='{_elided_text(base_text_rect)}'")
+
+        # re-do text elising using our style proxy's measurements
+        opt.text = _elided_text(our_text_rect)
+
     def paintEvent(self, event):
         """Override paintEvent to draw the tabs like we want to."""
         p = QStylePainter(self)
@@ -706,7 +737,10 @@ class TabBar(QTabBar):
                 continue
 
             tab = QStyleOptionTab()
+            print(f"\n==== paint start {idx=} ====\n")
+            print(f"paint before: {tab.text=}")
             self.initStyleOption(tab, idx)
+            print(f"paint after: {tab.text=}")
 
             setting = 'colors.tabs'
             if self._tab_pinned(idx):
@@ -894,6 +928,7 @@ class TabBarStyle(QProxyStyle):
             opt: QStyleOption
             widget: QWidget
 
         Return:
             A QRect.
         """
@@ -902,6 +937,7 @@ class TabBarStyle(QProxyStyle):
             if layouts is None:
                 log.misc.warning("Could not get layouts for tab!")
                 return QRect()
+            print(f"subElementRect: {layouts.text=}, {opt.text=}")
             return layouts.text
         elif sr in [QStyle.SubElement.SE_TabWidgetTabBar,
                     QStyle.SubElement.SE_TabBarScrollLeftButton]:
@@ -962,6 +998,7 @@ class TabBarStyle(QProxyStyle):
                 icon_rect.width() + TabBarStyle.ICON_PADDING, 0, 0, 0)
 
         text_rect = self.baseStyle().visualRect(opt.direction, opt.rect, text_rect)
+        print(f"layout: {text_rect=} {indicator_rect=}")
         return Layouts(text=text_rect, icon=icon_rect,
                        indicator=indicator_rect)
```

It's not the best fix, ideally we would find out why our proxy style is not being called. If anyone has a debug build around looking at the stack trace from inside our subElementRect in Qt5 and looking at what has changed in Qt6 might be a good start.

**Comment by toofar** [comment]
I'm going to go ahead with re-doing the text elision in our own overridden `initStyleOption()`. I hope there are no other implications of our custom style not being called from as many places as it used to be, I wouldn't be surprised if there was.

I've tried doing a bunch of other things to try to manipulate the codepaths of QStyleSheetStyle and QCommonStyle to try to get the code flow to call back into python but haven't found any other options.

The reason the text is missing is because it is being elided in it's entirety because [QCommonStylePrivate::tabLayout()](https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/styles/qcommonstyle.cpp?h=6.5.0#n1180) transposes the rectangle that is used for calculating available space. Our vertical tabs the text still is arranged horizontally (the tab bar is vertical, the tabs are not). So the height of the tabs is quite small and because `QCommonStylePrivate::tabLayout()` flips the dimensions around that's what `QTabBar::initStyleOption()` end up using to see how much text can fit. In fact, if you have favicons turned on, all the space it sees is already entirely filled by the icon size, so we get no text.

You can see in tabLayout() it only transposes the dimensions if we are a west or east shape? Could we change the shape while this codepath runs to trick it? Not with the current arrangement of classes and methods, calling `self.setShape()` calls `self.refresh()` which causes an infinite loop.

Since this is only triggered (for now) when we set a font on the TabBarTab subelement, could we avoid it by setting the font on the widget directly? No, that QTabBar doesn't have individual tab widgets and has no method for setting the font per-tab.

What I haven't tried is subclassing QStyleSheetStyle and trying to assign that to the widget and make it do custom stuff. I'm not sure that QWidget lets you set custom stylesheet widgets. But that seems like it would be another headache to maintain anyway.

The call stack looks like this:

```
QTabBar::initStyleOption
  QStyleSheetStyle::subElementRect
    QRenderRule::contentsRect
    QWindowsStyle::subElementRect
      QCommonStyle::subElementRect
        QCommonStylePrivate::tabLayout
```

So the root cause is that since [[QTBUG-92988] if font size is set via stylesheet for QTab, it chops off text - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-92988) we now fall into some old code in QStyleSheetStyle that statically calls QWindowsStyle (instead of the base QStyle the QStyleSheetStyle class was initialized with) than QWindowsStyle statically calls QCommonStyle which calls into a private method which has some old opinionated private code (that seems to duplicate some layoutTab() methods in QTabBar) that we can't override.

In my opinion the main bug here is that QStyleSheetStyle doesn't defer to the base style it is passed in all cases. But this whole area of Qt is a mess of inverted responsibility, duplication, poor composability and short sighted kludges. Most of it hasn't change since Nokia either so it doesn't seem well maintained.
I think I finally see why we want to make out own tab bar (ref: #5308).

**Comment by alkim0** [comment]
I am not the original bug opener, but I can confirm that this commit fixes the problem on my end. Great work.

**Comment by palb91** [comment]
I confirm too, this is fixed. Thanks for the good work!
