### ISSUE TITLE
qute-pass broken after gopass update

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#7336]
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.5 (compiled 5.15.4)

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
After applying `gopass` last version update (v1.14.4), the `qute-pass` userscript won't fill the password after filling the username.

Logs below starts from the `<Tab>` after the username is filled:

```
09:57:24 DEBUG   commands	userscripts:<lambda>:442 Got userscript command: fake-key <Tab>
09:57:24 DEBUG   commands	command:run:535 command called: fake-key ['<Tab>']
09:57:24 DEBUG   commands	command:run:549 Calling qutebrowser.browser.commands.CommandDispatcher.fake_key(<qutebrowser.browser.commands.CommandDispatcher>, '<Tab>', False)
09:57:24 DEBUG   commands	userscripts:<lambda>:442 Got userscript command: mode-enter insert
09:57:24 DEBUG   commands	command:run:535 command called: mode-enter ['insert']
09:57:24 DEBUG   commands	command:run:549 Calling qutebrowser.keyinput.modeman.ModeManager.mode_enter(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.normal: 1>>, 'insert')
09:57:24 DEBUG   modes	modeman:enter:363 Entering mode KeyMode.insert (reason: command)
09:57:24 DEBUG   modes	modeman:leave:424 Ignoring leave request for KeyMode.hint (reason insert mode) as we're in mode KeyMode.insert
09:57:24 DEBUG   statusbar	bar:set_mode_active:321 Setting insert flag to True
09:57:24 DEBUG   procs	guiprocess:_on_finished:301 Process finished with code 0, status 0.
```

**How to reproduce**
1. Go to a login page (ex: github.com/login)
2. `spawn --userscript qute-pass --mode gopass -d bemenu`

**Comment by aleprovencio** [comment]
This issue is solved by configuring a `PASSWORD_STORE_DIR` envvar instead of setting a path on `gopass`'s config.

**Comment by s3lph** [comment]
While setting `PASSWORD_STORE_DIR` might be a functioning workaround, I don't believe it's the best way to solve this.

gopass recently changed their behaviour regarding how exactly `PASSWORD_STORE_DIR` is treated, and this issue was a result of this. The source of this issue is that having `PASSWORD_STORE_DIR` set makes gopass now ignore the path configured in `$XDG_CONFIG_DIR/gopass/config.yaml`. What the qute-pass script does is to always set this envvar for its gopass subprocesses, defaulting to `~/.password-store` if not set via CLI or env.

IMO the "correct" way to fix this would be to not have `arguments.password_store` default to `~/.password-store`, but rather have no default at all - in which case gopass could then get the password store path from it's config file again. However, I don't know how this change would play out with GNU pass.

**Comment by The-Compiler** [comment]
@s3lph I think #7354 by @gnofs solves this in the way you describe, correct?

**Comment by gnofs** [comment]
@The-Compiler My solution still uses a default, although I agree that qute-pass ideally shouldn't have a default at all. However, the function that lists usernames (`find_pass_candidates`) does this by listing files in a given directory, but only when using `pass`. With `gopass` it uses `gopass list`, but `pass` has no equivalent of this, so the only
option would be some very finnicky parsing of `pass show` output, which isn't really viable.

The current approach of checking and overwriting the env variable seems to be the best we can do, but we can avoid hard-coded defaults except when absolutely necessary. A good approach would be to do nothing unless `--password-store` is set, in which case
config and defaults are overridden through the env var. And then specifically in `find_pass_candidates`, fall back to `~/.password-store` only as a last resort.
