### ISSUE TITLE
Option to blackhole cookies without breaking websites

### ISSUE THREAD

**Issue by xjzi** [qutebrowser/qutebrowser#7373]
About 50% of the websites I visit break with the following error when `content.cookies.accept` is set to `never`: `Failed to read the 'localStorage' property from 'Window': Access is denied for this document.` This error is expected, and it's also expected for poorly designed websites to have improper error handling, but I was wondering if there is a way to accept but ignore cookie set requests and return an empty value on get requests. This would significantly increase the portion of sites that work with cookies blocked.

**Comment by xjzi** [comment]
I would be willing to spend some time working on a PR, but first I would like to know if it would be accepted and if you have any advice for implementing it.

**Comment by The-Compiler** [comment]
I'm afraid this isn't possible. The only API [we get from Qt](https://doc.qt.io/qt-6/qwebenginecookiestore.html#setCookieFilter) is the possibility to decide whether the given cookie can be set or not.

It could in theory be possible to do this *for cookies* with a custom cookie jar (#5500). But I believe this would lure the user into a false sense of security, because `setCookieFilter` is documented as:

> The cookie filter also controls other features with tracking capabilities similar to those of cookies; including IndexedDB, DOM storage, filesystem API, service workers, and AppCache.

yet such a custom implementation would not (and has no possibility to) control those things.

The only way I see you could to get this to work is writing a Greasemonkey script which replaces those functions by fake implementations on the JS level. I suspect such a stub would be way too site-specific to be included in qutebrowser, however.
