### ISSUE TITLE
Default encoding does not appear to be applied

### ISSUE THREAD

**Issue by jpalus** [qutebrowser/qutebrowser#7381]
**Version info**:

```
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.4
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Just viewed [vala changelog](https://ftp.fau.de/gnome/sources/vala/0.56/vala-0.56.3.changes) and noticed that non-latin characters are rendered incorrectly in `qutebrowser`. Now if download the file and open it from disk it is rendered correctly. What's even more bizarre  is that if another mirror is selected [vala changelog mirror 2](https://mirrors.dotsrc.org/gnome/sources/vala/0.56/vala-0.56.3.changes) it works fine ([original non-mirrored link](https://download.gnome.org/sources/vala/0.56/vala-0.56.3.changes)). Looking at HTTP headers the only difference that I can spot is that broken site does not provide `Content-Type`, while the good one sends `Content-Type: text/plain`. Is there any chance to get a fallback to `content.default_encoding` (set to `utf-8`) in both cases?

**Comment by The-Compiler** [comment]
That setting did indeed not work properly, see #7281 - already fixed in dd68a84bc94da0492e3e49eaea629e604fe8ebee.

However, it doesn't seem to be taken into account by QtWebEngine/Chromium here (maybe it's only for HTML?). Nothing we can do about it I'm afraid, but the same URL also looks broken in Chromium and Firefox FWIW.
