### ISSUE TITLE
Qt 6: Wrong MPRIS name

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7431]
> A minor regression is that qutebrowser gets a `org.mpris.MediaPlayer2.chromium.instance[0-9]+` D-Bus name for its MPRIS interface, e.g. `org.mpris.MediaPlayer2.chromium.instance124`, instead of `org.mpris.MediaPlayer2.qutebrowser.instance[0-9]+`.  
This seems to be a regression Chromium as I noticed this also in Chrome deb releases, stable and unstable, and only Edge have this set correctly, using `org.mpris.MediaPlayer2.edge.instance[0-9]+`.  
I'm actually stopped using MPRIS, so I'm just looking the xdg-dbus-proxy log (`$ flatpak run --log-session-bus ...`) and D-Feet.

_Originally posted by @tinywrkb in https://github.com/qutebrowser/qutebrowser/issues/5395#issuecomment-1090658761_

Split out from #7202

**Comment by toofar** [comment]
Raised upstream here: https://bugreports.qt.io/browse/QTBUG-112308

**Comment by toofar** [comment]
Upstream points out that chromium made [a change](https://chromium.googlesource.com/chromium/src/+/7d9d666dc6ab533d3d19a13a85136f686808e3ef%5E%21/) in this area aimed at setting the [Identity](https://specifications.freedesktop.org/mpris-spec/2.2/Media_Player.html#Property:Identity) property to the correct application name. `qutebrowser` in this case. With the implied argument that user interfaces should be using that property instead of the dbus name when referring to players.

So I'm asking that if anyone using qutebrowser and Qt6 has had any media player controllers that they routinely use regress from showing `qutebrowser` to showing `chromium` when they upgraded that they please report it here.
Screenshots of the interface would be great, with webengine version and a link to the project.

It might also be interesting to look at the change in Edge that changed that and what rationale they used (probably it predates the recent change by chromium though).

**Comment by Dieterbe** [comment]
For users of firejail, this means the dbus/mpris integration is broken because the name no longer matches.
But just adding `dbus-user.own org.mpris.MediaPlayer2.chromium.*` to the firejail profile is a simple workaround for now.

**Comment by The-Compiler** [comment]
Closing this, given that it seems to be an intended upstream change, hopefully low-impact in general, and qutebrowser is unable to do anything about it.
