### ISSUE TITLE
Website crash

### ISSUE THREAD

**Issue by alkim0** [qutebrowser/qutebrowser#7501]
**Version info**:

qutebrowser v2.5.2
Git commit: 464752edc on master (2022-10-29 16:12:35 +0900)
Backend: QtWebEngine 5.15.11, based on Chromium 87.0.4280.144
Qt: 5.15.7

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
The website http://vldb.org/pvldb/volumes/16/ crashes. Works in chromium.

**How to reproduce**

1. Go to http://vldb.org/pvldb/volumes/16/

**Comment by The-Compiler** [comment]
This is due to the website using a newer JS feature ([Array.at](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at)) which is not available yet with Qt 5.15. And then apparently the website decides to disable itself on errors.

It works fine on Qt 6.2+, and I just added a polyfill which should make it work with older Qt versions too.
