### ISSUE TITLE
Rust user forum (using "discourse" I think) is unsupported in qutebrowser

### ISSUE THREAD

**Issue by fritzrehde** [qutebrowser/qutebrowser#7572]
**Version info**:

qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.12, based on Chromium 87.0.4280.144
Qt: 5.15.8

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
https://users.rust-lang.org/ seems to be unsupported in qutebrowser. It runs on https://github.com/discourse/discourse as far as I know. Is this expected behaviour?

**How to reproduce**

Visit https://users.rust-lang.org/ and you will see a yellow popup at the top saying that the browser is unsupported. You, therefore, cannot login to your account.

**Comment by The-Compiler** [comment]
From looking at the sources, it looks like [the culprit is here](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/scripts/browser-detect.js#L10), i.e. missing support for [CSS `aspect-ratio`](https://caniuse.com/mdn-css_properties_aspect-ratio) - looks like this was added as part of https://github.com/discourse/discourse/pull/19847.

Support was added in Chromium 88, while the latest Qt 5.15 version is based on 87 - so unfortunately not much we can do until Qt 6 support is finally ready, see #7202.

**Comment by The-Compiler** [comment]
FWIW adding `enable-experimental-web-platform-features` to `qt.args` seems to fix this on Qt 5 - see #7639

**Comment by rnhmjoj** [comment]
Another workaround is to just lie about it. Put this in a userscript:
```
original = CSS.supports
CSS.supports = function(x) {
  if (x.startsWith("aspect-ratio"))
    return true
  else
    return original(x)
}
```

**Comment by The-Compiler** [comment]
I've considered that too, but no point to lie about it if you can just make it work instead :wink:

**Comment by markstos** [comment]
Perhaps this can be unpinned now that Qute 3 / QT 6 are the default.

**Comment by toofar** [comment]
Good idea, we also did https://github.com/qutebrowser/qutebrowser/issues/7639 for users still on Qt5 (and with a recent qutebrowser version).

**Comment by fritzrehde** [comment]
Should this issue be closed now then, or what are your proposed further steps?

**Comment by The-Compiler** [comment]
This issue has been closed in January already. There is nothing more qutebrowser can do here, and people should use Qt 6 whenever possible.

**Comment by fritzrehde** [comment]
Ok, sounds good!

**Comment by Vistaus** [comment]
> FWIW adding `enable-experimental-web-platform-features` to `qt.args` seems to fix this on Qt 5 - see #7639

That does not fix it, not even in other QtWebEngine based browsers.

Also, it does not fix it in Falkon and Konqueror with Qt 6 either, so saying that Qt 6 will fix this issue is incorrect.

**Comment by The-Compiler** [comment]
@Vistaus I have no clue what you mean. This issue was fixed with `enable-experimental-web-platform-features` on Qt 5, and it was fixed (and remains so) on Qt 6. If that's not the case for you, you'll need to be more specific.

**Comment by Vistaus** [comment]
@The-Compiler Doesn't work for me. Not with the flag on Qt 5, nor on Qt 6 (with or without the flag).

**Comment by The-Compiler** [comment]
"Doesn't work" isn't exactly specific, all I can say is "works for me" (and presumably for everyone else, given that this issue is almost a year old)...

What exactly isn't working how? Have you tried with `--temp-basedir`? What's your `:version` information?

**Comment by Vistaus** [comment]
What else do you want me to add? I mean: the issue is that Discourse forums show a unsupported browser warning. I've tried the flag on Qt 5 you were talking about and Qt 6 as well, but none of them fix the issue. Discourse forums keep showing that warning and are therefor unusable.

You said “it's fixed in xyz”. I said it's not. Not it Qutebrowser, not in Falkon, not in Konqueror. I don't know how else to make it more clearly.

I'll add version information tomorrow.

**Comment by The-Compiler** [comment]
Ideally, how exactly I can reproduce this, with qutebrowser - i.e. version information, how exactly you passed the flag, and what URL exactly you're looking at. Ideally with `--temp-basedir` so that your config isn't being loaded.

The problem isn't that I don't understand what I'm saying. But evidently you're seeing something different from what I am seeing, so we will need to find out what's different in your situation as compared to mine (or, judging from the silence in this issue for the past months, everyone else's).
