### ISSUE TITLE
CLI argument to wait for existing instance (`--wait`)

### ISSUE THREAD

**Issue by moncheeta** [qutebrowser/qutebrowser#7581]
Add a --nofork option so that the command is still running in the terminal. I would like to use a window swallower with qutebrowser as I like launching programs from the terminal. The problem is that qutebrowser's command exits resulting in the terminal reappearing even though qutebrowser was launched. Is there any way that qutebrowser can have this option? Is there any work around?

**Comment by toofar** [comment]
It works like that for me already. What operating system are you using? How are you launching it?

**Comment by mschilli87** [comment]
I can only reproduce this when qutebrowser is already running and it opens the webpage in the existing instance.

**Comment by Moncheeta** [comment]
I'm using linux and it happens when I already have one instance of qutebrowser open.

**Comment by mschilli87** [comment]
IIRC there was an issue already for spawning new instances for every command but I can't find it. :eyes:

**Comment by The-Compiler** [comment]
Indeed opening qutebrowser when an existing instance is open exits immediately - this isn't because it's forking though, it's because only one qutebrowser process can exist Any other browser works in the same way.

I suppose it would be possible in theory to add a `--wait` argument which makes the second process wait until the main qutebrowser process has exited. But I'll have to admit I'm a bit lukewarm on the idea, given the added complexity for very little gain.
