### ISSUE TITLE
--logfilter crashes at startup

### ISSUE THREAD

**Issue by arza-zara** [qutebrowser/qutebrowser#7769]
```
$ qutebrowser -T about:blank --debug --logfilter sql
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 27, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "qutebrowser.py", line 239, in main
    earlyinit.early_init(args)
  File "misc/earlyinit.py", line 340, in early_init
    info = machinery.init(args)
  File "qt/machinery.py", line 278, in init
    raise Error("init() already called before application init")
qutebrowser.qt.machinery.Error: init() already called before application init
```
Introduced in f65a6923200cc7b738394fb8bacbbc5e356b4969 + cbea80178184890873c97c82696c49eddaf3331a.

**Comment by The-Compiler** [comment]
Confirmed. Happens because we implicitly initialize Qt via `qutebrowser.utils.log` here:

```
  [...]
  .../qutebrowser/qutebrowser.py(236)main()
-> args = parser.parse_args(argv)
  [...]
  /usr/lib/python3.11/argparse.py(2529)_get_value()
-> result = type_func(arg_string)
  .../qutebrowser/qutebrowser.py(160)logfilter_error()
-> from qutebrowser.utils import log
  [...]
  .../qutebrowser/utils/log.py(36)<module>()
-> from qutebrowser.qt import core as qtcore
  [...]
  .../qutebrowser/qt/core.py(17)<module>()
-> machinery.init_implicit()
```

because of:

https://github.com/qutebrowser/qutebrowser/blob/8da62bcbf4e90cc3952decf72b6798540f4b9d10/qutebrowser/qutebrowser.py#L110

and:

https://github.com/qutebrowser/qutebrowser/blob/8da62bcbf4e90cc3952decf72b6798540f4b9d10/qutebrowser/qutebrowser.py#L154-L165

---

I see two ways out of this:

- Postpone validating the logfilter argument and do it in `log.init_log(https://github.com/qutebrowser/qutebrowser/blob/8da62bcbf4e90cc3952decf72b6798540f4b9d10/qutebrowser/qutebrowser.py#L154-L165)` instead
- Declare `qutebrowser.utils.log` a Qt-free zone, and move all Qt related things elsewhere (or to function level imports)

I'd actually prefer the second - we have various places (I think) where we'd benefit from having logging available earlier (before Qt is initialized). For example, we already log the Qt backend information after calling `init_log` because we can't do it earlier:

https://github.com/qutebrowser/qutebrowser/blob/8da62bcbf4e90cc3952decf72b6798540f4b9d10/qutebrowser/misc/earlyinit.py#L292-L301

To get there, we'd need to find a way to get this out of `log.py`:

- `qtcore.qInstallMessageHandler(qt_message_handler)` in `init_log`
- `shutdown_log`
- `disable_qt_msghandler`
- `qt_message_handler`

I think moving things to function-level imports would be somewhat cumbersome, so I'd suggest adding a new `qtlog.py` with its own `init()` method. Then we can call that from `earlyinit.early_init` after `machinery.init`, bu tcan move `init_log` up to much earlier.

@pylbrecht Feel like doing a slightly bigger refactoring? :wink:

**Comment by pylbrecht** [comment]
@The-Compiler you bet I do! Sign me up, please.
