### ISSUE TITLE
Stance on Google's new Web-DRM?

### ISSUE THREAD

**Issue by RobertKosten** [qutebrowser/qutebrowser#7802]
I'm curious how qutebrowser will deal with Google's newest attempt to DRM the Web:
https://github.com/RupertBenWiser/Web-Environment-Integrity/blob/main/explainer.md

which is already integrated into chromium:
https://github.com/chromium/chromium/commit/6f47a22906b2899412e79a2727355efa9cc8f5bd

There is some strong opposition, e.g. 
- https://ia.acs.org.au/article/2023/-google-proposal-could-end-the-open-web.html
- https://securityboulevard.com/2023/07/google-wei-drm-adtech-richixbw/
- https://vivaldi.com/blog/googles-new-dangerous-web-environment-integrity-spec/
- https://tech.slashdot.org/story/23/07/25/1443223/googles-nightmare-web-integrity-api-wants-a-drm-gatekeeper-for-the-web

Full disclosure: I personally consider that thing a massive problem with the very real potential to undermine the free web by encouraging sites to only be accessible by fully locked down browsers, something we ought to nip in the bud as quickly and harshly as we can; That said, I am curious whether you have given it a thought yet.

**Comment by The-Compiler** [comment]
JS APIs are coming from QtWebEngine - nothing qutebrowser itself can do about it. Obviously I'm concerned about it too, but closing this as there's nothing actionable for qutebrowser here.

**Comment by mschilli87** [comment]
@The-Compiler:
> ...there's nothing actionable for qutebrowser here.

I guess in the long run, a switch of browser engines could be considered: Webkit was dropped due to security concerns and moving to WebEngine came at the cost of massive refactoring. But I guess the second it would be easier with all the abstractions and multi-engine support already implemented. Question is, is there such an alternative engine that is viable and would you consider actually supporting it?
Personally, I would drop qutebrowser as long as there is any viable alternative to browse the web DRM-free.
I certainly think maintainers of popular browsers using Google's product in theirs might be in a better position to lobby against this change as their downstream users. If all of them just shrug it off, browser conversion will continue and Alphabet's dominance of the web will keep growing. I understand that is rather polical and might be out of scope here but I think small browsers have an interest in a web of choice.

**Comment by The-Compiler** [comment]
WebKit is still supported technically - and yes, I believe adding a new engine (at least as a proof of concept) should be quite easy because we already support two. It's certainly something I'd want to explore.

However, there is nothing suitable. From the back of my head, there is:

- https://github.com/movableink/webkit (see https://github.com/qutebrowser/qutebrowser/issues/4039#issuecomment-1493410426) - that might be an obvious choice if someone provided Python bindings for it. It's also what makes me somewhat hesitant on actually removing WebKit support.
- Firefox's Gecko and Pale Moon's Goanna fork, both closely tied to the Firefox (/Pale Moon) codebase
- Mozilla's Servo, though with many people laid off, so I don't https://github.com/servo/servo/issues/27579 will move forward a lot
- [Ladybird](https://www.ladybird.dev/) from Serenity OS (recently [got funding](https://awesomekling.substack.com/p/welcoming-shopify-as-a-ladybird-sponsor)). Seems to be somewhat modular, but someone would need to actually expose it to Qt/Python before I'd be willing to play around with it. Also, not too high hopes on this actually being a future-proof thing that can be used for day-to-day browsing.
- Other Chromium wrappers (CEF, Electron)

And no, I don't think small browsers (even together) will make any kind of impact here.

**Comment by mschilli87** [comment]
@The-Compiler: Thank you for sharing your thoughts. Kinda makes me feel like 'we' already lost.

**Comment by The-Compiler** [comment]
We'll see how it actually develops. Not the first time there's some news that initially sounds like it could be the end of qutebrowser (in almost a decade). Also not the first time Google introduces something scary that doesn't actually change anything in the end.

**Comment by natrius** [comment]
Hello, i got asked because i just told somewhere these news and i got asked if there is an alternative to qb if this is integrated, so i searched in the issues. 

While you mention it above 

> Firefox's Gecko and Pale Moon's Goanna fork, both closely tied to the Firefox (/Pale Moon) codebase

you don't say whats the problem with that engine compared to the others in your list. I would appreciate the explanation a lot! :)

**Comment by The-Compiler** [comment]
@natrius I don't understand the question I'm afraid. The explanation is the exact thing you quoted: The engine is closely tied to Firefox and it's thus just not possible to use it in a different project.
