### ISSUE TITLE
Remove default mapping

### ISSUE THREAD

**Issue by kirelagin** [qutebrowser/qutebrowser#781]
qutebrowser won’t let me to remove a default key mapping.

Suppose, I want to get rid of `th` and `tl`. I edit `keys.conf` and remove those mappings leaving just:

```
back -t

forward -t
```

When I start qutebrowser again it reset those default mappings. So it looks like the only way to get rid of them is to map those commands to some keys I never use.

**Comment by The-Compiler** [comment]
It's a tradeoff between "new default keybindings should be available automatically" and "the user should be unable to unbind keys". See #499 for some related discussion.

For now, you can bind keys to the special command `<unbound>` and they won't get messed with. It seems that's not documented in `keys.conf` - it definitely should be.

**Comment by kirelagin** [comment]
Ok, I looked through #499 and #525. Are you saying that right now qutebrowser does something like: “On launch, for each default keybinding, bind it unless the key is bound to something else”?

**Comment by The-Compiler** [comment]
Yes - unless the *key* is bound to someone else, or the *command* is bound to some other key.

**Comment by kirelagin** [comment]
> or the _command_ is bound to some other key

I’m not sure why this last one condition. I mean, it would make sense to either always append the default or state the condition as “unless the command binding is not present in the config” resulting in _empty_ chain not being edited.

**Comment by The-Compiler** [comment]
I'm not sure I understand you properly - the reason that check exists is simple. Let's say you prefer `xh` to `th` for `back -t`:

```
back -t
    xh
```

Now without the command checking logic, `th` would be added because it's unbound, which is probably not what the user intended.

**Comment by kirelagin** [comment]
> Now without the command checking logic, `th` would be added because it's unbound, which is probably not what the user intended.

Yes, and that would be reasonable behaviour. Not very convenient, though.

What I’m trying to say is, now the condition you check is “the command has at least one key bound”. In my opinion it would be reasonable to check for something different, to check that “the command is listed in the config (possibly with an empty chain)”.
This way if a new command is introduced, its default binding will be applied, since the new command won’t be listed in the config. On the other hand, command with _empty_ chains, as in my first comment, won’t be bound to anything, even though they have no keys bound, but they are listed in the config.

**Comment by Permafacture** [comment]
What's wrong with just binding the key to `<unbound>` or some other command?  It seems rather arbitrary to say "I don't want this command bound to anything".  If it isn't bound to a key you use, then there's no harm in it being bound to it's default.  If that's a key you hit on accident sometimes, then set it to `<unbound>`, or if you prefer that key bound to something else, then do that and it's your responsibility to re-bind the other command if you want it somewhere.

If you really want to unbind a command without knowing what it is bound to, it doesn't seem unreasonable that you first find out what it is bound to and then unbind it.

**Comment by kirelagin** [comment]
There is nothing wrong with that, that’s just a little bit less natural than what I am talking about.
What’s wrong with not binding the default key if the command is present in the config? That’s what I would expect as a user.

**Comment by kirelagin** [comment]
To be honest, I gave all this some thought and I have to say that the whole `keys.conf` is somewhat inconvenient. It would be much better to have something like

~~~~
command
    modes: key
    modes: key
~~~~

I find it more natural to think “I want `t` to open a new tab. In which modes does this make sense? Only in normal, so I’ll add `normal: t`. I also want `<Ctrl+t>` to open a new tab and this makes sense in any mode, except for command, so I’ll add `!command: <Ctrl+t>`” and so on. Otherwise I have to bind keys to opening a new tab twice and that’s somewhat unnatural.

Also, is there a way to bind a key in _every_ mode?

**Comment by Permafacture** [comment]
the compiler said:
>[the command is bound automatically] unless the key is bound to something else, **or the command is bound to some other key.**

you said:
>What’s wrong with not binding the default key if the command is present in the config? That’s what I would expect as a user.

So you want something like the inverse of `<unbound>`, where instead of a key being explicitly unbound, a command is explicitly unbound?

**Comment by The-Compiler** [comment]
> Yes, and that would be reasonable behaviour. Not very convenient, though.

IMHO, it'd be even more surprising than the current behavior. If you simply change the key for a command, would you expect the old binding to be readded automatically?

> What’s wrong with not binding the default key if the command is present in the config? That’s what I would expect as a user.

So the current behavior (and the inverse of what you said in the comment above) then? I'm confused.

Having a command without any keybinding currently is only prohibited by the syntax - but I'm really confused on what you're trying to say exactly.

On the other hand, I think in the new config you'll bind keys to commands rather than the other way - actually that's already the case here, but the syntax of the config file doesn't really show that.

> To be honest, I gave all this some thought and I have to say that the whole `keys.conf` is somewhat inconvenient. It would be much better to have something like
> [...]

I disagree. That'd be too verbose and error-prone, IMHO.

> I find it more natural to think “I want `t` to open a new tab. In which modes does this make sense? Only in normal, so I’ll add `normal: t`.

Okay, so with the current syntax, you add `open -t` and `    t` in the `[normal]` section - what's the difference?

> I also want `<Ctrl+t>` to open a new tab and this makes sense in any mode, except for command, so I’ll add `!command: <Ctrl+t>`” and so on.

So you do the same in a `[!command]` section.

> Otherwise I have to bind keys to opening a new tab twice and that’s somewhat unnatural.

I don't see how you'd have to bind them twice.

> Also, is there a way to bind a key in _every_ mode?

Not with the current config syntax - what would your use case be?

**Comment by kirelagin** [comment]
@Permafacture 

>the compiler said:
>
> >[the command is bound automatically] unless the key is bound to something else, or the command is bound to some other key.
>
> you said:
>
> >What’s wrong with not binding the default key if the command is present in the config? That’s what I would expect as a user.
>
>So you want something like the inverse of `<unbound>`, where instead of a key being explicitly unbound, a command is explicitly unbound?

Yes, and I’m saying that there is a very, _very_ natural candidate: keeping the command present in the config with an empty list of keychains.

**Comment by kirelagin** [comment]
@The-Compiler 

> If you simply change the key for a command, would you expect the old binding to be readded automatically?

Of course, no.
In fact, I consider any attempt to add keybindings I didn’t bind explicitly to my config surprising, simply because, normally, software doesn’t do that. Normally, this is handled by an example config file with a list of all available options somewhere in `/usr/share/doc/…` and lists of new options in release notes. This way only options (bindings) that override defaults are kept in the config (you already have #633 for this).

> Having a command without any keybinding currently is only prohibited by the syntax - but I'm really confused on what you're trying to say exactly.

Well, it’s sad that it is prohibited and I don’t see any reason why would it be, grammar-wise. You are probably using pyYAML to parse `keys.conf` and it has this restriciton.

I’m just trying to say that I, as a user, would expect this to work this way. In fact, I would expect removing a command from `keys.conf to do the job in the first place, but after this didn’t work my second guess is leaving the list of keychains empty.

**Comment by kirelagin** [comment]
> you add `open -t` and `t` in the `[normal]` section



> So you **do the same** in a `[!command]` section.



> I don't see how you'd have to bind them twice.

Huh?

-----

Again, I just told you how I _personally_ think about keybindings.
When I figure out that qutebrowser doesn’t do what I expect it to do when I hit `t`, I go to the config and edit `open -t` to use `t`. Then I think “Well, I want `<Ctrl+t>` to do the same”, so I have to go all the way to the end of current section, start a new section, copy-paste the command there and add a new binding.
To be honest, that’s the reason I didn’t actually make `<Ctrl+t>` and some other `<Ctrl+…>` bidings work in modes other then normal. It’s just too much work and so boring. :weary: 

> > Also, is there a way to bind a key in every mode?
>
> Not with the current config syntax - what would your use case be?

Well, I don’t have any particular use-case right now but I can imagine having some `<Ctrl+…>` bindings that work in every mode.

**Comment by The-Compiler** [comment]
>In fact, I consider any attempt to add keybindings I didn’t bind explicitly surprising, simply because, normally, software doesn’t do that. Normally, this is handled by an example config file with a list of all available options somewhere in `/usr/share/doc/…` and lists of new options in release notes.

People's opinions differ in this regard. Originally new bindings wouldn't get added, and people got confused because `$NEW_FEATURE` won't work for them when they press the key.

But I intend this to be configurable with #499.

> This way only options (bindings) that override defaults are kept in the config (you already have #633 for this).

So if the user has bound *any* key in their config, no default bindings get applied at all? If that's not the case you'd still have to somehow unbind default keys.

With the GUI, that'd mean using `:bind x foo` would break everything - that's clearly not acceptable :wink:

>> Having a command without any keybinding currently is only prohibited by the syntax - but I'm really confused on what you're trying to say exactly.
>
>Well, it’s sad that it is prohibited and I don’t see any reason why would it be, grammar-wise. You are probably using pyYAML to parse `keys.conf` and it has this restriciton.

No, it's not related to PyYAML at all (though it will be YAML after #499). It's a [custom parser](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/config/parsers/keyconf.py#L281-L313).

I just don't really see the need for this, and I still think the config should bind *keys* to *commands*, not vice-versa.

---

>When I figure out that qutebrowser doesn’t do what I expect it to do when I hit `t`, I go to the config and edit `open -t` to use `t`. Then I think “Well, I want `<Ctrl+t>` to do the same”, so I have to go all the way to the end of current section, start a new section, copy-paste the command there and add a new binding.

I still don't follow. If you just want to bind `<Ctrl+t>` in the *same mode* you just bound `t`, you just add it below:

```
open -t
    t
    <Ctrl+t>
```

>To be honest, that’s the reason I didn’t actually make `<Ctrl+t>` and some other `<Ctrl+…>` bidings work in modes other then normal. It’s just too much work and so boring. :weary: 

If you want to add it in another mode - yep, you'll need to add another section. Or just add it once with a header with different sections:

```
[normal,insert,...]
open -t
    <Ctrl+t>

foo
    <Ctrl+...>
```

>> > Also, is there a way to bind a key in every mode?
>>
>> Not with the current config syntax - what would your use case be?
>
>Well, I don’t have any particular use-case right now but I can imagine having some `<Ctrl+…>` bindings that work in every mode.

I'm quite sure you wouldn't want to bind them in e.g. passthrough mode, as the point of that is to pass through (almost) all bindings to the webpage.

Other than that, I'm still not sure it's necessary - do you really need to, say, make `<Ctrl+T>` open a new tab even while editing a form, or entering a password, or entering a command?

You should probably be in normal mode 99% of the time anyways.

**Comment by kirelagin** [comment]
> do you really need to, say, make `<Ctrl+T>` open a new tab even while editing a form, or entering a password, or entering a command?

While entering a command, probably no. In insert mode — absolutely. I often find myself hitting `<Ctrl+t>` to google something while writing a text or filling a form. The same is true for `<Ctrl+n>` and `<Ctrl+p>` which I use to switch tabs.

**Comment by kirelagin** [comment]
> I still think the config should bind keys to commands, not vice-versa.

Well I used to think this same way. But when I saw the config of qutebrowser that made me think that it might make sense to bind keys to commands. Because, anyway, in `.vimrc`, `.vimperatorrc` and other files that configure bindings I (and I believe others too) tend to group bidings by command.

That is, I’ll have something like:

~~~~
map t open -t
map <Ctrl+t> open -t
imap <Ctrl+t> open -t
~~~~

anyway, so why not group this into (for example):

~~~~
open -t
  n: t
  n,i: t
~~~~

That’s not critical at all, but what’s critical is not to scatter different modes all around the file. I want similar bindings to be close and right now the only way to achieve this is:

~~~~
[normal]
open -t
  t

[!command]
open -t
  <Ctrl+t>

[normal]
other-command
  …

[!command]
other-command
  …
…
~~~~

which is unnecessarily verbose. :disappointed:

**Comment by Permafacture** [comment]
On a different note.  I understand the benefit in having qute update it's bindings with new commands that are added, but when I'm playing with `me/.config/qutebrowser/keys.conf` and ``:restart`ing qute to test the new settings, I get my text editor saying the file has been changed since I last wrote.  I assume this is qute touching the keys.conf perhaps checking to see if it needs to add any new bindings.

What about having a qute currated keys.conf in the install directory and the user configurable keys.conf imports (or doesn't, if the user comments out the import) those bindings?  Then when qute updates and adds a new feature great!  Oh, it hurts my workflow, so I unbind it in my keys.conf.  Qute never has to touch my keys.conf except on first fresh install.

**Comment by The-Compiler** [comment]
That's exactly what I have in mind with #499.

**Comment by The-Compiler** [comment]
Bindings are implemented in the `new-config` branch now - I've just read through this again, and I think everything should be covered:

- With a `config.py` (which isn't implemented yet), you will be able to group bindings and add them programmatically however you want
- You'll also be able to suppress loading of any default bindings with something like `conf.bindings.default = {}`
- The default binding themselves aren't in the config file anymore.
