### ISSUE TITLE
Mouse hover on github profile avatars/username - disable JS touch API

### ISSUE THREAD

**Issue by alexjp** [qutebrowser/qutebrowser#7814]
**Version info**:
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from override)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
On github, mouse hover for profile avatars do not show.
This seems to happen on Wayland plasma session, but it seems to show mouse hover of profile avatars on X11 Plasma session.

**How to reproduce**
On Wayland Plasma session, hover mouse over a profile avatars or username, and nothing happens.

**Note**
This is in reference to the info on #4890
I hope the issue is now properly done, and everything is OK.

Thank you very much for the awesome browser!

**Comment by The-Compiler** [comment]
Reproduced with sway (even when running sway on X11), and `QT_QPA_PLATFORM=wayland`. Seems to work fine in Weston though.

@alexjp I'm assuming `:version` shows "Platform plugin: wayland" for you too, correct?

**Comment by The-Compiler** [comment]
Reproduced in Qt's example project too and reported upstream: [[QTBUG-115764] [REG 5 -> 6] Hovering does not trigger elements on websites with Wayland - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-115764)

**Comment by alexjp** [comment]
> @alexjp I'm assuming :version shows "Platform plugin: wayland" for you too, correct?

yes, for reference:

```
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from override)
Qt: 6.5.2

CPython: 3.10.12
PyQt: 6.5.2

Qt wrapper: PyQt6 (via QUTE_QT_WRAPPER)

sip: no
colorama: no
jinja2: 3.1.2
pygments: 2.14.0
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
pdf.js: 2.14.305 (/nix/store/9jbpp3148y5vhykmq0rmdwlpk7xq7ng8-source/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.9 30 May 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 23.1.3
Platform: Linux-6.4.7-cachyos-x86_64-with-glibc2.37, 64bit
Linux distribution: NixOS 23.11 (Tapir) (nixos)
Frozen: False
Imported from /nix/store/n7zsb086xg7q8sbg1k20cac9ig4qdwq8-qutebrowser-unstable-2023-04-18/lib/python3.10/site-packages/qutebrowser
Using Python from /nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/bin/python3
Qt library executable path: /nix/store/pmpg1f22rwxrs0kpv5y53jrkn6klx9k6-qtbase-6.5.2/libexec, data path: /nix/store/pmpg1f22rwxrs0kpv5y53jrkn6klx9k6-qtbase-6.5.2

Paths:
cache: /home/alex/.qutebrowser/default/cache
config: /home/alex/.qutebrowser/default/config
data: /home/alex/.qutebrowser/default/data
runtime: /home/alex/.qutebrowser/default/runtime
system data: /nix/store/n7zsb086xg7q8sbg1k20cac9ig4qdwq8-qutebrowser-unstable-2023-04-18/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/alex/.qutebrowser/default/config/config.py has been loaded
Uptime: 0:00:04
```


Thank you very much!!

**Comment by alexjp** [comment]
@The-Compiler I also confirm that adding `--touch-events=disabled` fixes the issue for me (as mentioned in the QT bug report) :)

**Comment by The-Compiler** [comment]
Reopening this as it sounds like we can add a workaround by passing that flag ourselves in older Qt versions.

**Comment by toofar** [comment]
Summarizing this issue so far for my own benefit:

This is about disabling the JS [touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) API because some sites use it for feature detection indicating that you are on a mobile device.
Since this is only the JS touch events API I'm assuming pinch-to-zoom etc that are implemented at the platform level will still work.
This is only reproducible in some environments for now but both Qt ([with 6.6](https://codereview.qt-project.org/c/qt/qtwebengine/+/497028)) and [chromium](https://chromium-review.googlesource.com/c/chromium/src/+/729220) unilaterally disable the touch events API on desktop, so we should be fine to do it everywhere (I guess pinephone is just a really small desktop?).
It would be nice if we could allow users to turn it back on if they with. I'm not sure if the existing code around [juggling args](https://github.com/qutebrowser/qutebrowser/blob/0718b25/qutebrowser/config/qtargs.py) has something for "add Qt arg if this other one isn't there" already or not. Or if it's worth the effort.

**Comment by The-Compiler** [comment]
Related: [Add setting for Js touch events API (Ica860f54) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/497028)
