### ISSUE TITLE
Jpg files don't show up in file picker when filetypes are restricted to images

### ISSUE THREAD

**Issue by martonbalazs** [qutebrowser/qutebrowser#7866]
**Version info**:

qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

If that's important I'm under Arch and i3wm.

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
Jpg files don't show in file picker when webpage restricts to "Accepted types". Changing the option to "JPEG Image" doesn't show them either. Gif on the other hand works.

**How to reproduce**

Go to either Facebook or photos.google.com, try to upload a jpg image. File picker is empty even though photos are there.

How not to reproduce 1): go to drive.google.com, which doesn't restrict file types, then all files show including jpg's.
How not to reproduce 2): trying under Firefox all works as expected so it's not a Facebook/Google/jpg file issue.

**Comment by toofar** [comment]
Could you please try finding a reproducer that doesn't require having an account? I suppose this should be reproducible with plain HTML/JS right?

**Comment by martonbalazs** [comment]
https://yourimageshare.com/
https://upload.photobox.com/en/#computer
both fail the same way.

Interestingly,
https://www.remove.bg/upload
https://imgtr.ee/
https://imgur.com/upload
https://imgbb.com/
each seem to work fine (i.e., jpg's show normally in their file picker window).

**Comment by toofar** [comment]
Oh that is spooky! I can reproduce indeed. You can work around that for now by setting `fileselect.handler` to `external` and then setting all the other `fileselect.*` settings to something that works on your setup. (Which is more complicated than it sounds if you don't have something external setup already.)

I think next steps are to try to reproduce this with falkon of the simplebrowser app in the qtwebengine source and raise upstream, since I assume this is a Qt issue.

Looking at the `accepted_mimetypes` we [get from Qt](https://github.com/qutebrowser/qutebrowser/blob/0718b25/qutebrowser/browser/webengine/webview.py#L270) (and pass back unchanged):
https://yourimageshare.com/: `['image/jpg', 'image/png', 'image/jpeg', 'image/webp', 'image/gif', 'file/ico', 'video/mp4', 'video/webm']`
https://upload.photobox.com/en/#computer: `['image/jpeg', 'image/png']`
https://imgtr.ee/: `['image/*', '.jpg', '.jpeg', '.png', '.bmp', '.gif', '.webp', '.jpeg']`
https://www.remove.bg/upload: `['image/jpeg', 'image/png', '.jpg', '.jpeg', '.png']`

So I guess it works with just the extension but not the mimetype, weird. It's at least something we could work around easily enough though.

**Comment by martonbalazs** [comment]
Thanks for this and your work with Qutebrowser! For now I'm just pasting in absolute image file paths which still works even though the files are not listed in the picker. It's not so bad as I have a handy bash script that copies these paths into the clipboard for me. :-)

**Comment by bitraid** [comment]
I can't reproduce this on ArchLinux/Sway, Windows 10, Windows 11 (v3.0.0/Qt-6.5.2 with `--temp-basedir`)

**Comment by bitraid** [comment]
I also tried XFCE, i3wm. Still can't reproduce. Strange...

**Comment by toofar** [comment]
I think the problem might be that if you have an entry in `~/.local/share/mime/` for a mimetype then [QMimeDatabase](https://doc.qt.io/qt-6/qmimedatabase.html) will no longer look for any more matching entries in `/usr/share/mime/`. WebEngine uses QMimeDatabase to get glob patterns to filter for, if you pass it an extension it'll [make a glob out of that directly](https://github.com/qt/qtwebengine/blob/6.5.2/src/core/file_picker_controller.cpp#L252), instead the ones it gets from QMimeDatabase, hence why it is working for some of those sites.

In my case I have a `~/.local/share/mime/packages/x-wine-extension-jfif.xml` file with content

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="image/jpeg">
    <glob pattern="*.jfif"/>
    <comment>JPEG Image</comment>
  </mime-type>
</mime-info>
```

Here's Qt5 vs Qt6:

```python
from PyQt5.QtCore import QMimeDatabase
QMimeDatabase().mimeTypeForFile('foo.jpg').globPatterns()
# ['*.jpg', '*.jpeg', '*.jpe', '*.jfif']

from PyQt6.QtCore import QMimeDatabase
QMimeDatabase().mimeTypeForFile('foo.jpg').globPatterns()
# ['*.jfif']
```

And moving the xml file from wine out of the way and then regenerating the cache:

```bash
mv ~/.local/share/mime/packages/x-wine-extension-jfif.xml /tmp/
update-mime-database ~/.local/share/mime/
```

And testing Qt6 again:

```python
from PyQt6.QtCore import QMimeDatabase
QMimeDatabase().mimeTypeForFile('foo.jpg').globPatterns()
# ['*.jpg', '*.jpeg', '*.jpe']
```

It's interesting that `QMimeDatabase().mimeTypeForFile('foo.jpg')` still returns the right QMimeType, even though that extension isn't specified in the xml file from wine - so that must be looking in both places, but [QMimeType.globPatterns()](https://doc.qt.io/qt-6/qmimetype.html#globPatterns-prop) doesn't seem to know about the patterns specified elsewhere.

There's been [quite a few optimisations](https://github.com/qt/qtbase/commits/dev/src/corelib/mimetypes/qmimedatabase.cpp) in this area, so maybe one of them is a bit overzealous? (Maybe [this one](https://github.com/qt/qtbase/commit/d8dbc2b95aa89a9f2c8515bd12d2729a018dded4) about caching?)

There is a `QT_NO_MIME_CACHE` env var you can set but that doesn't seem to change the behaviour.

I haven't tried yet but for a reproduce you could probably control where it
looks via:

```python
os.environ['XDG_DATA_DIRS'] = '/tmp/a;/tmp/b'  # mock data dirs
os.environ['XDG_DATA_HOME'] = '/tmp/nope'      # don't look in home folder
```

Then putting mime/packages/*.xml in /tmp/a and /tmp/b

**Comment by martonbalazs** [comment]
Indeed I have references to *.jfif in
~/.local/share/mime/globs
~/.local/share/mime/globs2
~/.local/share/mime/image/jpeg.xml
~/.local/share/mime/packages/x-wine-extension-jfif.xml
the latter two similar to yours. I haven't touched any of these as of yet but I'm happy to do some testing, please let me know how I can help.

**Comment by toofar** [comment]
Upstream ticket raised: https://bugreports.qt.io/browse/QTBUG-116905

This was a fun one. Got to do some spelunking in someone elses code, some stracing and remember how pkg-config works. Thanks for helping triage @bitraid!

If we wanted to do a workaround in qutebrowser it might look something like this. But it's not really a general fix (for that we would have to reproduce the mime database, as this could happen to any mime type) so I'm not planning on adding it in for now. We'll see what upstream says and how many people ask for the workaround to be added.

```diff
diff --git i/qutebrowser/browser/webengine/webview.py w/qutebrowser/browser/webengine/webview.py
index f3f652ad03c8..76567c9455e2 100644
--- i/qutebrowser/browser/webengine/webview.py
+++ w/qutebrowser/browser/webengine/webview.py
@@ -258,6 +258,21 @@ class WebEnginePage(QWebEnginePage):
         self.navigation_request.emit(navigation)
         return navigation.accepted

+    def filepicker_mimetypes_workaround(self, accepted_mimetypes):
+        """Manually add filetype suffixes for know mime types.
+
+        WORKAROUND for https://github.com/qutebrowser/qutebrowser/issues/7866
+        Affected Qt versions: 6.3 - 6.6.0
+        """
+        to_manually_add = {
+            "image/": ".jpg",
+        }
+        for mime, suffix in to_manually_add.items():
+            mime_requested = any(mime in m for m in accepted_mimetypes)
+            suffix_requested = suffix in accepted_mimetypes
+            if mime_requested and not suffix_requested:
+                accepted_mimetypes.append(suffix)
+
     def chooseFiles(
         self,
         mode: QWebEnginePage.FileSelectionMode,
@@ -265,6 +280,7 @@ class WebEnginePage(QWebEnginePage):
         accepted_mimetypes: Iterable[str],
     ) -> List[str]:
         """Override chooseFiles to (optionally) invoke custom file uploader."""
+        self.filepicker_mimetypes_workaround(accepted_mimetypes)
         handler = config.val.fileselect.handler
         if handler == "default":
             return super().chooseFiles(mode, old_files, accepted_mimetypes)
```
