### ISSUE TITLE
Default font style is not applied

### ISSUE THREAD

**Issue by pzant** [qutebrowser/qutebrowser#7870]
**Version info**:
qutebrowser v3.0.0
Git commit:
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qutebrowser don't apply `c.fonts.default_family = 'Roboto Bold'` and appears regular font.
But works with other styles like Black and Medium.

**How to reproduce**
Just set the font in any way.

**Comment by toofar** [comment]
I'm pretty sure this is font-config, not qutebrowser. Have a look at `fc-match 'Roboto Bold'`, fontconfig is probably falling back to your default font.

Additionally I don't believe we support setting the "bold" attribute in the `fonts.default_family` setting. Not sure if that's intentional or not but that's the way it looks to me. The `fonts.default_family` setting doesn't take a full font specification but only takes a family to be substituted into the other `fonts.*` settings.

So if you want to set everything to bold looks like you'll have to add the bold attribute to all of the various font settings (eg `c.fonts.completion.entry 'bold default_size default_family'`).

**Comment by pzant** [comment]
Indeed, fc-match refer to Regular, maybe then developer can add support for this feature through `fonts.default_style` or processing `fonts.default_family` so that it accepts Style?

**Comment by The-Compiler** [comment]
Going to say no to this one, I'm afraid. Wanting to have *everything* in bold seems like a very exotic use-case to me (vs. having everything sized up, or everything in a different font family). It's already possible, and I don't think it's important enough for there to be a shorthand for this.
