### ISSUE TITLE
Viewing pdfs inline fails on Arch Linux because the system's pdf.js file is now called "pdf.mjs"

### ISSUE THREAD

**Issue by mortenivar** [qutebrowser/qutebrowser#7999]
**Version info**:

qutebrowser v3.0.2
Git commit:
Backend: QtWebEngine 6.6, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.0

pdfjs is version 4.0.189-1 from Arch Linux

**Does the bug happen if you start with `--temp-basedir`?**:

It doesn't show the pdf file inline by default, but it is shown if I hit ctrl-p

**Description**

**How to reproduce**

click on a pdf file link, e.g. https://www.supremecourt.uk/cases/docs/uksc-2022-0066-judgment.pdf and it fails with this message:

"No pdf.js installation found
Error while opening qute://pdfjs/web/viewer.html?filename=tmppjdjv1gv_uksc-2022-0066-judgment.pdf&file=&source=https://www.supremecourt.uk/cases/docs/uksc-2022-0066-judgment.pdf
qutebrowser can't find a suitable pdf.js installation

It looks like you set content.pdfjs to true but qutebrowser can't find the required files."

A temporary solution is to copy /usr/share/pdf.js/build/pdf.mjs to /usr/share/pdf.js/build/pdf.js

**Comment by The-Compiler** [comment]
Some related resources:

- #7992 
- [FS#80236 : [qutebrowser] new pdfjs version breaks pdf viewing](https://bugs.archlinux.org/task/80236)
- [(1) pdfjs and pdfjs-legacy are broken. : qutebrowser](https://www.reddit.com/r/qutebrowser/comments/17t7bon/pdfjs_and_pdfjslegacy_are_broken/)

**Comment by The-Compiler** [comment]
From the Archlinux issue, there might be another problem:

```
10:53:00 ERROR message message:error:63 JS: [qute://pdfjs/web/viewer.mjs:13562] Fetch API cannot load[ qute://pdfjs/web/locale/locale.json](qute://pdfjs/web/locale/locale.json). URL scheme "qute" is not supported.
10:53:00 ERROR message message:error:63 JS: [qute://pdfjs/web/viewer.mjs:13562] Uncaught (in promise) TypeError: Failed to fetch
```

The Fetch API won't work with how qutebrowser integrates pdf.js. qutebrowser has a hack to fix that:
https://github.com/qutebrowser/qutebrowser/blob/main/qutebrowser/browser/pdfjs.py#L63-L68

But possibly something changed which broke that. Could be an easy fix, could be a pain to fix. Since Qt 6.6, there is also [a flag](https://doc.qt.io/qt-6/qwebengineurlscheme.html#Flag-enum) to allow the Fetch API on third-party URL schemes, but that still won't be a trivial fix (requires us splitting `qute://` into separate schemes, I thought we had an issue somewhere...).

**Comment by toofar** [comment]
This change to .mjs files is being pulled into our nightly builds now too.
