### ISSUE TITLE
[suggestion] Dependency-free userscripts

### ISSUE THREAD

**Issue by 2gn** [qutebrowser/qutebrowser#8116]
Currently, there are many userscripts that depends on some python packages and command-line tools. Some of them require system-wide installation of the dependency. I think they should be compiled in some ways for a battery-included experience. For example, rust compiles all dependency into a binary and unless commands are called from the program, it requires nothing. How do you think about this?

**Comment by The-Compiler** [comment]
For Linux, this is more trouble than it's worth, as every userscript would come with its own Python, and have constraints regarding glibc compatibility and such. Instead, you can always create [a virtualenv](https://chriswarrick.com/blog/2018/09/04/python-virtual-environments/), or for Python binaries, use something like [pipx](https://github.com/pypa/pipx).

For Windows/macOS, this is more interesting as the OS itself is a bit more homogenous, but also because people usually don't have Python and such installed. However, we already have #3218 for that.
