### ISSUE TITLE
Nightly PyInstaller failures with PyQt 5.15.14

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#8260]
After #8256, we [now get](https://github.com/qutebrowser/qutebrowser/actions/runs/9925218922):

```
04:11:10 WARNING: QtWebEngine version mismatch - unexpected behavior might occur, please open a bug about this.
  Early version: QtWebEngine 5.15.2
  based on Chromium 83.0.4103.122
  with security patches up to 86.0.4240.183 (plus any distribution patches)
  (source: PyQt)
  Real version:  QtWebEngine 5.15.14
  based on Chromium 87.0.4280.144
  with security patches up to 113.0.5672.64 (plus any distribution patches)
  (source: UA)
```

on macOS and

```
ERROR: Could not find a version that satisfies the requirement PyQt5-Qt5==5.15.14 (from versions: 5.15.2)
```

on Windows.

For the former, I suppose we can adjust `WebEngineVersions.from_pyqt()` to deal with that. For the latter, I guess we could adjust our pinning logic.

...or alternatively, we just throw out Qt 5 nightly PyInstaller builds already.

**Comment by toofar** [comment]
Recapping this for myself:

1. Qt only provides binary builds of patch releases until the next minor release is available
2. For binary releases we use binaries provided by PyQt / Riverbank, which are presumably usually ones directly from Qt
3. The last binary release for Qt5 was 5.15.2, which is what we've been including in these Qt5 nightly releases
4. Recently PyQt provided their own binary builds of Qt 5.15.14 and 5.15.15
5. But only for Linux and macOS, there's no binaries for windows
6. Also the macOS builds seem to provide us with the old version number (5.15.2) instead of the one they are built from 
7. The requirements update job runs on linux so our 5.15 requirements file has been updated to 5.15.15 but the releases for macOS and Windows are failing

So we could:

1. fix our 5.15 requirements file at 5.15.2
2. have different requirements file for windows
3. stop providing windows nightly builds of 5.15 (and make the macOS ones not complain)
    * for our main releases we already only provide builds with the latest version of Qt at release time
    * we also only run CI tests for windows and macOS on the latest version of Qt
3. stop building any 5.15 nightly builds
    * we don't provide main releases based on Qt5, so what value do these nightly ones have?

I'm open to being convinced otherwise but for now I'm going to do 4: stop building 5.15 nightly builds. My reasoning as follows:

1. the nightly builds are only for testing binary releases which we only make for macOS and Windows
2. we've been making binary releases with Qt6 for over a year now, I don't see any need for us to switch back to 5.15 ones

For the record:
1. we are still testing qutebrowser against 5.15 on Linux on CI for the time being, using Qt built for Arch, but it's very much a second class target
2. the chrome version QtWebEngine 5.15 is built on is [four years old](https://developer.chrome.com/blog/new-in-chrome-87) and we don't recommend anyone uses it for day to day browsing
