### ISSUE TITLE
Qutebrowser Display Issue: White Screen and Warnings with NVIDIA GTX 1650 Ti on Arch Linux

### ISSUE THREAD

**Issue by ekokurniawann** [qutebrowser/qutebrowser#8281]
Version info:
qutebrowser 3.2.1
Python: 3.12.0
Qt: 6.5.0
PyQt: 6.5.0
QtWebEngine: 6.5.0

Does the bug happen if you start with --temp-basedir?:
Yes, the issue persists when starting qutebrowser with --temp-basedir.

Description:
Qutebrowser fails to display any web content, rendering the main browser window completely white except for a small search bar and "DuckDuckGo" text at the top. Additionally, the following warnings appear in the terminal output:

- "Could not find the Qt platform plugin 'wayland' in ''"
- "Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'"
- "Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/lib/qt6/qtwebengine_dictionaries'"
- "eglSwapBuffers failed with 0x300d, surface: 0x0"

How to reproduce:
1.Install qutebrowser version 3.2.1 on Arch Linux with an NVIDIA GeForce GTX 1650 Ti Mobile GPU.
2.Start qutebrowser and observe that the browser window is white with only the search bar visible.
3.Check the terminal output for the above warnings.

Additional Information:
Arch Linux x86_64
Kernel: Linux 6.10.4-arch2-1
DE: GNOME 46.4 with Wayland
NVIDIA Driver: Latest available version
GPU: NVIDIA GeForce GTX 1650 Ti Mobile

**Comment by The-Compiler** [comment]
This sounds like an issue with your configuration rather than with qutebrowser.

> "Could not find the Qt platform plugin 'wayland' in ''"

Seems like you set `QT_QTA_PLATFORM=wayland` (or maybe wayland was autodetected by Qt?), but you don't have qt6-wayland installed. Any Qt application will show the same issue.

> "Path override failed for key base::DIR_APP_DICTIONARIES and path ..."

Those are bogus and will be [fixed in Qt soon](https://codereview.qt-project.org/c/qt/qtwebengine/+/553597).

> "eglSwapBuffers failed with 0x300d, surface: 0x0"

That's likely the actual issue. From a quick search, people have this issue [with other Qt applications](https://bbs.archlinux.org/viewtopic.php?id=298204) too, so again, nothing qutebrowser can do here.

Can you see if running the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py) shows the same behavior?

**Comment by ekokurniawann** [comment]
Thank you for your assistance. The issue I was facing with Qt and Wayland has been resolved.
