### ISSUE TITLE
Inconsistent number prefix behavior for navigation commands

### ISSUE THREAD

**Issue by JSON-HSB** [qutebrowser/qutebrowser#8373]
**Version info**: 
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.8
  based on Chromium 122.0.6261.171
  with security patches up to 129.0.6668.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.0

Some navigation commands support number prefixes (like 5j for 5 lines down), while others don't work with numbers. Example:

Works:
- 5j - scrolls 5 lines down
- 5k - scrolls 5 lines up

Doesn't work:
- 5space - should scroll 5 pages
- 5PgDown - should scroll 5 pages

This inconsistency makes navigation less predictable. All movement commands should handle number prefixes consistently.

**Comment by toofar** [comment]
The `input.forward_unbound_keys` setting is set to `auto` by default, which means unbound keys are forwarded to the webview (QtWebEngine in this case). `<Space>` and `<PgDown>` aren't bound by default, so counts don't work by them because the keys aren't handled by qutebrowser.

If you would like to have more consistency in navigation commands, try setting forward_unbound_keys to `none` and adding new bindings until everything works as you expect. Feel free to report back with any other bindings you think should be the default! It's not the first time we've got this question.

Have a look at the default binding for <Ctrl+f>, I guess you would want to copy that for an equivalent to the default behaviour. `:scroll-page` scrolls based on multiples of the viewport, so `:bind --mode normal <Space> scroll-page 0 1` should make it scroll down so all the content on the page now is out of view.

**Comment by The-Compiler** [comment]
See #4845 - as long as those aren't handled by qutebrowser, indeed counts won't work.
