### ISSUE TITLE
Crashing when suspending

### ISSUE THREAD

**Issue by blibers** [qutebrowser/qutebrowser#8392]
**Version info**:
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.8
  based on Chromium 122.0.6261.171
  with security patches up to 129.0.6668.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qutebrowser is crashing every time I suspend my machine. This did not happen before this upgrade.
I'm running Artix Linux.

**How to reproduce**
Open qutebrowser, suspend machine, go back, where is qutebrowser? Launch qutebrowser, crash notice.

**Comment by The-Compiler** [comment]
This sounds like an issue with Qt rather than qutebrowser. Not much I can say without a C++ stacktrace. To get one, please:

- Set up [debuginfod](https://wiki.archlinux.org/title/Debuginfod) and install `gdb`
- Run `ulimit -c unlimited`
- Run `qutebrowser --temp-basedir` and reproduce the crash
- You should find a `core.*` file in the current directory
- Run `gdb python3 core.*` and run `bt` at the gdb prompt (you might want to do `set pagination off` and `set logging enabled on` first, so you get the output in a `gdb.txt`)

**Comment by blibers** [comment]
Qt got updated, it's all set now! Thanks Florian, I'm a big fan of your work!
