### ISSUE TITLE
Make scheme/download handlers configurable.

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#841]
Using an unknown scheme or opening a download currently simply uses `xdg-open` - this should have some optional config in qutebrowser, as configuring `xdg-open` can be... hard.

**Comment by The-Compiler** [comment]
Currently we use `QDesktopServices.openUrl` to handle this - instead we could have something like a `general -> open-dispatcher` setting (or whatever a good name would be...) which is empty by default, and a `utils.open_file` which uses either that or `QDesktopServices` (if empty).

**Comment by swalladge** [comment]
Some ideas for custom/configurable scheme handlers:

- `QDesktopServices.setUrlHandler` looks like it allows for registering custom schemes.
- might need a settings dictionary/list type for storing mappings
- it would need to be linked it so that on qute start or settings change it registers everything with `setUrlHandler`.
- a command would be needed so you can run `:handle mailto: evolution {}` or `:handle-scheme mailto: some_function`

**Comment by The-Compiler** [comment]
I'd say handling them ourselves instead of using `openUrl` and `setUrlHandler` would probably be the simpler approach.

A dict/list type for the config both already exist, though with the new config format (#499) those should be much simpler to use too, including some way to easily modify dicts/lists via `:set` commands. So I don't think we need a separate command.

**Comment by The-Compiler** [comment]
There's `downloads.open_dispatcher` since a while already - and we can't configure how custom schemes are handled with QtWebEngine.
