### ISSUE TITLE
Pinned tabs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#926]
Like in Firefox - tabs can be pinned - then they only show the favicon and are "protected" - see #13 too.

![ye8](https://cloud.githubusercontent.com/assets/625793/9706101/e7965070-54da-11e5-9a6b-4b7b29d93552.png)

**Comment by Carpetsmoker** [comment]
In `dwb`, this was sort of implemented by "protecting" tabs with `xd`, `xu`, and `<C-p>`. From #13 :

>[n]C-P  
>Protect tab [n]. Closing this tab must be confirmed (command protect, aliases: prot).

>[n]xd  
>Lock tab [n]. Locking a tab will lock this tab to the current domain, it’s not possible to navigate to another domain until unlocked. lock_domain, aliases: dlock).

>[n]xu  
>Lock tab [n]. Locking a tab will lock this tab to the current uri, it’s not possible to navigate to another uri until unlocked. lock_uri, aliases: ulock).

Tabs in Qutebrowser work different than in Firefox: In Firefox, a tab takes up a maximum of *n* pixels of space (about 200). In qutebrowser, a tab takes up total_width / num_tabs of space. Not sure if only the showing the favicon fits well in this?

**Comment by The-Compiler** [comment]
I'd say those tabs will need to be drawn smaller then - yeah.

This is one of those "I won't work on it, but it was requested once or twice, so maybe someone picks this up" issues :wink:

**Comment by shellkr** [comment]
I wish someone picked this up because it is an awesome feature. One that probably would make me a fulltime user of qutebrowser. A reason why can be to have "active pages" like G+, Twitter, Reddit, CNN and other frequently used ones pinned. Who are constantly updated. While temporary pages like opening an url from a post in the G+ flow in the normal tab field. So you can save it for readin later and just continue reading on your pinned G+ page. Pinned also take a lot less space so extra good for frequently visited pages.

favicons is a fixed size. So you can dedicate space calculated from the number of pinned tabs. Then have the normal dynamically resized tab space to the right of it.

**Comment by thomwiggers** [comment]
A large part of pinned tabs for me is that they are also automatically opened on start. That's very useful for all the 'app-in-the-browser' stuff like WhatsApp Web, Slack, TweetDeck, ...

**Comment by lahwaacz** [comment]
I'm wondering if we could have a `:reload --pinned` or something like that to reload all pinned tabs at once? It would be useful e.g. when I don't close the browser over night and want to quickly "update" the content in the morning.

**Comment by The-Compiler** [comment]
Hmm - I'd prefer having something like `:foreach --pinned reload` or so - see #267. I haven't looked at that yet, though.
